/- Generated by Lem from basic_classes.lem. -/

import LemLib

/- **************************************************************************** -/
/-  Basic Type Classes                                                          -/
/- **************************************************************************** -/

import Bool
open Bool
 




/-  ==========================================================================  -/
/-  Equality                                                                    -/
/-  ==========================================================================  -/

/-  Lem`s default equality (=) is defined by the following type-class Eq.
   This typeclass should define equality on an abstract datatype 'a. It should
   always coincide with the default equality of Coq, HOL and Isabelle.
   For OCaml, it might be different, since abstract datatypes like sets
   might have fancy equalities.  -/

class  Eq (a : Type) where 
 
  isEqual :  a →  a →  Bool

  isInequal :  a →  a →  Bool

open  Eq

/- removed value specification -/

/- removed value specification -/

def  unsafe_structural_inequality  {a : Type}  (x : a) (y : a)  : Bool :=  not  (x  ==  y)
/-  -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- 


/-  ==========================================================================  -/
/-  Orderings                                                                   -/
/-  ==========================================================================  -/

/-  The type-class Ord represents total orders (also called linear orders)  -/
inductive  ordering where 
  |  LT : ordering  
  |  EQ : ordering  
  |  GT : ordering 
  deriving BEq
open ordering
instance : Inhabited (ordering) where
  default := LT -/

def  orderingIsLess  (r : LemOrdering)        : Bool :=  (match  r with |  LemOrdering.LT =>  true |  _ =>  false )
def  orderingIsGreater  (r : LemOrdering)     : Bool :=  (match  r with |  LemOrdering.GT =>  true |  _ =>  false )
def  orderingIsEqual  (r : LemOrdering)       : Bool :=  (match  r with |  LemOrdering.EQ =>  true |  _ =>  false )
/- removed top-level value definition -/
/- removed top-level value definition -/

def  ordering_cases  {a : Type}  (r : LemOrdering) (lt : a) (eq : a) (gt : a)  : a := 
  if  orderingIsLess  r then  lt  else 
  if  orderingIsEqual  r then  eq  else  gt
/- removed value specification -/

/- removed top-level value definition -/

instance   : Eq LemOrdering where
 
    isEqual   :=  (fun x y => x == y)

    isInequal   x  y  :=  not  (x  ==  y)


class  Ord (a : Type) where 
 
  compare :                  a →  a →  LemOrdering

  isLess :          a →  a →  Bool

  isLessEqual :     a →  a →  Bool

  isGreater :       a →  a →  Bool

  isGreaterEqual :  a →  a →  Bool 

open  Ord

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/



def  genericCompare  {a : Type}   (less : a →  a →  Bool)  (equal : a →  a →  Bool)  (x  : a)  (y  : a)  : LemOrdering := 
  if  less  x  y then 
    LemOrdering.LT
   else  if  equal  x  y then 
    LemOrdering.EQ
   else 
    LemOrdering.GT
/- removed value specification -/

def  ordCompare  {a : Type} [Eq a] [Ord a]  (x : a) (y : a)  : LemOrdering := 
  if  ( isLess x  y) then  LemOrdering.LT  else 
  if  (x  ==  y) then  LemOrdering.EQ  else  LemOrdering.GT

class  OrdMaxMin (a : Type) where 
 
  max :  a →  a →  a

  min :  a →  a →  a

open  OrdMaxMin

/- removed value specification -/

def  minByLessEqual  {a : Type}  (le : a → a → Bool) (x : a) (y : a)  : a :=  if  (le  x  y) then  x  else  y
/- removed value specification -/

def  maxByLessEqual  {a : Type}  (le : a → a → Bool) (x : a) (y : a)  : a :=  if  (le  y  x) then  x  else  y
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/-  -/


/-  ==========================================================================  -/
/-  SetTypes                                                                    -/
/-  ==========================================================================  -/

/-  Set implementations use often an order on the elements. This allows the OCaml implementation
   to use trees for implementing them. At least, one needs to be able to check equality on sets.
   One could use the Ord type-class for sets. However, defining a special typeclass is cleaner
   and allows more flexibility. One can make e.g. sure, that this type-class is ignored for
   backends like HOL or Isabelle, which don't need it. Moreover, one is not forced to also instantiate
   the functions "<", "<=" ...  -/

class  SetType (a : Type) where 
 
  setElemCompare :  a →  a →  LemOrdering

open  SetType

/-  -/

/-  ==========================================================================  -/
/-  Instantiations                                                              -/
/-  ==========================================================================  -/

instance   : Eq Bool where

    isEqual   :=  (fun x y => x == y)

    isInequal   x  y  :=  not  ((fun x y => x == y)  x  y)


def  boolCompare  (b1 : Bool) (b2 : Bool)  : LemOrdering :=  match  (b1, b2) with  |  (true,  true) =>  LemOrdering.EQ |  (true,  false) =>  LemOrdering.GT |  (false,  true) =>  LemOrdering.LT |  (false,  false) =>  LemOrdering.EQ


instance   : SetType Bool where

    setElemCompare   :=  boolCompare

/- removed value specification -/

/- removed top-level value definition -/

instance   : Eq Char where
 
    isEqual   :=  (fun x y => x == y)

    isInequal   left  right  :=  not  (left  ==  right)

/- removed value specification -/

/- removed top-level value definition -/

instance   : Eq String where

    isEqual        :=  (fun x y => x == y)

    isInequal   l  r  :=  not  (l  ==  r)

/- removed value specification -/

def  pairEqual  {a : Type} {b : Type} [Eq a] [Eq b]  (p : (a ×b)) (p0 : (a ×b))  : Bool := match  (p,p0) with |  ( (a1,  b1),  (a2,  b2))  =>  (a1  ==  a2)  &&  (b1  ==  b2) 
/- removed value specification -/


instance (a b : Type) [Eq a] [Eq b] : Eq ((a  × b)) where

    isEqual   :=  pairEqual

    isInequal   x  y  :=  not  (pairEqual  x  y)

/- removed value specification -/

def  pairCompare  {a : Type} {b : Type}  (cmpa : a → a → LemOrdering) (cmpb : b → b → LemOrdering) (p : (a ×b)) (p0 : (a ×b))  : LemOrdering := match  (cmpa,cmpb,p,p0) with |  ( cmpa,  cmpb,  (a1,  b1),  (a2,  b2))  =>  match  cmpa  a1  a2 with  |  LemOrdering.LT =>  LemOrdering.LT |  LemOrdering.GT =>  LemOrdering.GT |  LemOrdering.EQ =>  cmpb  b1  b2    

def  pairLess  {a : Type} {b : Type} [Ord a] [Ord b]  (p : (b ×a)) (p0 : (b ×a))  : Bool := match  (p,p0) with |  ( (x1,  x2),  (y1,  y2))  =>  ( isLess x1  y1)  ||  (( isLessEqual x1  y1)  &&  ( isLess x2  y2)) 
def  pairLessEq  {a : Type} {b : Type} [Ord a] [Ord b]  (p : (b ×a)) (p0 : (b ×a))  : Bool := match  (p,p0) with |  ( (x1,  x2),  (y1,  y2))  =>  ( isLess x1  y1)  ||  (( isLessEqual x1  y1)  &&  ( isLessEqual x2  y2)) 

def  pairGreater  {a : Type} {b : Type} [Ord a] [Ord b]  (x12 : (a ×b)) (y12 : (a ×b))  : Bool :=  pairLess  y12  x12
def  pairGreaterEq  {a : Type} {b : Type} [Ord a] [Ord b]  (x12 : (a ×b)) (y12 : (a ×b))  : Bool :=  pairLessEq  y12  x12

instance (a b : Type) [Ord a] [Ord b] : Ord ((a  × b)) where

    compare   :=  pairCompare  compare  compare

    isLess    :=  pairLess

    isLessEqual   :=  pairLessEq

    isGreater    :=  pairGreater

    isGreaterEqual   :=  pairGreaterEq


instance (a b : Type) [SetType a] [SetType b] : SetType ((a  × b)) where

    setElemCompare   :=  pairCompare  setElemCompare  setElemCompare

/- removed value specification -/

def  tripleEqual  {a : Type} {b : Type} {c : Type} [Eq a] [Eq b] [Eq c]  (p : (a ×b ×c)) (p0 : (a ×b ×c))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3),  (y1,  y2,  y3))  =>  ( pairEqual (x1, (x2, x3))  (y1, (y2, y3))) 

instance (a b c : Type) [Eq a] [Eq b] [Eq c] : Eq ((a  × b  × c)) where

    isEqual   :=  tripleEqual

    isInequal   x  y  :=  not  (tripleEqual  x  y)

/- removed value specification -/

def  tripleCompare  {a : Type} {b : Type} {c : Type}  (cmpa : a → a → LemOrdering) (cmpb : b → b → LemOrdering) (cmpc : c → c → LemOrdering) (p : (a ×b ×c)) (p0 : (a ×b ×c))  : LemOrdering := match  (cmpa,cmpb,cmpc,p,p0) with |  ( cmpa,  cmpb,  cmpc,  (a1,  b1,  c1),  (a2,  b2,  c2))  =>  pairCompare  cmpa  (pairCompare  cmpb  cmpc)  (a1, (b1, c1))  (a2, (b2, c2)) 

def  tripleLess  {a : Type} {b : Type} {c : Type} [Ord a] [Ord b] [Ord c]  (p : (a ×b ×c)) (p0 : (a ×b ×c))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3),  (y1,  y2,  y3))  =>  pairLess  (x1, (x2, x3))  (y1, (y2, y3)) 
def  tripleLessEq  {a : Type} {b : Type} {c : Type} [Ord a] [Ord b] [Ord c]  (p : (a ×b ×c)) (p0 : (a ×b ×c))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3),  (y1,  y2,  y3))  =>  pairLessEq  (x1, (x2, x3))  (y1, (y2, y3)) 

def  tripleGreater  {a : Type} {b : Type} {c : Type} [Ord a] [Ord b] [Ord c]  (x123 : (c ×b ×a)) (y123 : (c ×b ×a))  : Bool :=  tripleLess  y123  x123
def  tripleGreaterEq  {a : Type} {b : Type} {c : Type} [Ord a] [Ord b] [Ord c]  (x123 : (c ×b ×a)) (y123 : (c ×b ×a))  : Bool :=  tripleLessEq  y123  x123

instance (a b c : Type) [Ord a] [Ord b] [Ord c] : Ord ((a  × b  × c)) where

    compare   :=  tripleCompare  compare  compare  compare

    isLess    :=  tripleLess

    isLessEqual   :=  tripleLessEq

    isGreater    :=  tripleGreater

    isGreaterEqual   :=  tripleGreaterEq


instance (a b c : Type) [SetType a] [SetType b] [SetType c] : SetType ((a  × b  × c)) where

    setElemCompare   :=  tripleCompare  setElemCompare  setElemCompare  setElemCompare

/- removed value specification -/

def  quadrupleEqual  {a : Type} {b : Type} {c : Type} {d : Type} [Eq a] [Eq b] [Eq c] [Eq d]  (p : (a ×b ×c ×d)) (p0 : (a ×b ×c ×d))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4),  (y1,  y2,  y3,  y4))  =>  ( pairEqual (x1, (x2, (x3, x4)))  (y1, (y2, (y3, y4)))) 

instance (a b c d : Type) [Eq a] [Eq b] [Eq c] [Eq d] : Eq ((a  × b  × c  × d)) where

    isEqual   :=  quadrupleEqual

    isInequal   x  y  :=  not  (quadrupleEqual  x  y)

/- removed value specification -/

def  quadrupleCompare  {a : Type} {b : Type} {c : Type} {d : Type}  (cmpa : a → a → LemOrdering) (cmpb : b → b → LemOrdering) (cmpc : c → c → LemOrdering) (cmpd : d → d → LemOrdering) (p : (a ×b ×c ×d)) (p0 : (a ×b ×c ×d))  : LemOrdering := match  (cmpa,cmpb,cmpc,cmpd,p,p0) with |  ( cmpa,  cmpb,  cmpc,  cmpd,  (a1,  b1,  c1,  d1),  (a2,  b2,  c2,  d2))  =>  pairCompare  cmpa  (pairCompare  cmpb  (pairCompare  cmpc  cmpd))  (a1, (b1, (c1, d1)))  (a2, (b2, (c2, d2))) 

def  quadrupleLess  {a : Type} {b : Type} {c : Type} {d : Type} [Ord a] [Ord b] [Ord c] [Ord d]  (p : (a ×b ×c ×d)) (p0 : (a ×b ×c ×d))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4),  (y1,  y2,  y3,  y4))  =>  pairLess  (x1, (x2, (x3, x4)))  (y1, (y2, (y3, y4))) 
def  quadrupleLessEq  {a : Type} {b : Type} {c : Type} {d : Type} [Ord a] [Ord b] [Ord c] [Ord d]  (p : (a ×b ×c ×d)) (p0 : (a ×b ×c ×d))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4),  (y1,  y2,  y3,  y4))  =>  pairLessEq  (x1, (x2, (x3, x4)))  (y1, (y2, (y3, y4))) 

def  quadrupleGreater  {a : Type} {b : Type} {c : Type} {d : Type} [Ord a] [Ord b] [Ord c] [Ord d]  (x1234 : (d ×c ×b ×a)) (y1234 : (d ×c ×b ×a))  : Bool :=  quadrupleLess  y1234  x1234
def  quadrupleGreaterEq  {a : Type} {b : Type} {c : Type} {d : Type} [Ord a] [Ord b] [Ord c] [Ord d]  (x1234 : (d ×c ×b ×a)) (y1234 : (d ×c ×b ×a))  : Bool :=  quadrupleLessEq  y1234  x1234

instance (a b c d : Type) [Ord a] [Ord b] [Ord c] [Ord d] : Ord ((a  × b  × c  × d)) where

    compare   :=  quadrupleCompare  compare  compare  compare  compare

    isLess    :=  quadrupleLess

    isLessEqual   :=  quadrupleLessEq

    isGreater    :=  quadrupleGreater

    isGreaterEqual   :=  quadrupleGreaterEq


instance (a b c d : Type) [SetType a] [SetType b] [SetType c] [SetType d] : SetType ((a  × b  × c  × d)) where

    setElemCompare   :=  quadrupleCompare  setElemCompare  setElemCompare  setElemCompare  setElemCompare

/- removed value specification -/

def  quintupleEqual  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} [Eq a] [Eq b] [Eq c] [Eq d] [Eq e]  (p : (a ×b ×c ×d ×e)) (p0 : (a ×b ×c ×d ×e))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4,  x5),  (y1,  y2,  y3,  y4,  y5))  =>  ( pairEqual (x1, (x2, (x3, (x4, x5))))  (y1, (y2, (y3, (y4, y5))))) 

instance (a b c d e : Type) [Eq a] [Eq b] [Eq c] [Eq d] [Eq e] : Eq ((a  × b  × c  × d  × e)) where

    isEqual   :=  quintupleEqual

    isInequal   x  y  :=  not  (quintupleEqual  x  y)

/- removed value specification -/

def  quintupleCompare  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type}  (cmpa : a → a → LemOrdering) (cmpb : b → b → LemOrdering) (cmpc : c → c → LemOrdering) (cmpd : d → d → LemOrdering) (cmpe : e → e → LemOrdering) (p : (a ×b ×c ×d ×e)) (p0 : (a ×b ×c ×d ×e))  : LemOrdering := match  (cmpa,cmpb,cmpc,cmpd,cmpe,p,p0) with |  ( cmpa,  cmpb,  cmpc,  cmpd,  cmpe,  (a1,  b1,  c1,  d1,  e1),  (a2,  b2,  c2,  d2,  e2))  =>  pairCompare  cmpa  (pairCompare  cmpb  (pairCompare  cmpc  (pairCompare  cmpd  cmpe)))  (a1, (b1, (c1, (d1, e1))))  (a2, (b2, (c2, (d2, e2)))) 

def  quintupleLess  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} [Ord a] [Ord b] [Ord c] [Ord d] [Ord e]  (p : (a ×b ×c ×d ×e)) (p0 : (a ×b ×c ×d ×e))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4,  x5),  (y1,  y2,  y3,  y4,  y5))  =>  pairLess  (x1, (x2, (x3, (x4, x5))))  (y1, (y2, (y3, (y4, y5)))) 
def  quintupleLessEq  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} [Ord a] [Ord b] [Ord c] [Ord d] [Ord e]  (p : (a ×b ×c ×d ×e)) (p0 : (a ×b ×c ×d ×e))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4,  x5),  (y1,  y2,  y3,  y4,  y5))  =>  pairLessEq  (x1, (x2, (x3, (x4, x5))))  (y1, (y2, (y3, (y4, y5)))) 

def  quintupleGreater  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} [Ord a] [Ord b] [Ord c] [Ord d] [Ord e]  (x12345 : (e ×d ×c ×b ×a)) (y12345 : (e ×d ×c ×b ×a))  : Bool :=  quintupleLess  y12345  x12345
def  quintupleGreaterEq  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} [Ord a] [Ord b] [Ord c] [Ord d] [Ord e]  (x12345 : (e ×d ×c ×b ×a)) (y12345 : (e ×d ×c ×b ×a))  : Bool :=  quintupleLessEq  y12345  x12345

instance (a b c d e : Type) [Ord a] [Ord b] [Ord c] [Ord d] [Ord e] : Ord ((a  × b  × c  × d  × e)) where

    compare   :=  quintupleCompare  compare  compare  compare  compare  compare

    isLess    :=  quintupleLess

    isLessEqual   :=  quintupleLessEq

    isGreater    :=  quintupleGreater

    isGreaterEqual   :=  quintupleGreaterEq


instance (a b c d e : Type) [SetType a] [SetType b] [SetType c] [SetType d] [SetType e] : SetType ((a  × b  × c  × d  × e)) where

    setElemCompare   :=  quintupleCompare  setElemCompare  setElemCompare  setElemCompare  setElemCompare  setElemCompare

/- removed value specification -/

def  sextupleEqual  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} {f : Type} [Eq a] [Eq b] [Eq c] [Eq d] [Eq e] [Eq f]  (p : (a ×b ×c ×d ×e ×f)) (p0 : (a ×b ×c ×d ×e ×f))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4,  x5,  x6),  (y1,  y2,  y3,  y4,  y5,  y6))  =>  ( pairEqual (x1, (x2, (x3, (x4, (x5, x6)))))  (y1, (y2, (y3, (y4, (y5, y6)))))) 

instance (a b c d e f : Type) [Eq a] [Eq b] [Eq c] [Eq d] [Eq e] [Eq f] : Eq ((a  × b  × c  × d  × e  × f)) where

    isEqual   :=  sextupleEqual

    isInequal   x  y  :=  not  (sextupleEqual  x  y)

/- removed value specification -/

def  sextupleCompare  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} {f : Type}  (cmpa : a → a → LemOrdering) (cmpb : b → b → LemOrdering) (cmpc : c → c → LemOrdering) (cmpd : d → d → LemOrdering) (cmpe : e → e → LemOrdering) (cmpf : f → f → LemOrdering) (p : (a ×b ×c ×d ×e ×f)) (p0 : (a ×b ×c ×d ×e ×f))  : LemOrdering := match  (cmpa,cmpb,cmpc,cmpd,cmpe,cmpf,p,p0) with |  ( cmpa,  cmpb,  cmpc,  cmpd,  cmpe,  cmpf,  (a1,  b1,  c1,  d1,  e1,  f1),  (a2,  b2,  c2,  d2,  e2,  f2))  =>  pairCompare  cmpa  (pairCompare  cmpb  (pairCompare  cmpc  (pairCompare  cmpd  (pairCompare  cmpe  cmpf))))  (a1, (b1, (c1, (d1, (e1, f1)))))  (a2, (b2, (c2, (d2, (e2, f2))))) 

def  sextupleLess  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} {f : Type} [Ord a] [Ord b] [Ord c] [Ord d] [Ord e] [Ord f]  (p : (a ×b ×c ×d ×e ×f)) (p0 : (a ×b ×c ×d ×e ×f))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4,  x5,  x6),  (y1,  y2,  y3,  y4,  y5,  y6))  =>  pairLess  (x1, (x2, (x3, (x4, (x5, x6)))))  (y1, (y2, (y3, (y4, (y5, y6))))) 
def  sextupleLessEq  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} {f : Type} [Ord a] [Ord b] [Ord c] [Ord d] [Ord e] [Ord f]  (p : (a ×b ×c ×d ×e ×f)) (p0 : (a ×b ×c ×d ×e ×f))  : Bool := match  (p,p0) with |  ( (x1,  x2,  x3,  x4,  x5,  x6),  (y1,  y2,  y3,  y4,  y5,  y6))  =>  pairLessEq  (x1, (x2, (x3, (x4, (x5, x6)))))  (y1, (y2, (y3, (y4, (y5, y6))))) 

def  sextupleGreater  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} {f : Type} [Ord a] [Ord b] [Ord c] [Ord d] [Ord e] [Ord f]  (x123456 : (f ×e ×d ×c ×b ×a)) (y123456 : (f ×e ×d ×c ×b ×a))  : Bool :=  sextupleLess  y123456  x123456
def  sextupleGreaterEq  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} {f : Type} [Ord a] [Ord b] [Ord c] [Ord d] [Ord e] [Ord f]  (x123456 : (f ×e ×d ×c ×b ×a)) (y123456 : (f ×e ×d ×c ×b ×a))  : Bool :=  sextupleLessEq  y123456  x123456

instance (a b c d e f : Type) [Ord a] [Ord b] [Ord c] [Ord d] [Ord e] [Ord f] : Ord ((a  × b  × c  × d  × e  × f)) where

    compare   :=  sextupleCompare  compare  compare  compare  compare  compare  compare

    isLess    :=  sextupleLess

    isLessEqual   :=  sextupleLessEq

    isGreater    :=  sextupleGreater

    isGreaterEqual   :=  sextupleGreaterEq


instance (a b c d e f : Type) [SetType a] [SetType b] [SetType c] [SetType d] [SetType e] [SetType f] : SetType ((a  × b  × c  × d  × e  × f)) where

    setElemCompare   :=  sextupleCompare  setElemCompare  setElemCompare  setElemCompare  setElemCompare  setElemCompare  setElemCompare

