/- Generated by Lem from either.lem. -/

import LemLib
import Either

open either


#eval do
  if ( ( eitherEqual ((Sum.inl  false) :  Sum  Bool  Bool)  (Sum.inl  false)) : Bool)
  then IO.println "PASS: either_equal_1"
  else throw (IO.userError "FAIL: either_equal_1")
#eval do
  if ( ( not  (eitherEqual  ((Sum.inl  true) :  Sum  Bool  Bool)  (Sum.inl  false))) : Bool)
  then IO.println "PASS: either_equal_2"
  else throw (IO.userError "FAIL: either_equal_2")
#eval do
  if ( (  eitherEqual ((Sum.inl  true) :  Sum  Bool  Bool)  (Sum.inl  true)) : Bool)
  then IO.println "PASS: either_equal_3"
  else throw (IO.userError "FAIL: either_equal_3")
#eval do
  if ( ( eitherEqual ((Sum.inr  false) :  Sum  Bool  Bool)  (Sum.inr  false)) : Bool)
  then IO.println "PASS: either_equal_4"
  else throw (IO.userError "FAIL: either_equal_4")
#eval do
  if ( ( not  (eitherEqual  ((Sum.inr  false) :  Sum  Bool  Bool)  (Sum.inr  true))) : Bool)
  then IO.println "PASS: either_equal_5"
  else throw (IO.userError "FAIL: either_equal_5")
#eval do
  if ( ( not  (eitherEqual  ((Sum.inr  true) :  Sum  Bool  Bool)  (Sum.inl  true))) : Bool)
  then IO.println "PASS: either_equal_6"
  else throw (IO.userError "FAIL: either_equal_6")
#eval do
  if ( ( not  (eitherEqual  ((Sum.inl  true) :  Sum  Bool  Bool)  (Sum.inr  true))) : Bool)
  then IO.println "PASS: either_equal_7"
  else throw (IO.userError "FAIL: either_equal_7")

#eval do
  if ( (match  (Sum.inl  true) with |  Sum.inl x =>  x |  Sum.inr y =>  not  y ) : Bool)
  then IO.println "PASS: either_pattern_1"
  else throw (IO.userError "FAIL: either_pattern_1")
#eval do
  if ( (match  (Sum.inr  false) with |  Sum.inl x =>  x |  Sum.inr y =>  not  y ) : Bool)
  then IO.println "PASS: either_pattern_2"
  else throw (IO.userError "FAIL: either_pattern_2")
#eval do
  if ( (not  (match  (Sum.inl  false) with |  Sum.inl x =>  x |  Sum.inr y =>  not  y )) : Bool)
  then IO.println "PASS: either_pattern_3"
  else throw (IO.userError "FAIL: either_pattern_3")
#eval do
  if ( (not  (match  (Sum.inr  true) with |  Sum.inl x =>  x |  Sum.inr y =>  not  y )) : Bool)
  then IO.println "PASS: either_pattern_4"
  else throw (IO.userError "FAIL: either_pattern_4")

#eval do
  if ( (((fun (x : Sum (Bool) (Bool)) =>  match x with  |  Sum.inl _ =>  true |  Sum.inr _ =>  false
)  ((Sum.inl  true) : Sum  Bool  Bool))) : Bool)
  then IO.println "PASS: isLeft_1"
  else throw (IO.userError "FAIL: isLeft_1")
#eval do
  if ( (not  (((fun (x : Sum (Bool) (Bool)) =>  match x with  |  Sum.inl _ =>  true |  Sum.inr _ =>  false
)  ((Sum.inr  true) : Sum  Bool  Bool)))) : Bool)
  then IO.println "PASS: isLeft_2"
  else throw (IO.userError "FAIL: isLeft_2")

#eval do
  if ( (((fun (x : Sum (Bool) (Bool)) =>  match x with  |  Sum.inr _ =>  true |  Sum.inl _ =>  false
)  ((Sum.inr  true) : Sum  Bool  Bool))) : Bool)
  then IO.println "PASS: isRight_1"
  else throw (IO.userError "FAIL: isRight_1")
#eval do
  if ( (not  (((fun (x : Sum (Bool) (Bool)) =>  match x with  |  Sum.inr _ =>  true |  Sum.inl _ =>  false
)  ((Sum.inl  true) : Sum  Bool  Bool)))) : Bool)
  then IO.println "PASS: isRight_2"
  else throw (IO.userError "FAIL: isRight_2")

#eval do
  if ( (either  (not)  (fun (b : Bool) =>  b)  (Sum.inl  true)  ==  false) : Bool)
  then IO.println "PASS: either_1"
  else throw (IO.userError "FAIL: either_1")
#eval do
  if ( (either  (not)  (fun (b : Bool) =>  b)  (Sum.inl  false)  ==  true) : Bool)
  then IO.println "PASS: either_2"
  else throw (IO.userError "FAIL: either_2")
#eval do
  if ( (either  (not)  (fun (b : Bool) =>  b)  (Sum.inr  true)  ==  true) : Bool)
  then IO.println "PASS: either_3"
  else throw (IO.userError "FAIL: either_3")
#eval do
  if ( (either  (not)  (fun (b : Bool) =>  b)  (Sum.inr  false)  ==  false) : Bool)
  then IO.println "PASS: either_4"
  else throw (IO.userError "FAIL: either_4")

#eval do
  if ( ( pairEqual (partitionEither  [Sum.inl  true, Sum.inr  false, Sum.inr  false,  Sum.inl  false, Sum.inr  true])  ([true,false], [false,false,true])) : Bool)
  then IO.println "PASS: partitionEither_1"
  else throw (IO.userError "FAIL: partitionEither_1")

#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (Prod.fst  (partitionEither  [Sum.inl  true, Sum.inr  false, Sum.inr  false,  Sum.inl  false, Sum.inr  true]))  [true,false])) : Bool)
  then IO.println "PASS: lefts_1"
  else throw (IO.userError "FAIL: lefts_1")


#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (Prod.snd  (partitionEither  [Sum.inl  true, Sum.inr  false, Sum.inr  false,  Sum.inl  false, Sum.inr  true]))  [false,false,true])) : Bool)
  then IO.println "PASS: rights_1"
  else throw (IO.userError "FAIL: rights_1")


