/- Generated by Lem from either.lem. -/

import LemLib

 

import Bool
open Bool
import Basic_classes
open Basic_classes
import List
open List
import Tuple
open Tuple



/- 

inductive  either (a : Type) (b : Type) where
  
  |  Left :   a →  either a b
  
  |  Right :  b →  either a b
  deriving BEq
open either
instance {a : Type} [Inhabited a] {b : Type} [Inhabited b] : Inhabited (either a b) where
  default := Left default -/
/- removed value specification -/

/- removed value specification -/


def  eitherEqualBy  {a : Type} {b : Type}  (eql : a → a → Bool) (eqr : b → b → Bool)  (left : Sum  a  b)  (right : Sum  a  b)  : Bool := 
  match  (left, right) with  |  (Sum.inl l,  Sum.inl l') =>  eql  l  l' |  (Sum.inr r,  Sum.inr r') =>  eqr  r  r' |  _ =>  false
  
def  eitherEqual  {a : Type} {b : Type} [Eq a] [Eq b]   : Sum a b → Sum a b → Bool :=  eitherEqualBy  (fun x y => x == y)  (fun x y => x == y)

instance (a b : Type) [Eq a] [Eq b] : Eq (Sum  a  b) where

    isEqual   :=  eitherEqual

    isInequal   x  y  :=  not  (eitherEqual  x  y)
 

def  either_setElemCompare  {a : Type} {b : Type} {c : Type} {d : Type}  (cmpa : d → b → LemOrdering) (cmpb : c → a → LemOrdering) (x : Sum d c) (y : Sum b a)  : LemOrdering := 
  match  (x, y) with  |  (Sum.inl x',  Sum.inl y') =>  cmpa  x'  y' |  (Sum.inr x',  Sum.inr y') =>  cmpb  x'  y' |  (Sum.inl _,  Sum.inr _) =>  LemOrdering.LT |  (Sum.inr _,  Sum.inl _) =>  LemOrdering.GT
  

instance (a b : Type) [SetType a] [SetType b] : SetType (Sum  a  b) where

    setElemCompare   x  y  :=  either_setElemCompare  setElemCompare  setElemCompare  x  y

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

def  either  {a : Type} {b : Type} {c : Type}  (fa : a → c) (fb : b → c) (x : Sum a b)  : c :=  match  x with  |  Sum.inl a1 =>  fa  a1 |  Sum.inr b1 =>  fb  b1

/- removed value specification -/

 partial def  partitionEither  {a : Type} {b : Type}  (l : List (Sum a b))  : (List a ×List b) :=  match  l with  |  [] =>  ([], []) |  x  ::  xs =>  /- begin block -/       match  partitionEither  xs with |   (ll,  rl) =>        match  x with  |  Sum.inl l =>  ((l :: ll), rl) |  Sum.inr r =>  (ll, (r :: rl))             /- end block -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/


