/- Generated by Lem from function_extra.lem. -/

import LemLib
import Function_extra



/-  -----------------------  -/
/-  Tests for function       -/
/-  -----------------------  -/

/-  These tests are not written in function itself, because the nat type
   is not available there, yet  -/

#eval do
  if ( (  2 :Nat)  ==   2 : Bool)
  then IO.println "PASS: id_0"
  else throw (IO.userError "FAIL: id_0")
#eval do
  if ( (  5 :Nat)  ==   5 : Bool)
  then IO.println "PASS: id_1"
  else throw (IO.userError "FAIL: id_1")
#eval do
  if ( (  2 :Nat)  ==   2 : Bool)
  then IO.println "PASS: id_2"
  else throw (IO.userError "FAIL: id_2")

#eval do
  if ( (Function.const  (  2 :Nat))  true  ==   2 : Bool)
  then IO.println "PASS: const_0"
  else throw (IO.userError "FAIL: const_0")
#eval do
  if ( (Function.const  (  5 :Nat))  false  ==   5 : Bool)
  then IO.println "PASS: const_1"
  else throw (IO.userError "FAIL: const_1")
#eval do
  if ( (Function.const  (  2 :Nat))  (  3 :Nat)  ==   2 : Bool)
  then IO.println "PASS: const_2"
  else throw (IO.userError "FAIL: const_2")

#eval do
  if ( (Function.comp  (fun  (x :Nat) =>   3  *  x)  Nat.succ (  2)  ==   9) : Bool)
  then IO.println "PASS: comb_0"
  else throw (IO.userError "FAIL: comb_0")
#eval do
  if ( (Function.comp  Nat.succ  (fun  (x :Nat) =>   3  *  x) (  2)  ==   7) : Bool)
  then IO.println "PASS: comb_1"
  else throw (IO.userError "FAIL: comb_1")

#eval do
  if ( apply  (fun  (x :Nat) =>   3  *  x) (  2)  ==   6 : Bool)
  then IO.println "PASS: apply_0"
  else throw (IO.userError "FAIL: apply_0")
#eval do
  if (  apply (fun  (x :Nat) =>   3  *  x) (  2)  ==   6 : Bool)
  then IO.println "PASS: apply_1"
  else throw (IO.userError "FAIL: apply_1")

#eval do
  if ( flip  (fun  (x :Nat) (y : Nat) =>  x  -  y) (  3) (  5)  ==   2 : Bool)
  then IO.println "PASS: flip_0"
  else throw (IO.userError "FAIL: flip_0")
#eval do
  if ( flip  (fun  (x :Nat) (y : Nat) =>  x  -  y) (  5) (  3)  ==   0 : Bool)
  then IO.println "PASS: flip_1"
  else throw (IO.userError "FAIL: flip_1")

