(* Generated by Lem from debug.lem. *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import String.
Require Import Program.Wf.

Require Import coqharness.

Open Scope nat_scope.
Open Scope string_scope.


(* [?]: removed value specification. *)

Definition print_string  (str : string )  : unit :=  tt.
(* [?]: removed value specification. *)

Definition print_endline  (str : string )  : unit :=  tt.
