/- Generated by Lem from list_extra.lem. -/

import LemLib



import Bool
open Bool
import Maybe
open Maybe
import Basic_classes
open Basic_classes
import Tuple
open Tuple
import Num
open Num
import List
open List
import Assert_extra
open Assert_extra

/- removed value specification -/

def  head  {a : Type}  (l : List a)  : a :=  match  l with  |  x :: xs =>  x |  [] =>  failwith  "List_extra.head of empty list" 
/- removed value specification -/

def  tail  {a : Type}  (l : List a)  : List a :=  match  l with  |  x :: xs =>  xs |  [] =>  failwith  "List_extra.tail of empty list" 
/- removed value specification -/

 partial def  last  {a : Type}  (l : List a)  : a :=  match  l with  |  [x] =>  x |  x1 :: x2 :: xs =>  last  (x2  ::  xs) |  [] =>  failwith  "List_extra.last of empty list" 
/- removed value specification -/

 partial def  init  {a : Type}  (l : List a)  : List a :=  match  l with  |  [x] =>  [] |  x1 :: x2 :: xs =>  x1 :: (init  (x2 :: xs)) |  [] =>  failwith  "List_extra.init of empty list" 
/- removed value specification -/

def  foldl1  {a : Type}  (f : a → a → a) (x_xs : List a)  : a :=  match  x_xs with  | ( x  ::  xs) =>  List.foldl  f  x  xs |  [] =>  failwith  "List_extra.foldl1 of empty list" 
/- removed value specification -/

def  foldr1  {a : Type}  (f : a → a → a) (x_xs : List a)  : a :=  match  x_xs with  | ( x  ::  xs) =>  List.foldr  f  x  xs |  [] =>  failwith  "List_extra.foldr1 of empty list" 
/- removed value specification -/

/- 
def  nth  {a : Type}  (l : List a) (n : Nat)  : a :=  match  List.get?  l  n with |  some e =>  e |  none =>  failwith  "List_extra.nth"  -/
/- removed value specification -/
 
def  findNonPure  {a : Type}  (P : a → Bool) (l : List a)  : a :=  match  (find  P  l) with  |  some e =>  e |  none =>  failwith  "List_extra.findNonPure"

/- removed value specification -/
 
 partial def  zipSameLength  {a : Type} {b : Type}  (l1 : List a) (l2 : List b)  : List ((a ×b)) :=  match  (l1, l2) with  |  (x  ::  xs,  y  ::  ys) =>  (x, y)  ::  zipSameLength  xs  ys |  ([],  []) =>  [] |  _ =>  failwith  "List_extra.zipSameLength of different length lists"


/- removed value specification -/

 partial def  unfoldr  {a : Type} {b : Type}  (f : a → Option ((b ×a))) (x : a)  : List b := 
  match  f  x with  |  some (y,  x') =>          y  ::  unfoldr  f  x' |  none =>          []
  

