/- Generated by Lem from list_extra.lem. -/

import LemLib
import List_extra



#eval do
  if ( (head  [  3,  1]  ==  (  3 :Nat)) : Bool)
  then IO.println "PASS: head_simple_1"
  else throw (IO.userError "FAIL: head_simple_1")
#eval do
  if ( (head  [  5,  4]  ==  (  5 :Nat)) : Bool)
  then IO.println "PASS: head_simple_2"
  else throw (IO.userError "FAIL: head_simple_2")

#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (tail  [(  3 :Nat),  1])  [  1])) : Bool)
  then IO.println "PASS: tail_simple_1"
  else throw (IO.userError "FAIL: tail_simple_1")
#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (tail  [(  5 :Nat)])  [])) : Bool)
  then IO.println "PASS: tail_simple_2"
  else throw (IO.userError "FAIL: tail_simple_2")
#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (tail  [(  5 :Nat),  4,  3,  2])  [  4,  3,  2])) : Bool)
  then IO.println "PASS: tail_simple_3"
  else throw (IO.userError "FAIL: tail_simple_3")

theorem  head_tail_cons : ( (∀  l, ( ((not  (natGtb  (List.length  l) (  0)))  ||  ( (listEqualBy  (fun x y => x == y) l  ((head  l) :: (tail  l))))) : Prop)) : Prop) := by decide


#eval do
  if ( (last  [(  3 :Nat),  1]  ==   1) : Bool)
  then IO.println "PASS: last_simple_1"
  else throw (IO.userError "FAIL: last_simple_1")
#eval do
  if ( (last  [(  5 :Nat),  4]  ==   4) : Bool)
  then IO.println "PASS: last_simple_2"
  else throw (IO.userError "FAIL: last_simple_2")

#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (init  [(  3 :Nat),  1])  [  3])) : Bool)
  then IO.println "PASS: init_simple_1"
  else throw (IO.userError "FAIL: init_simple_1")
#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (init  [(  5 :Nat)])  [])) : Bool)
  then IO.println "PASS: init_simple_2"
  else throw (IO.userError "FAIL: init_simple_2")
#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (init  [(  5 :Nat),  4,  3,  2])  [  5,  4,  3])) : Bool)
  then IO.println "PASS: init_simple_3"
  else throw (IO.userError "FAIL: init_simple_3")

theorem  init_last_append : ( (∀  l, ( ((not  (natGtb  (List.length  l) (  0)))  ||  ( (listEqualBy  (fun x y => x == y) l  ((init  l)  ++  [last  l])))) : Prop)) : Prop) := by decide
theorem  init_last_dest : ( (∀  l, ( ((not  (natGtb  (List.length  l) (  0)))  ||  ( (maybeEqualBy  pairEqual (dest_init  l)  (some  (init  l, last  l))))) : Prop)) : Prop) := by decide
theorem nth_def_lemma : ((∀ n l, ( match  List.get?  l  n with |  some e =>  e |  none =>  failwith  "List_extra.nth"  ==  List.get!  l  n : Prop)) : Prop) := by decide

#eval do
  if ( (List.get!  [  0,  1,  2,  3,  4,  5] (  0)  ==  (  0 :Nat)) : Bool)
  then IO.println "PASS: nth_0"
  else throw (IO.userError "FAIL: nth_0")
#eval do
  if ( (List.get!  [  0,  1,  2,  3,  4,  5] (  1)  ==  (  1 :Nat)) : Bool)
  then IO.println "PASS: nth_1"
  else throw (IO.userError "FAIL: nth_1")
#eval do
  if ( (List.get!  [  0,  1,  2,  3,  4,  5] (  2)  ==  (  2 :Nat)) : Bool)
  then IO.println "PASS: nth_2"
  else throw (IO.userError "FAIL: nth_2")
#eval do
  if ( (List.get!  [  0,  1,  2,  3,  4,  5] (  3)  ==  (  3 :Nat)) : Bool)
  then IO.println "PASS: nth_3"
  else throw (IO.userError "FAIL: nth_3")
#eval do
  if ( (List.get!  [  0,  1,  2,  3,  4,  5] (  4)  ==  (  4 :Nat)) : Bool)
  then IO.println "PASS: nth_4"
  else throw (IO.userError "FAIL: nth_4")
#eval do
  if ( (List.get!  [  0,  1,  2,  3,  4,  5] (  5)  ==  (  5 :Nat)) : Bool)
  then IO.println "PASS: nth_5"
  else throw (IO.userError "FAIL: nth_5")

theorem  nth_index : ( (∀  l  n  e, ( ((not  (natLtb  n  (List.length  l)))  ||  (maybeEqualBy  (fun x y => x == y)  (List.get?  l  n)  (some  (List.get!  l  n)))) : Prop)) : Prop) := by decide 

#eval do
  if ( ( (listEqualBy  pairEqual (zipSameLength  [(  1 :Nat),  2,  3,  4,  5]  [(  2 :Nat),  3,  4,  5,  6])  [(  1,  2),(  2,  3),(  3,  4),(  4,  5),(  5,  6)])) : Bool)
  then IO.println "PASS: zipSameLength_1"
  else throw (IO.userError "FAIL: zipSameLength_1")

