/- Generated by Lem from list.lem. -/

import LemLib

 

import Bool
open Bool
import Maybe
open Maybe
import Basic_classes
open Basic_classes
import Function
open Function
import Tuple
open Tuple
import Num
open Num





/- removed value specification -/

/- removed value specification -/

/- 
def  null  {a : Type}  (l : List a)  : Bool :=  match  l with |  [] =>  true |  _ =>  false  -/
/- removed value specification -/

/- 
 partial def  length  {a : Type}  (l : List a)  : Nat := 
  match  l with  |  [] =>  0 |  x  ::  xs =>  (fun x y => x Instance_Num_NumAdd_nat.+ y)  (List.length  xs)  1
   -/
/- removed value specification -/

/- removed value specification -/

/- 

 partial def  listEqualBy  {a : Type}  (eq : a → a → Bool) (l1 : List a) (l2 : List a)  : Bool :=  match  (l1,l2) with  |  ([],  []) =>  true |  ([], ( _ :: _)) =>  false |  ((_ :: _),  []) =>  false |  (x :: xs,  y  ::  ys) =>  (eq  x  y  &&  listEqualBy  eq  xs  ys)
 -/
/- removed top-level value definition -/

instance (a : Type) [Eq a] : Eq (List  a) where

    isEqual   :=  (listEqualBy  (fun x y => x == y))

    isInequal   l1  l2  :=  not  ((listEqualBy  (fun x y => x == y)  l1  l2))

/- removed value specification -/

/- removed value specification -/


 partial def  lexicographicCompareBy  {a : Type}  (cmp : a → a → LemOrdering) (l1 : List a) (l2 : List a)  : LemOrdering :=  match  (l1,l2) with  |  ([],  []) =>  LemOrdering.EQ |  ([],  _ :: _) =>  LemOrdering.LT |  (_ :: _,  []) =>  LemOrdering.GT |  (x :: xs,  y :: ys) =>  /- begin block -/       match  cmp  x  y with  |  LemOrdering.LT =>  LemOrdering.LT |  LemOrdering.GT =>  LemOrdering.GT |  LemOrdering.EQ =>  lexicographicCompareBy  cmp  xs  ys            /- end block -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

 partial def  lexicographicLessBy  {a : Type}  (less : a → a → Bool) (less_eq : a → a → Bool) (l1 : List a) (l2 : List a)  : Bool :=  match  (l1,l2) with  |  ([],  []) =>  false |  ([],  _ :: _) =>  true |  (_ :: _,  []) =>  false |  (x :: xs,  y :: ys) =>  ((less  x  y)  ||  ((less_eq  x  y)  &&  (lexicographicLessBy  less  less_eq  xs  ys)))

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

 partial def  lexicographicLessEqBy  {a : Type}  (less : a → a → Bool) (less_eq : a → a → Bool) (l1 : List a) (l2 : List a)  : Bool :=  match  (l1,l2) with  |  ([],  []) =>  true |  ([],  _ :: _) =>  true |  (_ :: _,  []) =>  false |  (x :: xs,  y :: ys) =>  (less  x  y  ||  (less_eq  x  y  &&  lexicographicLessEqBy  less  less_eq  xs  ys))

/- removed top-level value definition -/


instance (a : Type) [Ord a] : Ord (List  a) where

    compare   :=  (lexicographicCompareBy  compare)

    isLess   :=  (lexicographicLessBy  isLess  isLessEqual)

    isLessEqual   :=  (lexicographicLessEqBy  isLess  isLessEqual)

    isGreater   x  y  :=  (lexicographicLessBy  isLess  isLessEqual  y  x)

    isGreaterEqual   x  y  :=  (lexicographicLessEqBy  isLess  isLessEqual  y  x)

/- removed value specification -/

/-  /-  originally append  -/
 partial def  append  {a : Type}  (xs : List a) (ys : List a)  : List a :=  match  xs with  |  [] =>  ys |  x  ::  xs' =>  x  ::  (xs'  ++  ys)
                    -/
/- removed value specification -/

def  snoc  {a : Type}  (e : a) (l : List a)  : List a :=  l  ++  [e]
/- removed value specification -/

/-  /-  originally named rev_append  -/
 partial def  reverseAppend  {a : Type}  (l1 : List a) (l2 : List a)  : List a :=  match  l1 with  |  [] =>  l2 |  x  ::  xs =>  List.reverseAux  xs  (x  ::  l2)
                                -/
/- removed value specification -/

/-  /-  originally named rev  -/
def  reverse  {a : Type}  (l : List a)  : List a :=  List.reverseAux  l  [] -/
/- removed value specification -/

 partial def  map_tr  {a : Type} {b : Type}  (rev_acc : List b) (f : a → b) (l : List a)  : List b :=  match  l with  |  [] =>  List.reverse  rev_acc |  x  ::  xs =>  map_tr  ((f  x)  ::  rev_acc)  f  xs

/- removed value specification -/

 partial def  count_map  {a : Type} {b : Type}  (f : a → b) (l : List a) (ctr : Nat)  : List b :=   
  match  l with  |  [] =>  [] |  hd  ::  tl =>  f  hd  ::       (if  natLtb  ctr (  5000) then  count_map  f  tl  (ctr  +   1)       else  map_tr  []  f  tl)
  
/- removed value specification -/

/- 
def  map  {a : Type} {b : Type}  (f : a → b) (l : List a)  : List b :=  count_map  f  l  0 -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/-  /-  originally foldl  -/

 partial def  foldl  {a : Type} {b : Type}  (f : a → b → a) (b : a) (l : List b)  : a :=  match  l with  |  [] =>  b |  x  ::  xs =>  List.foldl  f  (f  b  x)  xs
 -/
/- removed value specification -/

/-  /-  originally foldr with different argument order  -/
 partial def  foldr  {a : Type} {b : Type}  (f : a → b → b) (b : b) (l : List a)  : b :=  match  l with  |  [] =>  b |  x  ::  xs =>  f  x  (List.foldr  f  b  xs)
 -/
/- removed value specification -/

/-  /-  before also called "flatten"  -/
def  concat  {a : Type}   : List (List a) → List a :=  List.foldr  (fun x y => x ++ y)  [] -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/-  /-  originally for_all  -/
def  all  {a : Type}  (P : a → Bool) (l : List a)  : Bool :=  List.foldl  (fun (r : Bool) (e : a) =>  P  e  &&  r)  true  l -/
/- removed value specification -/

/-  /-  originally exist  -/
def  any  {a : Type}  (P : a → Bool) (l : List a)  : Bool :=  List.foldl  (fun (r : Bool) (e : a) =>  P  e  ||  r)  false  l -/
/- removed value specification -/
 

 partial def  dest_init_aux  {a : Type}  (rev_init : List a) (last_elem_seen : a) (to_process : List a)  : (List a ×a) := 
  match  to_process with  |  [] =>  (List.reverse  rev_init, last_elem_seen) |  x :: xs =>  dest_init_aux  (last_elem_seen :: rev_init)  x  xs
  

def  dest_init  {a : Type}  (l : List a)  : Option ((List a ×a)) :=  match  l with  |  [] =>  none |  x :: xs =>  some  (dest_init_aux  []  x  xs)

/- removed value specification -/

/- 

 partial def  index  {a : Type}  (l : List a) (n : Nat)  : Option a :=  match  l with  |  [] =>  none |  x  ::  xs =>  if  (fun x y => x Instance_Basic_classes_Eq_nat.= y)  n  0 then  some  x  else  List.get?  xs  ((fun x y => x Instance_Num_NumMinus_nat.- y) n 1)
 -/
/- removed value specification -/


 partial def  findIndices_aux  {a : Type}   (i :Nat) (P : a → Bool) (l : List a)  : List (Nat) := 
  match  l with  |  [] =>  [] |  x  ::  xs =>  if  P  x then  i  ::  findIndices_aux  (i  +   1)  P  xs  else  findIndices_aux  (i  +   1)  P  xs
 
def  findIndices  {a : Type}  (P : a → Bool) (l : List a)  : List (Nat) :=  findIndices_aux (  0)  P  l
/- removed value specification -/

def  findIndex  {a : Type}  (P : a → Bool) (l : List a)  : Option (Nat) :=  match  findIndices  P  l with  |  [] =>  none |  x  ::  _ =>  some  x

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/



 partial def  genlist  {a : Type}  (f : Nat → a)  (n  : Nat)  : List a := 
  match  (n :  Nat) with  |  (0 : Nat) =>  [] |  (n' + 1) =>  snoc  (f  n')  (genlist  f  n')
  
/- removed value specification -/

/- 
 partial def  replicate  {a : Type}  (n : Nat) (x : a)  : List a := 
  match  n with  |  0 =>  [] |  (n' + 1) =>  x  ::  List.replicate  n'  x
   -/
/- removed value specification -/

 partial def  splitAtAcc  {a : Type}  (revAcc : List a) (n : Nat) (l : List a)  : (List a ×List a) :=  
  match  l with  |  [] =>  (List.reverse  revAcc, []) |  x :: xs =>  if  natLteb  n (  0) then  (List.reverse  revAcc, l)  else  splitAtAcc  (x :: revAcc)  (n -   1)  xs
  
/- removed value specification -/

def  splitAt  {a : Type}  (n : Nat) (l : List a)  : (List a ×List a) :=  
   splitAtAcc  []  n  l
/- removed value specification -/

/- 
def  take  {a : Type}  (n : Nat) (l : List a)  : List a :=  Prod.fst  (splitAt  n  l) -/
/- removed value specification -/

/- 
def  drop  {a : Type}  (n : Nat) (l : List a)  : List a :=  Prod.snd  (splitAt  n  l) -/
/- removed value specification -/

 partial def  splitWhile_tr  {a : Type}  (p : a → Bool) (xs : List a) (acc : List a)  : (List a ×List a) :=  match  xs with  |  [] =>      (List.reverse  acc, []) |  x :: xs =>      if  p  x then        splitWhile_tr  p  xs  (x :: acc)      else        (List.reverse  acc, (x :: xs))

/- removed value specification -/

def  splitWhile  {a : Type}  (p : a → Bool) (xs : List a)  : (List a ×List a) :=  splitWhile_tr  p  xs  []
/- removed value specification -/

def  takeWhile  {a : Type}  (p : a → Bool) (l : List a)  : List a :=  Prod.fst  (splitWhile  p  l)
/- removed value specification -/

def  dropWhile  {a : Type}  (p : a → Bool) (l : List a)  : List a :=  Prod.snd  (splitWhile  p  l)
/- removed value specification -/

 partial def  isPrefixOf  {a : Type} [Eq a]  (l1 : List a) (l2 : List a)  : Bool :=  match  (l1, l2) with  |  ([],  _) =>  true |  (_ :: _,  []) =>  false |  (x :: xs,  y :: ys) =>  (x  ==  y)  &&  isPrefixOf  xs  ys

/- removed value specification -/

 partial def  update  {a : Type}  (l : List a) (n : Nat) (e : a)  : List a :=  
  match  l with  |  [] =>  [] |  x  ::  xs =>  if  n  ==   0 then  e  ::  xs  else  x  ::  (update  xs  (n  -   1)  e)

/- removed value specification -/

/- removed value specification -/

/- 

def  elemBy  {a : Type}  (eq : a → a → Bool) (e : a) (l : List a)  : Bool :=  List.any  l  (eq  e) -/
def  elem  {a : Type} [Eq a]   : a → List a → Bool :=  listMemberBy  (fun x y => x == y)
/- removed value specification -/
 /-  previously not of maybe type  -/
 partial def  find  {a : Type}  (P : a → Bool) (l : List a)  : Option a :=  match  l with  |  [] =>  none |  x  ::  xs =>  if  P  x then  some  x  else  find  P  xs

/- removed value specification -/

/- removed value specification -/


/-  DPM: eta-expansion for Coq backend type-inference.  -/
def  lookupBy  {a : Type} {b : Type}  (eq : a → a → Bool) (k : a) (m : List ((a ×b)))  : Option b :=  Option.map  (fun (x : (a ×b)) =>  Prod.snd  x)  (find  (fun (p : (a ×b)) =>  match  (p)  with |   ( (k',  _))  =>  eq  k  k' )  m)
/- removed top-level value definition -/
/- removed value specification -/

/- 
 partial def  filter  {a : Type}  (P : a → Bool) (l : List a)  : List a :=  match  l with  |  [] =>  [] |  x  ::  xs =>  if  (P  x) then  x  ::  (List.filter  P  xs)  else  List.filter  P  xs
                      -/
/- removed value specification -/

def  partition  {a : Type}  (P : a → Bool) (l : List a)  : (List a ×List a) :=  (List.filter  P  l, List.filter  (fun (x : a) =>  not  (P  x))  l)
/- removed value specification -/

def  reversePartition  {a : Type}  (P : a → Bool) (l : List a)  : (List a ×List a) :=  partition  P  (List.reverse  l)
/- removed value specification -/
 
 partial def  deleteFirst  {a : Type}  (P : a → Bool) (l : List a)  : Option (List a) :=  match  l with  |  [] =>  none |  x  ::  xs =>  if  (P  x) then  some  xs  else  Option.map  (fun (xs' : List a) =>  x  ::  xs')  (deleteFirst  P  xs)
                          
/- removed value specification -/

/- removed value specification -/


def  deleteBy  {a : Type}  (eq : a → a → Bool) (x : a) (l : List a)  : List a :=  fromMaybe  l  (deleteFirst  (eq  x)  l)
/- removed top-level value definition -/
/- removed value specification -/

/-  /-  before combine  -/
 partial def  zip  {a : Type} {b : Type}  (l1 : List a) (l2 : List b)  : List ((a ×b)) :=  match  (l1, l2) with  |  (x  ::  xs,  y  ::  ys) =>  (x, y)  ::  List.zip  xs  ys |  _ =>  []
 -/
/- removed value specification -/

/- 
 partial def  unzip  {a : Type} {b : Type}  (l : List ((a ×b)))  : (List a ×List b) :=  match  l with  |  [] =>  ([], []) |  (x,  y)  ::  xys =>  let  (xs,  ys)   := List.unzip  xys 
 (x  ::  xs, y  ::  ys)
 -/


instance (a : Type) [SetType a] : SetType (List  a) where

   setElemCompare   :=  lexicographicCompareBy  setElemCompare

/- removed value specification -/

 partial def  allDistinct  {a : Type} [Eq a]  (l : List a)  : Bool :=  
  match  l with  |  [] =>  true | ( x :: l') =>  not  (elem  x  l')  &&  allDistinct  l'
  
/- removed value specification -/

 partial def  mapMaybe  {a : Type} {b : Type}  (f : a → Option b) (xs : List a)  : List b := 
  match  xs with  |  [] =>  [] |  x :: xs =>        match  f  x with  |  none =>  mapMaybe  f  xs |  some y =>  y  ::  (mapMaybe  f  xs)       
  
/- removed value specification -/

 partial def  mapiAux  {a : Type} {b : Type}  (f : Nat → b → a)  (n  : Nat) (l : List b)  : List a :=  match  l with  |  [] =>  [] |  x  ::  xs =>  (f  n  x)  ::  mapiAux  f  (n  +   1)  xs

def  mapi  {a : Type} {b : Type}  (f : Nat → a → b) (l : List a)  : List b :=  mapiAux  f (  0)  l
/- removed value specification -/

def  deletes  {a : Type} [Eq a]  (xs : List a) (ys : List a)  : List a := 
  List.foldl  (flip  (deleteBy  (fun x y => x == y)))  xs  ys
/- removed value specification -/

 partial def  catMaybes  {a : Type}  (xs : List (Option a))  : List a := 
  match  xs with  |  [] =>          [] | ( none  ::  xs') =>          catMaybes  xs' | ( some x  ::  xs') =>          x  ::  catMaybes  xs'
  
