/- Generated by Lem from map.lem. -/

import LemLib



import Bool
open Bool
import Basic_classes
open Basic_classes
import Function
open Function
import Maybe
open Maybe
import List
open List
import Tuple
open Tuple
import Set
open Set
import Num
open Num


/- 

inductive  map (k : Type) (v : Type) where
open map
instance {k : Type} [Inhabited k] {v : Type} [Inhabited v] : Inhabited (map k v) where
  default := sorry /- DAEMON -/ -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance (k v : Type) [Eq k] [Eq v] : Eq (Fmap  k  v) where

    isEqual   :=  (fmapEqualBy  (fun x y => x == y)  (fun x y => x == y))

    isInequal   m1  m2  :=  not  ((fmapEqualBy  (fun x y => x == y)  (fun x y => x == y)  m1  m2))



/-  --------------------------------------------------------------------------  -/
/-  Map type class                                                              -/
/-  --------------------------------------------------------------------------  -/

class  MapKeyType (a : Type) where 

  mapKeyCompare :  a →  a →  LemOrdering

open  MapKeyType

/-  -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

def  fromList  {k : Type} {v : Type} [MapKeyType k]  (l : List ((k ×v)))  : Fmap k v :=  List.foldl  (fun (m : Fmap k v) (p : (k ×v)) =>  match  (m ,p)  with |   ( m ,  (k1, v1))  =>  fmapAdd  k1  v1  m )  fmapEmpty  l
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/-  

def  all  {k : Type} {v : Type} [MapKeyType k] [Eq v]  (P : k → v → Bool) (m : Fmap k v)  : Bool :=  (∀  k  v, ( (P  k  v  &&  (Instance_Basic_classes_Eq_Maybe_maybe.=  lookup  k  m  some  v)) : Prop)) -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/

/-  instance of SetType  -/
def  map_setElemCompare  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} [SetType a] [SetType b] [SetType c] [SetType d] [MapKeyType b] [MapKeyType d]  (cmp : List ((d ×c)) → List ((b ×a)) → e) (x : Fmap d c) (y : Fmap b a)  : e := 
  cmp  (id  x)  (id  y)

instance (a b : Type) [SetType a] [SetType b] [MapKeyType a] : SetType (Fmap  a  b) where

    setElemCompare   x  y  :=  map_setElemCompare  (setCompareBy  (pairCompare  setElemCompare  setElemCompare))  x  y

