/- Generated by Lem from num.lem. -/

import LemLib
import Num

open NumNegate
open NumAbs
open NumAdd
open NumMinus
open NumMult
open NumPow
open NumDivision
open NumIntegerDivision
open NumRemainder
open NumSucc
open NumPred
open float32
open float64
open real
open rational
open int64
open int32
open integer
open int
open natural

theorem natSucc_def_lemma : ((∀ n, ( (n  +   1) ==  Nat.succ  n : Prop)) : Prop) := by decide
theorem gen_pow_aux_def_lemma : ((∀ mul e a b, (
   match  e with  |  0 =>  a |  1 =>  mul  a  b | (  (e' + 2)) =>  let  e''  := e  /   2 
                    let  a'   := (if  (e  %   2)  ==   0 then  a  else  mul  a  b) 
                    gen_pow_aux  mul  a'  (mul  b  b)  e''
    ==  gen_pow_aux  (mul :  a →  a →  a)  (a :  a)  (b :  a)  (e :  Nat) : Prop)) : Prop) := by decide
theorem naturalSucc_def_lemma : ((∀ n, ( (n  +   1) ==  Nat.succ  n : Prop)) : Prop) := by decide
theorem rationalPowInteger_def_lemma : ((∀ e b, (
  (if  e  == ( 0 :  Int) then ( 1 :  Int)  else 
  if  intGtb  e (( 0 :  Int)) then  b  ^  (e  - ( 1 :  Int))  *  b  else 
  b  ^  (e  + ( 1 :  Int))  /  b) ==  b  ^  e : Prop)) : Prop) := by decide
theorem rationalPowNat_def_lemma : ((∀ e r, ( r  ^  (Int.ofNat  e) ==  r  ^  e : Prop)) : Prop) := by decide
theorem realPowInteger_def_lemma : ((∀ e b, (
  (if  e  == ( 0 :  Int) then ( 1 :  Int)  else 
  if  intGtb  e (( 0 :  Int)) then  b  ^  (e  - ( 1 :  Int))  *  b  else 
  b  ^  (e  + ( 1 :  Int))  /  b) ==  b  ^  e : Prop)) : Prop) := by decide
theorem realPowNat_def_lemma : ((∀ e r, ( r  ^  (Int.ofNat  e) ==  r  ^  e : Prop)) : Prop) := by decide
theorem integerSqrt_def_lemma : ((∀ i, ( realFloor  (realSqrt  (  i)) ==  integerSqrt  i : Prop)) : Prop) := by decide


/-  ==========================================================================  -/
/-  Tests                                                                       -/
/-  ==========================================================================  -/

#eval do
  if ( ((  2  +  (  5 :  Nat))  ==   7) : Bool)
  then IO.println "PASS: nat_test1"
  else throw (IO.userError "FAIL: nat_test1")
#eval do
  if ( ((  8  -  (  7 :  Nat))  ==   1) : Bool)
  then IO.println "PASS: nat_test2"
  else throw (IO.userError "FAIL: nat_test2")
#eval do
  if ( ((  7  -  (  8 :  Nat))  ==   0) : Bool)
  then IO.println "PASS: nat_test3"
  else throw (IO.userError "FAIL: nat_test3")
#eval do
  if ( ((  7  *  (  8 :  Nat))  ==   56) : Bool)
  then IO.println "PASS: nat_test4"
  else throw (IO.userError "FAIL: nat_test4")
#eval do
  if ( ( natPower (  7 :Nat) (  2)  ==   49) : Bool)
  then IO.println "PASS: nat_test5"
  else throw (IO.userError "FAIL: nat_test5")
#eval do
  if ( ((  11  /  (  4 :  Nat))  ==   2) : Bool)
  then IO.println "PASS: nat_test6"
  else throw (IO.userError "FAIL: nat_test6")
#eval do
  if ( ((  11  /  (  4 :  Nat))  ==   2) : Bool)
  then IO.println "PASS: nat_test7"
  else throw (IO.userError "FAIL: nat_test7")
#eval do
  if ( ((  11  %  (  4 :  Nat))  ==   3) : Bool)
  then IO.println "PASS: nat_test8"
  else throw (IO.userError "FAIL: nat_test8")
#eval do
  if ( ( natLtb (  11)  (  12 :  Nat)) : Bool)
  then IO.println "PASS: nat_test9"
  else throw (IO.userError "FAIL: nat_test9")
#eval do
  if ( ( natLteb (  11)  (  12 :  Nat)) : Bool)
  then IO.println "PASS: nat_test10"
  else throw (IO.userError "FAIL: nat_test10")
#eval do
  if ( ( natLteb (  12)  (  12 :  Nat)) : Bool)
  then IO.println "PASS: nat_test11"
  else throw (IO.userError "FAIL: nat_test11")
#eval do
  if ( (not  ( natLtb (  12)  (  12 :  Nat))) : Bool)
  then IO.println "PASS: nat_test12"
  else throw (IO.userError "FAIL: nat_test12")
#eval do
  if ( ( natGtb (  12)  (  11 :  Nat)) : Bool)
  then IO.println "PASS: nat_test13"
  else throw (IO.userError "FAIL: nat_test13")
#eval do
  if ( ( natGteb (  12)  (  11 :  Nat)) : Bool)
  then IO.println "PASS: nat_test14"
  else throw (IO.userError "FAIL: nat_test14")
#eval do
  if ( ( natGteb (  12)  (  12 :  Nat)) : Bool)
  then IO.println "PASS: nat_test15"
  else throw (IO.userError "FAIL: nat_test15")
#eval do
  if ( (not  ( natGtb (  12)  (  12 :  Nat))) : Bool)
  then IO.println "PASS: nat_test16"
  else throw (IO.userError "FAIL: nat_test16")
#eval do
  if ( (natMin (  12)  (  12 :  Nat)  ==   12) : Bool)
  then IO.println "PASS: nat_test17"
  else throw (IO.userError "FAIL: nat_test17")
#eval do
  if ( (natMin (  10)  (  12 :  Nat)  ==   10) : Bool)
  then IO.println "PASS: nat_test18"
  else throw (IO.userError "FAIL: nat_test18")
#eval do
  if ( (natMin (  12)  (  10 :  Nat)  ==   10) : Bool)
  then IO.println "PASS: nat_test19"
  else throw (IO.userError "FAIL: nat_test19")
#eval do
  if ( (natMax (  12)  (  12 :  Nat)  ==   12) : Bool)
  then IO.println "PASS: nat_test20"
  else throw (IO.userError "FAIL: nat_test20")
#eval do
  if ( (natMax (  10)  (  12 :  Nat)  ==   12) : Bool)
  then IO.println "PASS: nat_test21"
  else throw (IO.userError "FAIL: nat_test21")
#eval do
  if ( (natMax (  12)  (  10 :  Nat)  ==   12) : Bool)
  then IO.println "PASS: nat_test22"
  else throw (IO.userError "FAIL: nat_test22")
#eval do
  if ( (Nat.succ (  12)  ==  (  13 :  Nat)) : Bool)
  then IO.println "PASS: nat_test23"
  else throw (IO.userError "FAIL: nat_test23")
#eval do
  if ( (Nat.succ (  0)  ==  (  1 :  Nat)) : Bool)
  then IO.println "PASS: nat_test24"
  else throw (IO.userError "FAIL: nat_test24")
#eval do
  if ( (Nat.pred (  12)  ==  (  11 :  Nat)) : Bool)
  then IO.println "PASS: nat_test25"
  else throw (IO.userError "FAIL: nat_test25")
#eval do
  if ( (Nat.pred (  0)  ==  (  0 :  Nat)) : Bool)
  then IO.println "PASS: nat_test26"
  else throw (IO.userError "FAIL: nat_test26")
#eval do
  if ( (match  (  27 :Nat) with  |  0 =>  false |  (x + 2) =>  (x  ==   25) |  (x + 1) =>  (x  ==   26)
  ) : Bool)
  then IO.println "PASS: nat_test27"
  else throw (IO.userError "FAIL: nat_test27")
#eval do
  if ( (match  (  27 :Nat) with  |  (n + 50) =>  "50 <= x" |  40 =>  "x = 40" |  (n + 31) =>  "x <> 40 && 31 <= x < 50" |  29 =>  "x = 29" |  (n + 30) =>  "x = 30" |  4 =>  "x = 4" |  _ =>  "x <> 4 && x <> 29 && x < 30"
    ==  "x <> 4 && x <> 29 && x < 30") : Bool)
  then IO.println "PASS: nat_test28a"
  else throw (IO.userError "FAIL: nat_test28a")
#eval do
  if ( (match  (  30 :Nat) with  |  (n + 50) =>  "50 <= x" |  40 =>  "x = 40" |  (n + 31) =>  "x <> 40 && 31 <= x < 50" |  29 =>  "x = 29" |  (n + 30) =>  "x = 30" |  4 =>  "x = 4" |  _ =>  "x <> 4 && x <> 29 && x < 30"
    ==  "x = 30") : Bool)
  then IO.println "PASS: nat_test28b"
  else throw (IO.userError "FAIL: nat_test28b")
#eval do
  if ( ((  127  +  (  1 :  Nat))  ==   128) : Bool)
  then IO.println "PASS: nat_test29"
  else throw (IO.userError "FAIL: nat_test29")



#eval do
  if ( ((  2  +  (  5 :  Nat))  ==   7) : Bool)
  then IO.println "PASS: natural_test1"
  else throw (IO.userError "FAIL: natural_test1")
#eval do
  if ( ((  8  -  (  7 :  Nat))  ==   1) : Bool)
  then IO.println "PASS: natural_test2"
  else throw (IO.userError "FAIL: natural_test2")
#eval do
  if ( ((  7  -  (  8 :  Nat))  ==   0) : Bool)
  then IO.println "PASS: natural_test3"
  else throw (IO.userError "FAIL: natural_test3")
#eval do
  if ( ((  7  *  (  8 :  Nat))  ==   56) : Bool)
  then IO.println "PASS: natural_test4"
  else throw (IO.userError "FAIL: natural_test4")
#eval do
  if ( ( natPower (  7 :  Nat) (  2)  ==   49) : Bool)
  then IO.println "PASS: natural_test5"
  else throw (IO.userError "FAIL: natural_test5")
#eval do
  if ( ((  11  /  (  4 :  Nat))  ==   2) : Bool)
  then IO.println "PASS: natural_test6"
  else throw (IO.userError "FAIL: natural_test6")
#eval do
  if ( ((  11  /  (  4 :  Nat))  ==   2) : Bool)
  then IO.println "PASS: natural_test7"
  else throw (IO.userError "FAIL: natural_test7")
#eval do
  if ( ((  11  %  (  4 :  Nat))  ==   3) : Bool)
  then IO.println "PASS: natural_test8"
  else throw (IO.userError "FAIL: natural_test8")
#eval do
  if ( ( natLtb (  11)  (  12 :  Nat)) : Bool)
  then IO.println "PASS: natural_test9"
  else throw (IO.userError "FAIL: natural_test9")
#eval do
  if ( ( natLteb (  11)  (  12 :  Nat)) : Bool)
  then IO.println "PASS: natural_test10"
  else throw (IO.userError "FAIL: natural_test10")
#eval do
  if ( ( natLteb (  12)  (  12 :  Nat)) : Bool)
  then IO.println "PASS: natural_test11"
  else throw (IO.userError "FAIL: natural_test11")
#eval do
  if ( (not  ( natLtb (  12)  (  12 :  Nat))) : Bool)
  then IO.println "PASS: natural_test12"
  else throw (IO.userError "FAIL: natural_test12")
#eval do
  if ( ( natGtb (  12)  (  11 :  Nat)) : Bool)
  then IO.println "PASS: natural_test13"
  else throw (IO.userError "FAIL: natural_test13")
#eval do
  if ( ( natGteb (  12)  (  11 :  Nat)) : Bool)
  then IO.println "PASS: natural_test14"
  else throw (IO.userError "FAIL: natural_test14")
#eval do
  if ( ( natGteb (  12)  (  12 :  Nat)) : Bool)
  then IO.println "PASS: natural_test15"
  else throw (IO.userError "FAIL: natural_test15")
#eval do
  if ( (not  ( natGtb (  12)  (  12 :  Nat))) : Bool)
  then IO.println "PASS: natural_test16"
  else throw (IO.userError "FAIL: natural_test16")
#eval do
  if ( (natMin (  12)  (  12 :  Nat)  ==   12) : Bool)
  then IO.println "PASS: natural_test17"
  else throw (IO.userError "FAIL: natural_test17")
#eval do
  if ( (natMin (  10)  (  12 :  Nat)  ==   10) : Bool)
  then IO.println "PASS: natural_test18"
  else throw (IO.userError "FAIL: natural_test18")
#eval do
  if ( (natMin (  12)  (  10 :  Nat)  ==   10) : Bool)
  then IO.println "PASS: natural_test19"
  else throw (IO.userError "FAIL: natural_test19")
#eval do
  if ( (natMax (  12)  (  12 :  Nat)  ==   12) : Bool)
  then IO.println "PASS: natural_test20"
  else throw (IO.userError "FAIL: natural_test20")
#eval do
  if ( (natMax (  10)  (  12 :  Nat)  ==   12) : Bool)
  then IO.println "PASS: natural_test21"
  else throw (IO.userError "FAIL: natural_test21")
#eval do
  if ( (natMax (  12)  (  10 :  Nat)  ==   12) : Bool)
  then IO.println "PASS: natural_test22"
  else throw (IO.userError "FAIL: natural_test22")
#eval do
  if ( (Nat.succ (  12)  ==  (  13 :  Nat)) : Bool)
  then IO.println "PASS: natural_test23"
  else throw (IO.userError "FAIL: natural_test23")
#eval do
  if ( (Nat.succ (  0)  ==  (  1 :  Nat)) : Bool)
  then IO.println "PASS: natural_test24"
  else throw (IO.userError "FAIL: natural_test24")
#eval do
  if ( (Nat.pred (  12)  ==  (  11 :  Nat)) : Bool)
  then IO.println "PASS: natural_test25"
  else throw (IO.userError "FAIL: natural_test25")
#eval do
  if ( (Nat.pred (  0)  ==  (  0 :  Nat)) : Bool)
  then IO.println "PASS: natural_test26"
  else throw (IO.userError "FAIL: natural_test26")
#eval do
  if ( (match  (  27 :Nat) with  |  0 =>  false |  (x + 2) =>  (x  ==   25) |  (x + 1) =>  (x  ==   26)
  ) : Bool)
  then IO.println "PASS: natural_test27"
  else throw (IO.userError "FAIL: natural_test27")
#eval do
  if ( (match  (  27 :Nat) with  |  (n + 50) =>  "50 <= x" |  40 =>  "x = 40" |  (n + 31) =>  "x <> 40 && 31 <= x < 50" |  29 =>  "x = 29" |  (n + 30) =>  "x = 30" |  4 =>  "x = 4" |  _ =>  "x <> 4 && x <> 29 && x < 30"
    ==  "x <> 4 && x <> 29 && x < 30") : Bool)
  then IO.println "PASS: natural_test28a"
  else throw (IO.userError "FAIL: natural_test28a")
#eval do
  if ( (match  (  30 :Nat) with  |  (n + 50) =>  "50 <= x" |  40 =>  "x = 40" |  (n + 31) =>  "x <> 40 && 31 <= x < 50" |  29 =>  "x = 29" |  (n + 30) =>  "x = 30" |  4 =>  "x = 4" |  _ =>  "x <> 4 && x <> 29 && x < 30"
    ==  "x = 30") : Bool)
  then IO.println "PASS: natural_test28b"
  else throw (IO.userError "FAIL: natural_test28b")
#eval do
  if ( ((  127  +  (  1 :  Nat))  ==   128) : Bool)
  then IO.println "PASS: natural_test29"
  else throw (IO.userError "FAIL: natural_test29")


#eval do
  if ( ((( 2 :  Int)  +  (( 5 :  Int) :  Int))  == ( 7 :  Int)) : Bool)
  then IO.println "PASS: int_test1"
  else throw (IO.userError "FAIL: int_test1")
#eval do
  if ( ((( 8 :  Int)  -  (( 7 :  Int) :  Int))  == ( 1 :  Int)) : Bool)
  then IO.println "PASS: int_test2"
  else throw (IO.userError "FAIL: int_test2")
#eval do
  if ( ((( 7 :  Int)  -  (( 8 :  Int) :  Int))  ==  (Int.neg  (( 1 :  Int)))) : Bool)
  then IO.println "PASS: int_test3"
  else throw (IO.userError "FAIL: int_test3")
#eval do
  if ( ((( 7 :  Int)  *  (( 8 :  Int) :  Int))  == ( 56 :  Int)) : Bool)
  then IO.println "PASS: int_test4"
  else throw (IO.userError "FAIL: int_test4")
#eval do
  if ( (((( 7 :  Int) :Int)  ^   2)  == ( 49 :  Int)) : Bool)
  then IO.println "PASS: int_test5"
  else throw (IO.userError "FAIL: int_test5")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: int_test6"
  else throw (IO.userError "FAIL: int_test6")
#eval do
  if ( ((((Int.neg  (( 11 :  Int))))  /  (( 4 :  Int) :  Int))  ==  (Int.neg  (( 3 :  Int)))) : Bool)
  then IO.println "PASS: int_test6a"
  else throw (IO.userError "FAIL: int_test6a")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: int_test7"
  else throw (IO.userError "FAIL: int_test7")
#eval do
  if ( (((Int.neg  (( 11 :  Int)))  /  (( 4 :  Int) :  Int))  ==  (Int.neg  (( 3 :  Int)))) : Bool)
  then IO.println "PASS: int_test7a"
  else throw (IO.userError "FAIL: int_test7a")
#eval do
  if ( ((( 11 :  Int)  %  (( 4 :  Int) :  Int))  == ( 3 :  Int)) : Bool)
  then IO.println "PASS: int_test8"
  else throw (IO.userError "FAIL: int_test8")
#eval do
  if ( (((Int.neg  (( 11 :  Int)))  %  (( 4 :  Int) :  Int))  == ( 1 :  Int)) : Bool)
  then IO.println "PASS: int_test8at"
  else throw (IO.userError "FAIL: int_test8at")
#eval do
  if ( ( intLtb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test9"
  else throw (IO.userError "FAIL: int_test9")
#eval do
  if ( ( intLteb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test10"
  else throw (IO.userError "FAIL: int_test10")
#eval do
  if ( ( intLteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test11"
  else throw (IO.userError "FAIL: int_test11")
#eval do
  if ( (not  ( intLtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int_test12"
  else throw (IO.userError "FAIL: int_test12")
#eval do
  if ( ( intGtb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test13"
  else throw (IO.userError "FAIL: int_test13")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test14"
  else throw (IO.userError "FAIL: int_test14")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test15"
  else throw (IO.userError "FAIL: int_test15")
#eval do
  if ( (not  ( intGtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int_test16"
  else throw (IO.userError "FAIL: int_test16")
#eval do
  if ( (min (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int_test17"
  else throw (IO.userError "FAIL: int_test17")
#eval do
  if ( (min (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: int_test18"
  else throw (IO.userError "FAIL: int_test18")
#eval do
  if ( (min (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: int_test19"
  else throw (IO.userError "FAIL: int_test19")
#eval do
  if ( (max (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int_test20"
  else throw (IO.userError "FAIL: int_test20")
#eval do
  if ( (max (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int_test21"
  else throw (IO.userError "FAIL: int_test21")
#eval do
  if ( (max (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int_test22"
  else throw (IO.userError "FAIL: int_test22")
#eval do
  if ( ((( 12 :  Int)  + ( 1 :  Int))  ==  (( 13 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test23"
  else throw (IO.userError "FAIL: int_test23")
#eval do
  if ( ((( 0 :  Int)  + ( 1 :  Int))  ==  (( 1 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test24"
  else throw (IO.userError "FAIL: int_test24")
#eval do
  if ( ((( 12 :  Int)  - ( 1 :  Int))  ==  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test25"
  else throw (IO.userError "FAIL: int_test25")
#eval do
  if ( ((( 0 :  Int)  - ( 1 :  Int))  ==  (Int.neg  (( 1 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int_test26"
  else throw (IO.userError "FAIL: int_test26")
#eval do
  if ( (Int.natAbs (( 42 :  Int))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test27"
  else throw (IO.userError "FAIL: int_test27")
#eval do
  if ( (Int.natAbs  ((Int.neg  (( 42 :  Int))))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int_test28"
  else throw (IO.userError "FAIL: int_test28")
#eval do
  if ( ((( 127 :  Int)  +  (( 1 :  Int) :  Int))  == ( 128 :  Int)) : Bool)
  then IO.println "PASS: int_test29"
  else throw (IO.userError "FAIL: int_test29")

#eval do
  if ( ((( 2 :  Int)  +  (( 5 :  Int) :  Int))  == ( 7 :  Int)) : Bool)
  then IO.println "PASS: int32_test1"
  else throw (IO.userError "FAIL: int32_test1")
#eval do
  if ( ((( 8 :  Int)  -  (( 7 :  Int) :  Int))  == ( 1 :  Int)) : Bool)
  then IO.println "PASS: int32_test2"
  else throw (IO.userError "FAIL: int32_test2")
#eval do
  if ( ((( 7 :  Int)  -  (( 8 :  Int) :  Int))  ==  (Int.neg  (( 1 :  Int)))) : Bool)
  then IO.println "PASS: int32_test3"
  else throw (IO.userError "FAIL: int32_test3")
#eval do
  if ( ((( 7 :  Int)  *  (( 8 :  Int) :  Int))  == ( 56 :  Int)) : Bool)
  then IO.println "PASS: int32_test4"
  else throw (IO.userError "FAIL: int32_test4")
#eval do
  if ( (((( 7 :  Int) :  Int)  ^   2)  == ( 49 :  Int)) : Bool)
  then IO.println "PASS: int32_test5"
  else throw (IO.userError "FAIL: int32_test5")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: int32_test6"
  else throw (IO.userError "FAIL: int32_test6")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: int32_test7"
  else throw (IO.userError "FAIL: int32_test7")
#eval do
  if ( ((( 11 :  Int)  %  (( 4 :  Int) :  Int))  == ( 3 :  Int)) : Bool)
  then IO.println "PASS: int32_test8"
  else throw (IO.userError "FAIL: int32_test8")
#eval do
  if ( ( intLtb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test9"
  else throw (IO.userError "FAIL: int32_test9")
#eval do
  if ( ( intLteb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test10"
  else throw (IO.userError "FAIL: int32_test10")
#eval do
  if ( ( intLteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test11"
  else throw (IO.userError "FAIL: int32_test11")
#eval do
  if ( (not  ( intLtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int32_test12"
  else throw (IO.userError "FAIL: int32_test12")
#eval do
  if ( ( intGtb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test13"
  else throw (IO.userError "FAIL: int32_test13")
#eval do
  if ( ( intGtb (( 12 :  Int))  ((Int.neg  (( 11 :  Int) :  Int)))) : Bool)
  then IO.println "PASS: int32_test13a"
  else throw (IO.userError "FAIL: int32_test13a")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test14"
  else throw (IO.userError "FAIL: int32_test14")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test15"
  else throw (IO.userError "FAIL: int32_test15")
#eval do
  if ( (not  ( intGtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int32_test16"
  else throw (IO.userError "FAIL: int32_test16")
#eval do
  if ( (min (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int32_test17"
  else throw (IO.userError "FAIL: int32_test17")
#eval do
  if ( (min (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: int32_test18"
  else throw (IO.userError "FAIL: int32_test18")
#eval do
  if ( (min (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: int32_test19"
  else throw (IO.userError "FAIL: int32_test19")
#eval do
  if ( (max (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int32_test20"
  else throw (IO.userError "FAIL: int32_test20")
#eval do
  if ( (max  ((Int.neg  (( 10 :  Int))))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int32_test21"
  else throw (IO.userError "FAIL: int32_test21")
#eval do
  if ( (max (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int32_test22"
  else throw (IO.userError "FAIL: int32_test22")
#eval do
  if ( ((( 12 :  Int)  + ( 1 :  Int))  ==  (( 13 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test23"
  else throw (IO.userError "FAIL: int32_test23")
#eval do
  if ( ((( 0 :  Int)  + ( 1 :  Int))  ==  (( 1 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test24"
  else throw (IO.userError "FAIL: int32_test24")
#eval do
  if ( ((( 12 :  Int)  - ( 1 :  Int))  ==  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test25"
  else throw (IO.userError "FAIL: int32_test25")
#eval do
  if ( ((( 0 :  Int)  - ( 1 :  Int))  ==  (Int.neg  (( 1 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int32_test26"
  else throw (IO.userError "FAIL: int32_test26")
#eval do
  if ( (int32Abs (( 42 :  Int))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test27"
  else throw (IO.userError "FAIL: int32_test27")
#eval do
  if ( (int32Abs  ((Int.neg  (( 42 :  Int))))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int32_test28"
  else throw (IO.userError "FAIL: int32_test28")

#eval do
  if ( ((( 2 :  Int)  +  (( 5 :  Int) :  Int))  == ( 7 :  Int)) : Bool)
  then IO.println "PASS: int64_test1"
  else throw (IO.userError "FAIL: int64_test1")
#eval do
  if ( ((( 8 :  Int)  -  (( 7 :  Int) :  Int))  == ( 1 :  Int)) : Bool)
  then IO.println "PASS: int64_test2"
  else throw (IO.userError "FAIL: int64_test2")
#eval do
  if ( ((( 7 :  Int)  -  (( 8 :  Int) :  Int))  ==  (Int.neg  (( 1 :  Int)))) : Bool)
  then IO.println "PASS: int64_test3"
  else throw (IO.userError "FAIL: int64_test3")
#eval do
  if ( ((( 7 :  Int)  *  (( 8 :  Int) :  Int))  == ( 56 :  Int)) : Bool)
  then IO.println "PASS: int64_test4"
  else throw (IO.userError "FAIL: int64_test4")
#eval do
  if ( (((( 7 :  Int) :  Int)  ^   2)  == ( 49 :  Int)) : Bool)
  then IO.println "PASS: int64_test5"
  else throw (IO.userError "FAIL: int64_test5")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: int64_test6"
  else throw (IO.userError "FAIL: int64_test6")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: int64_test7"
  else throw (IO.userError "FAIL: int64_test7")
#eval do
  if ( ((( 11 :  Int)  %  (( 4 :  Int) :  Int))  == ( 3 :  Int)) : Bool)
  then IO.println "PASS: int64_test8"
  else throw (IO.userError "FAIL: int64_test8")
#eval do
  if ( ( intLtb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test9"
  else throw (IO.userError "FAIL: int64_test9")
#eval do
  if ( ( intLteb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test10"
  else throw (IO.userError "FAIL: int64_test10")
#eval do
  if ( ( intLteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test11"
  else throw (IO.userError "FAIL: int64_test11")
#eval do
  if ( (not  ( intLtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int64_test12"
  else throw (IO.userError "FAIL: int64_test12")
#eval do
  if ( ( intGtb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test13"
  else throw (IO.userError "FAIL: int64_test13")
#eval do
  if ( ( intGtb (( 12 :  Int))  ((Int.neg  (( 11 :  Int) :  Int)))) : Bool)
  then IO.println "PASS: int64_test13a"
  else throw (IO.userError "FAIL: int64_test13a")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test14"
  else throw (IO.userError "FAIL: int64_test14")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test15"
  else throw (IO.userError "FAIL: int64_test15")
#eval do
  if ( (not  ( intGtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int64_test16"
  else throw (IO.userError "FAIL: int64_test16")
#eval do
  if ( (min (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int64_test17"
  else throw (IO.userError "FAIL: int64_test17")
#eval do
  if ( (min (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: int64_test18"
  else throw (IO.userError "FAIL: int64_test18")
#eval do
  if ( (min (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: int64_test19"
  else throw (IO.userError "FAIL: int64_test19")
#eval do
  if ( (max (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int64_test20"
  else throw (IO.userError "FAIL: int64_test20")
#eval do
  if ( (max  ((Int.neg  (( 10 :  Int))))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int64_test21"
  else throw (IO.userError "FAIL: int64_test21")
#eval do
  if ( (max (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: int64_test22"
  else throw (IO.userError "FAIL: int64_test22")
#eval do
  if ( ((( 12 :  Int)  + ( 1 :  Int))  ==  (( 13 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test23"
  else throw (IO.userError "FAIL: int64_test23")
#eval do
  if ( ((( 0 :  Int)  + ( 1 :  Int))  ==  (( 1 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test24"
  else throw (IO.userError "FAIL: int64_test24")
#eval do
  if ( ((( 12 :  Int)  - ( 1 :  Int))  ==  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test25"
  else throw (IO.userError "FAIL: int64_test25")
#eval do
  if ( ((( 0 :  Int)  - ( 1 :  Int))  ==  (Int.neg  (( 1 :  Int) :  Int))) : Bool)
  then IO.println "PASS: int64_test26"
  else throw (IO.userError "FAIL: int64_test26")
#eval do
  if ( (int64Abs (( 42 :  Int))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test27"
  else throw (IO.userError "FAIL: int64_test27")
#eval do
  if ( (int64Abs  ((Int.neg  (( 42 :  Int))))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: int64_test28"
  else throw (IO.userError "FAIL: int64_test28")

#eval do
  if ( ((( 2 :  Int)  +  (( 5 :  Int) :  Int))  == ( 7 :  Int)) : Bool)
  then IO.println "PASS: integer_test1"
  else throw (IO.userError "FAIL: integer_test1")
#eval do
  if ( ((( 8 :  Int)  -  (( 7 :  Int) :  Int))  == ( 1 :  Int)) : Bool)
  then IO.println "PASS: integer_test2"
  else throw (IO.userError "FAIL: integer_test2")
#eval do
  if ( ((( 7 :  Int)  -  (( 8 :  Int) :  Int))  ==  (Int.neg  (( 1 :  Int)))) : Bool)
  then IO.println "PASS: integer_test3"
  else throw (IO.userError "FAIL: integer_test3")
#eval do
  if ( ((( 7 :  Int)  *  (( 8 :  Int) :  Int))  == ( 56 :  Int)) : Bool)
  then IO.println "PASS: integer_test4"
  else throw (IO.userError "FAIL: integer_test4")
#eval do
  if ( (((( 7 :  Int) :  Int)  ^   2)  == ( 49 :  Int)) : Bool)
  then IO.println "PASS: integer_test5"
  else throw (IO.userError "FAIL: integer_test5")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: integer_test6"
  else throw (IO.userError "FAIL: integer_test6")
#eval do
  if ( ((((Int.neg  (( 11 :  Int))))  /  (( 4 :  Int) :  Int))  ==  (Int.neg  (( 3 :  Int)))) : Bool)
  then IO.println "PASS: integer_test6a"
  else throw (IO.userError "FAIL: integer_test6a")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: integer_test7"
  else throw (IO.userError "FAIL: integer_test7")
#eval do
  if ( (((Int.neg  (( 11 :  Int)))  /  (( 4 :  Int) :  Int))  ==  (Int.neg  (( 3 :  Int)))) : Bool)
  then IO.println "PASS: integer_test7a"
  else throw (IO.userError "FAIL: integer_test7a")
#eval do
  if ( ((( 11 :  Int)  %  (( 4 :  Int) :  Int))  == ( 3 :  Int)) : Bool)
  then IO.println "PASS: integer_test8"
  else throw (IO.userError "FAIL: integer_test8")
#eval do
  if ( (((Int.neg  (( 11 :  Int)))  %  (( 4 :  Int) :  Int))  == ( 1 :  Int)) : Bool)
  then IO.println "PASS: integer_test8a"
  else throw (IO.userError "FAIL: integer_test8a")
#eval do
  if ( ( intLtb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test9"
  else throw (IO.userError "FAIL: integer_test9")
#eval do
  if ( ( intLteb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test10"
  else throw (IO.userError "FAIL: integer_test10")
#eval do
  if ( ( intLteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test11"
  else throw (IO.userError "FAIL: integer_test11")
#eval do
  if ( (not  ( intLtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: integer_test12"
  else throw (IO.userError "FAIL: integer_test12")
#eval do
  if ( ( intGtb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test13"
  else throw (IO.userError "FAIL: integer_test13")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test14"
  else throw (IO.userError "FAIL: integer_test14")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test15"
  else throw (IO.userError "FAIL: integer_test15")
#eval do
  if ( (not  ( intGtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: integer_test16"
  else throw (IO.userError "FAIL: integer_test16")
#eval do
  if ( (min (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: integer_test17"
  else throw (IO.userError "FAIL: integer_test17")
#eval do
  if ( (min (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: integer_test18"
  else throw (IO.userError "FAIL: integer_test18")
#eval do
  if ( (min (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: integer_test19"
  else throw (IO.userError "FAIL: integer_test19")
#eval do
  if ( (max (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: integer_test20"
  else throw (IO.userError "FAIL: integer_test20")
#eval do
  if ( (max (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: integer_test21"
  else throw (IO.userError "FAIL: integer_test21")
#eval do
  if ( (max (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: integer_test22"
  else throw (IO.userError "FAIL: integer_test22")
#eval do
  if ( ((( 12 :  Int)  + ( 1 :  Int))  ==  (( 13 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test23"
  else throw (IO.userError "FAIL: integer_test23")
#eval do
  if ( ((( 0 :  Int)  + ( 1 :  Int))  ==  (( 1 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test24"
  else throw (IO.userError "FAIL: integer_test24")
#eval do
  if ( ((( 12 :  Int)  - ( 1 :  Int))  ==  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test25"
  else throw (IO.userError "FAIL: integer_test25")
#eval do
  if ( ((( 0 :  Int)  - ( 1 :  Int))  ==  (Int.neg  (( 1 :  Int) :  Int))) : Bool)
  then IO.println "PASS: integer_test26"
  else throw (IO.userError "FAIL: integer_test26")
#eval do
  if ( (Int.natAbs (( 42 :  Int))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test27"
  else throw (IO.userError "FAIL: integer_test27")
#eval do
  if ( (Int.natAbs  ((Int.neg  (( 42 :  Int))))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: integer_test28"
  else throw (IO.userError "FAIL: integer_test28")
#eval do
  if ( (integerSqrt (( 5 :  Int))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: integer_test29"
  else throw (IO.userError "FAIL: integer_test29")
#eval do
  if ( ((( 18446744073709551615 :  Int)  +  (( 1 :  Int) :  Int))  == ( 18446744073709551616 :  Int)) : Bool)
  then IO.println "PASS: integer_test30"
  else throw (IO.userError "FAIL: integer_test30")


#eval do
  if ( ((( 2 :  Int)  +  (( 5 :  Int) :  Int))  == ( 7 :  Int)) : Bool)
  then IO.println "PASS: rational_test1"
  else throw (IO.userError "FAIL: rational_test1")
#eval do
  if ( (((rationalFromFrac (( 3 :  Int)) (( 2 :  Int)))  +  (rationalFromFrac (( 1 :  Int)) (( 2 :  Int))))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: rational_test2"
  else throw (IO.userError "FAIL: rational_test2")
#eval do
  if ( ((( 7 :  Int)  -  (( 8 :  Int) :  Int))  == (( 0 :  Int)  - ( 1 :  Int))) : Bool)
  then IO.println "PASS: rational_test3"
  else throw (IO.userError "FAIL: rational_test3")
#eval do
  if ( ((( 7 :  Int)  *  (( 8 :  Int) :  Int))  == ( 56 :  Int)) : Bool)
  then IO.println "PASS: rational_test4"
  else throw (IO.userError "FAIL: rational_test4")
#eval do
  if ( (((( 7 :  Int) :  Int)  ^   2)  == ( 49 :  Int)) : Bool)
  then IO.println "PASS: rational_test5"
  else throw (IO.userError "FAIL: rational_test5")
#eval do
  if ( ((( 2 :  Int) :  Int)  ^  ((Int.neg  (( 3 :  Int))))  ==  rationalFromFrac (( 1 :  Int)) (( 8 :  Int))) : Bool)
  then IO.println "PASS: rational_test5a"
  else throw (IO.userError "FAIL: rational_test5a")
#eval do
  if ( ((( 0 :  Int)  - ( 2 :  Int) :  Int)  ^  ((Int.neg  (( 3 :  Int))))  ==  rationalFromFrac  ((Int.neg  (( 1 :  Int)))) (( 8 :  Int))) : Bool)
  then IO.println "PASS: rational_test5b"
  else throw (IO.userError "FAIL: rational_test5b")
#eval do
  if ( ((( 0 :  Int)  - ( 2 :  Int) :  Int)  ^  ((Int.neg  (( 2 :  Int))))  ==  rationalFromFrac (( 1 :  Int)) (( 4 :  Int))) : Bool)
  then IO.println "PASS: rational_test5c"
  else throw (IO.userError "FAIL: rational_test5c")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  ==  (rationalFromFrac (( 11 :  Int)) (( 4 :  Int)))) : Bool)
  then IO.println "PASS: rational_test6"
  else throw (IO.userError "FAIL: rational_test6")
#eval do
  if ( (((( 0 :  Int)  - ( 11 :  Int))  /  (( 4 :  Int) :  Int))  ==  (rationalFromFrac  ((Int.neg  (( 11 :  Int)))) (( 4 :  Int)))) : Bool)
  then IO.println "PASS: rational_test6a"
  else throw (IO.userError "FAIL: rational_test6a")
#eval do
  if ( ( intLtb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test7"
  else throw (IO.userError "FAIL: rational_test7")
#eval do
  if ( ( intLteb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test8"
  else throw (IO.userError "FAIL: rational_test8")
#eval do
  if ( ( intLteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test9"
  else throw (IO.userError "FAIL: rational_test9")
#eval do
  if ( (not  ( intLtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: rational_test10"
  else throw (IO.userError "FAIL: rational_test10")
#eval do
  if ( ( intGtb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test11"
  else throw (IO.userError "FAIL: rational_test11")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test12"
  else throw (IO.userError "FAIL: rational_test12")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test13"
  else throw (IO.userError "FAIL: rational_test13")
#eval do
  if ( (not  ( intGtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: rational_test14"
  else throw (IO.userError "FAIL: rational_test14")
#eval do
  if ( (min (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: rational_test15"
  else throw (IO.userError "FAIL: rational_test15")
#eval do
  if ( (min (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: rational_test16"
  else throw (IO.userError "FAIL: rational_test16")
#eval do
  if ( (min (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: rational_test17"
  else throw (IO.userError "FAIL: rational_test17")
#eval do
  if ( (max (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: rational_test18"
  else throw (IO.userError "FAIL: rational_test18")
#eval do
  if ( (max (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: rational_test19"
  else throw (IO.userError "FAIL: rational_test19")
#eval do
  if ( (max (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: rational_test20"
  else throw (IO.userError "FAIL: rational_test20")
#eval do
  if ( ((( 12 :  Int)  + ( 1 :  Int))  ==  (( 13 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test21"
  else throw (IO.userError "FAIL: rational_test21")
#eval do
  if ( ((( 0 :  Int)  + ( 1 :  Int))  ==  (( 1 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test22"
  else throw (IO.userError "FAIL: rational_test22")
#eval do
  if ( ((( 12 :  Int)  - ( 1 :  Int))  ==  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test23"
  else throw (IO.userError "FAIL: rational_test23")
#eval do
  if ( ((( 0 :  Int)  - ( 1 :  Int))  == (( 0 :  Int)  -  (( 1 :  Int) :  Int))) : Bool)
  then IO.println "PASS: rational_test24"
  else throw (IO.userError "FAIL: rational_test24")
#eval do
  if ( ((if  intGtb (( 42 :  Int)) (( 0 :  Int)) then ( 42 :  Int)  else ( 0 :  Int)  -  ( 42 :  Int))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test25"
  else throw (IO.userError "FAIL: rational_test25")
#eval do
  if ( ((if  intGtb  (( 0 :  Int)  - ( 42 :  Int)) (( 0 :  Int)) then  (( 0 :  Int)  - ( 42 :  Int))  else ( 0 :  Int)  -  (( 0 :  Int)  - ( 42 :  Int)))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: rational_test26"
  else throw (IO.userError "FAIL: rational_test26")
#eval do
  if ( (((rationalFromFrac (( 1 :  Int)) (( 2 :  Int)))  * ( 2 :  Int))  == ( 1 :  Int)) : Bool)
  then IO.println "PASS: rational_test27"
  else throw (IO.userError "FAIL: rational_test27")
#eval do
  if (
  (let  r  := rationalFromFrac  ((Int.neg  (( 11 :  Int)))) (( 4 :  Int)) 

   ((  (rationalNumerator  r)  /    (rationalDenominator  r))  ==  r)) : Bool)
  then IO.println "PASS: rational_test28"
  else throw (IO.userError "FAIL: rational_test28")
#eval do
  if (
  (let  r  := rationalFromFrac (( 8 :  Int)) (( 4 :  Int)) 

   ((  (rationalNumerator  r)  /    (rationalDenominator  r))  ==   (( 2 :  Int)))) : Bool)
  then IO.println "PASS: rational_test29"
  else throw (IO.userError "FAIL: rational_test29")

#eval do
  if ( ((( 2 :  Int)  +  (( 5 :  Int) :  Int))  == ( 7 :  Int)) : Bool)
  then IO.println "PASS: real_test1"
  else throw (IO.userError "FAIL: real_test1")
#eval do
  if ( (((( 3 :  Int)  /  (( 2 :  Int) :  Int))  +  (( 1 :  Int)  / ( 2 :  Int)))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: real_test2"
  else throw (IO.userError "FAIL: real_test2")
#eval do
  if ( ((( 7 :  Int)  -  (( 8 :  Int) :  Int))  ==  Int.neg (( 1 :  Int))) : Bool)
  then IO.println "PASS: real_test3"
  else throw (IO.userError "FAIL: real_test3")
#eval do
  if ( ((( 7 :  Int)  *  (( 8 :  Int) :  Int))  == ( 56 :  Int)) : Bool)
  then IO.println "PASS: real_test4"
  else throw (IO.userError "FAIL: real_test4")
#eval do
  if ( (((( 7 :  Int) :  Int)  ^   2)  == ( 49 :  Int)) : Bool)
  then IO.println "PASS: real_test5"
  else throw (IO.userError "FAIL: real_test5")
#eval do
  if ( ((( 2 :  Int) :  Int)  ^  ((Int.neg  (( 3 :  Int))))  ==  realFromFrac (( 1 :  Int)) (( 8 :  Int))) : Bool)
  then IO.println "PASS: real_test5a"
  else throw (IO.userError "FAIL: real_test5a")
#eval do
  if ( ((Int.neg (( 2 :  Int)) :  Int)  ^  ((Int.neg  (( 3 :  Int))))  ==  realFromFrac  ((Int.neg  (( 1 :  Int)))) (( 8 :  Int))) : Bool)
  then IO.println "PASS: real_test5b"
  else throw (IO.userError "FAIL: real_test5b")
#eval do
  if ( ((Int.neg (( 2 :  Int)) :  Int)  ^  ((Int.neg  (( 2 :  Int))))  ==  realFromFrac (( 1 :  Int)) (( 4 :  Int))) : Bool)
  then IO.println "PASS: real_test5c"
  else throw (IO.userError "FAIL: real_test5c")
#eval do
  if ( ((( 11 :  Int)  /  (( 4 :  Int) :  Int))  ==  (realFromFrac (( 11 :  Int)) (( 4 :  Int)))) : Bool)
  then IO.println "PASS: real_test6"
  else throw (IO.userError "FAIL: real_test6")
#eval do
  if ( (((Int.neg (( 11 :  Int)))  /  (( 4 :  Int) :  Int))  ==  (realFromFrac  ((Int.neg  (( 11 :  Int)))) (( 4 :  Int)))) : Bool)
  then IO.println "PASS: real_test6a"
  else throw (IO.userError "FAIL: real_test6a")
#eval do
  if ( ( intLtb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test7"
  else throw (IO.userError "FAIL: real_test7")
#eval do
  if ( ( intLteb (( 11 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test8"
  else throw (IO.userError "FAIL: real_test8")
#eval do
  if ( ( intLteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test9"
  else throw (IO.userError "FAIL: real_test9")
#eval do
  if ( (not  ( intLtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: real_test10"
  else throw (IO.userError "FAIL: real_test10")
#eval do
  if ( ( intGtb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test11"
  else throw (IO.userError "FAIL: real_test11")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test12"
  else throw (IO.userError "FAIL: real_test12")
#eval do
  if ( ( intGteb (( 12 :  Int))  (( 12 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test13"
  else throw (IO.userError "FAIL: real_test13")
#eval do
  if ( (not  ( intGtb (( 12 :  Int))  (( 12 :  Int) :  Int))) : Bool)
  then IO.println "PASS: real_test14"
  else throw (IO.userError "FAIL: real_test14")
#eval do
  if ( (min (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: real_test15"
  else throw (IO.userError "FAIL: real_test15")
#eval do
  if ( (min (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: real_test16"
  else throw (IO.userError "FAIL: real_test16")
#eval do
  if ( (min (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 10 :  Int)) : Bool)
  then IO.println "PASS: real_test17"
  else throw (IO.userError "FAIL: real_test17")
#eval do
  if ( (max (( 12 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: real_test18"
  else throw (IO.userError "FAIL: real_test18")
#eval do
  if ( (max (( 10 :  Int))  (( 12 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: real_test19"
  else throw (IO.userError "FAIL: real_test19")
#eval do
  if ( (max (( 12 :  Int))  (( 10 :  Int) :  Int)  == ( 12 :  Int)) : Bool)
  then IO.println "PASS: real_test20"
  else throw (IO.userError "FAIL: real_test20")
#eval do
  if ( ((( 12 :  Int)  + ( 1 :  Int))  ==  (( 13 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test21"
  else throw (IO.userError "FAIL: real_test21")
#eval do
  if ( ((( 0 :  Int)  + ( 1 :  Int))  ==  (( 1 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test22"
  else throw (IO.userError "FAIL: real_test22")
#eval do
  if ( ((( 12 :  Int)  - ( 1 :  Int))  ==  (( 11 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test23"
  else throw (IO.userError "FAIL: real_test23")
#eval do
  if ( ((( 0 :  Int)  - ( 1 :  Int))  ==  Int.neg (( 1 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test24"
  else throw (IO.userError "FAIL: real_test24")
#eval do
  if ( (Int.natAbs (( 42 :  Int))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test25"
  else throw (IO.userError "FAIL: real_test25")
#eval do
  if ( (Int.natAbs  (Int.neg (( 42 :  Int)))  ==  (( 42 :  Int) :  Int)) : Bool)
  then IO.println "PASS: real_test26"
  else throw (IO.userError "FAIL: real_test26")
#eval do
  if ( (((( 1 :  Int)  /  (( 2 :  Int) :  Int))  * ( 2 :  Int))  == ( 1 :  Int)) : Bool)
  then IO.println "PASS: real_test27"
  else throw (IO.userError "FAIL: real_test27")
#eval do
  if ( (realFloor  (realFromFrac (( 11 :  Int)) (( 4 :  Int)))  == ( 2 :  Int)) : Bool)
  then IO.println "PASS: real_test28"
  else throw (IO.userError "FAIL: real_test28")
#eval do
  if ( (realCeiling  (realFromFrac (( 11 :  Int)) (( 4 :  Int)))  == ( 3 :  Int)) : Bool)
  then IO.println "PASS: real_test29"
  else throw (IO.userError "FAIL: real_test29")
#eval do
  if ( (realFloor  (realFromFrac (( 12 :  Int)) (( 4 :  Int)))  == ( 3 :  Int)) : Bool)
  then IO.println "PASS: real_test30"
  else throw (IO.userError "FAIL: real_test30")
#eval do
  if ( (realCeiling  (realFromFrac (( 12 :  Int)) (( 4 :  Int)))  == ( 3 :  Int)) : Bool)
  then IO.println "PASS: real_test31"
  else throw (IO.userError "FAIL: real_test31")
#eval do
  if ( (realFloor  (realFromFrac  ((Int.neg  (( 3 :  Int)))) (( 2 :  Int)))  ==  (Int.neg  (( 2 :  Int)))) : Bool)
  then IO.println "PASS: real_test32"
  else throw (IO.userError "FAIL: real_test32")
#eval do
  if ( (realCeiling  (realFromFrac  ((Int.neg  (( 3 :  Int)))) (( 2 :  Int)))  ==  (Int.neg  (( 1 :  Int)))) : Bool)
  then IO.println "PASS: real_test33"
  else throw (IO.userError "FAIL: real_test33")

#eval do
  if (  (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: integer_from_int_0"
  else throw (IO.userError "FAIL: integer_from_int_0")
#eval do
  if (  (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: integer_from_int_1"
  else throw (IO.userError "FAIL: integer_from_int_1")
#eval do
  if (   ((Int.neg  (( 2 :  Int))))  ==  ((Int.neg  (( 2 :  Int)))) : Bool)
  then IO.println "PASS: integer_from_int_2"
  else throw (IO.userError "FAIL: integer_from_int_2")

#eval do
  if ( Int.ofNat (  0)  == ( 0 :  Int) : Bool)
  then IO.println "PASS: integer_from_nat_0"
  else throw (IO.userError "FAIL: integer_from_nat_0")
#eval do
  if ( Int.ofNat (  1)  == ( 1 :  Int) : Bool)
  then IO.println "PASS: integer_from_nat_1"
  else throw (IO.userError "FAIL: integer_from_nat_1")
#eval do
  if ( Int.ofNat (  12)  == ( 12 :  Int) : Bool)
  then IO.println "PASS: integer_from_nat_2"
  else throw (IO.userError "FAIL: integer_from_nat_2")

#eval do
  if ( Int.ofNat (  0)  == ( 0 :  Int) : Bool)
  then IO.println "PASS: integerFromNatural_0"
  else throw (IO.userError "FAIL: integerFromNatural_0")
#eval do
  if ( Int.ofNat (  822)  == ( 822 :  Int) : Bool)
  then IO.println "PASS: integerFromNatural_1"
  else throw (IO.userError "FAIL: integerFromNatural_1")
#eval do
  if ( Int.ofNat (  12)  == ( 12 :  Int) : Bool)
  then IO.println "PASS: integerFromNatural_2"
  else throw (IO.userError "FAIL: integerFromNatural_2")

#eval do
  if (  (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: integer_from_int32_0"
  else throw (IO.userError "FAIL: integer_from_int32_0")
#eval do
  if (  (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: integer_from_int32_1"
  else throw (IO.userError "FAIL: integer_from_int32_1")
#eval do
  if (  (( 123 :  Int))  == ( 123 :  Int) : Bool)
  then IO.println "PASS: integer_from_int32_2"
  else throw (IO.userError "FAIL: integer_from_int32_2")
#eval do
  if (   ((Int.neg  (( 0 :  Int))))  ==  (Int.neg  (( 0 :  Int))) : Bool)
  then IO.println "PASS: integer_from_int32_3"
  else throw (IO.userError "FAIL: integer_from_int32_3")
#eval do
  if (   ((Int.neg  (( 1 :  Int))))  ==  (Int.neg  (( 1 :  Int))) : Bool)
  then IO.println "PASS: integer_from_int32_4"
  else throw (IO.userError "FAIL: integer_from_int32_4")
#eval do
  if (   ((Int.neg  (( 123 :  Int))))  ==  (Int.neg  (( 123 :  Int))) : Bool)
  then IO.println "PASS: integer_from_int32_5"
  else throw (IO.userError "FAIL: integer_from_int32_5")

#eval do
  if (  (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: integer_from_int64_0"
  else throw (IO.userError "FAIL: integer_from_int64_0")
#eval do
  if (  (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: integer_from_int64_1"
  else throw (IO.userError "FAIL: integer_from_int64_1")
#eval do
  if (  (( 123 :  Int))  == ( 123 :  Int) : Bool)
  then IO.println "PASS: integer_from_int64_2"
  else throw (IO.userError "FAIL: integer_from_int64_2")
#eval do
  if (   ((Int.neg  (( 0 :  Int))))  ==  (Int.neg  (( 0 :  Int))) : Bool)
  then IO.println "PASS: integer_from_int64_3"
  else throw (IO.userError "FAIL: integer_from_int64_3")
#eval do
  if (   ((Int.neg  (( 1 :  Int))))  ==  (Int.neg  (( 1 :  Int))) : Bool)
  then IO.println "PASS: integer_from_int64_4"
  else throw (IO.userError "FAIL: integer_from_int64_4")
#eval do
  if (   ((Int.neg  (( 123 :  Int))))  ==  (Int.neg  (( 123 :  Int))) : Bool)
  then IO.println "PASS: integer_from_int64_5"
  else throw (IO.userError "FAIL: integer_from_int64_5")

#eval do
  if (  (  0)  ==   0 : Bool)
  then IO.println "PASS: natural_from_nat_0"
  else throw (IO.userError "FAIL: natural_from_nat_0")
#eval do
  if (  (  1)  ==   1 : Bool)
  then IO.println "PASS: natural_from_nat_1"
  else throw (IO.userError "FAIL: natural_from_nat_1")
#eval do
  if (  (  2)  ==   2 : Bool)
  then IO.println "PASS: natural_from_nat_2"
  else throw (IO.userError "FAIL: natural_from_nat_2")

#eval do
  if ( Int.natAbs (( 0 :  Int))  ==   0 : Bool)
  then IO.println "PASS: natural_from_integer_0"
  else throw (IO.userError "FAIL: natural_from_integer_0")
#eval do
  if ( Int.natAbs (( 1 :  Int))  ==   1 : Bool)
  then IO.println "PASS: natural_from_integer_1"
  else throw (IO.userError "FAIL: natural_from_integer_1")
#eval do
  if ( Int.natAbs  ((Int.neg  (( 2 :  Int))))  ==   2 : Bool)
  then IO.println "PASS: natural_from_integer_2"
  else throw (IO.userError "FAIL: natural_from_integer_2")

#eval do
  if (  (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int_from_integer_0"
  else throw (IO.userError "FAIL: int_from_integer_0")
#eval do
  if (  (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int_from_integer_1"
  else throw (IO.userError "FAIL: int_from_integer_1")
#eval do
  if (   ((Int.neg  (( 2 :  Int))))  ==  ((Int.neg  (( 2 :  Int)))) : Bool)
  then IO.println "PASS: int_from_integer_2"
  else throw (IO.userError "FAIL: int_from_integer_2")

#eval do
  if ( Int.ofNat (  0)  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int_from_nat_0"
  else throw (IO.userError "FAIL: int_from_nat_0")
#eval do
  if ( Int.ofNat (  1)  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int_from_nat_1"
  else throw (IO.userError "FAIL: int_from_nat_1")
#eval do
  if ( Int.ofNat (  2)  == ( 2 :  Int) : Bool)
  then IO.println "PASS: int_from_nat_2"
  else throw (IO.userError "FAIL: int_from_nat_2")

#eval do
  if (  (  0)  ==   0 : Bool)
  then IO.println "PASS: nat_from_natural_0"
  else throw (IO.userError "FAIL: nat_from_natural_0")
#eval do
  if (  (  1)  ==   1 : Bool)
  then IO.println "PASS: nat_from_natural_1"
  else throw (IO.userError "FAIL: nat_from_natural_1")
#eval do
  if (  (  2)  ==   2 : Bool)
  then IO.println "PASS: nat_from_natural_2"
  else throw (IO.userError "FAIL: nat_from_natural_2")

#eval do
  if ( Int.natAbs (( 0 :  Int))  ==   0 : Bool)
  then IO.println "PASS: nat_from_int_0"
  else throw (IO.userError "FAIL: nat_from_int_0")
#eval do
  if ( Int.natAbs (( 1 :  Int))  ==   1 : Bool)
  then IO.println "PASS: nat_from_int_1"
  else throw (IO.userError "FAIL: nat_from_int_1")
#eval do
  if ( Int.natAbs  ((Int.neg  (( 2 :  Int))))  ==   2 : Bool)
  then IO.println "PASS: nat_from_int_2"
  else throw (IO.userError "FAIL: nat_from_int_2")

#eval do
  if ( Int.ofNat (  0)  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int32_from_nat_0"
  else throw (IO.userError "FAIL: int32_from_nat_0")
#eval do
  if ( Int.ofNat (  1)  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int32_from_nat_1"
  else throw (IO.userError "FAIL: int32_from_nat_1")
#eval do
  if ( Int.ofNat (  123)  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int32_from_nat_2"
  else throw (IO.userError "FAIL: int32_from_nat_2")

#eval do
  if ( Int.ofNat (  0)  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int32_from_natural_0"
  else throw (IO.userError "FAIL: int32_from_natural_0")
#eval do
  if ( Int.ofNat (  1)  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int32_from_natural_1"
  else throw (IO.userError "FAIL: int32_from_natural_1")
#eval do
  if ( Int.ofNat (  123)  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int32_from_natural_2"
  else throw (IO.userError "FAIL: int32_from_natural_2")

#eval do
  if ( int32FromInteger (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int32_from_integer_0"
  else throw (IO.userError "FAIL: int32_from_integer_0")
#eval do
  if ( int32FromInteger (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int32_from_integer_1"
  else throw (IO.userError "FAIL: int32_from_integer_1")
#eval do
  if ( int32FromInteger (( 123 :  Int))  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int32_from_integer_2"
  else throw (IO.userError "FAIL: int32_from_integer_2")
#eval do
  if ( int32FromInteger  ((Int.neg  (( 0 :  Int))))  ==  (Int.neg  (( 0 :  Int))) : Bool)
  then IO.println "PASS: int32_from_integer_3"
  else throw (IO.userError "FAIL: int32_from_integer_3")
#eval do
  if ( int32FromInteger  ((Int.neg  (( 1 :  Int))))  ==  (Int.neg  (( 1 :  Int))) : Bool)
  then IO.println "PASS: int32_from_integer_4"
  else throw (IO.userError "FAIL: int32_from_integer_4")
#eval do
  if ( int32FromInteger  ((Int.neg  (( 123 :  Int))))  ==  (Int.neg  (( 123 :  Int))) : Bool)
  then IO.println "PASS: int32_from_integer_5"
  else throw (IO.userError "FAIL: int32_from_integer_5")

#eval do
  if ( int32FromInt (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int32_from_int_0"
  else throw (IO.userError "FAIL: int32_from_int_0")
#eval do
  if ( int32FromInt (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int32_from_int_1"
  else throw (IO.userError "FAIL: int32_from_int_1")
#eval do
  if ( int32FromInt (( 123 :  Int))  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int32_from_int_2"
  else throw (IO.userError "FAIL: int32_from_int_2")
#eval do
  if ( int32FromInt  ((Int.neg  (( 0 :  Int))))  ==  (Int.neg  (( 0 :  Int))) : Bool)
  then IO.println "PASS: int32_from_int_3"
  else throw (IO.userError "FAIL: int32_from_int_3")
#eval do
  if ( int32FromInt  ((Int.neg  (( 1 :  Int))))  ==  (Int.neg  (( 1 :  Int))) : Bool)
  then IO.println "PASS: int32_from_int_4"
  else throw (IO.userError "FAIL: int32_from_int_4")
#eval do
  if ( int32FromInt  ((Int.neg  (( 123 :  Int))))  ==  (Int.neg  (( 123 :  Int))) : Bool)
  then IO.println "PASS: int32_from_int_5"
  else throw (IO.userError "FAIL: int32_from_int_5")

#eval do
  if ( int32FromInt64 (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int32_from_int_64_0"
  else throw (IO.userError "FAIL: int32_from_int_64_0")
#eval do
  if ( int32FromInt64 (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int32_from_int_64_1"
  else throw (IO.userError "FAIL: int32_from_int_64_1")
#eval do
  if ( int32FromInt64 (( 123 :  Int))  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int32_from_int_64_2"
  else throw (IO.userError "FAIL: int32_from_int_64_2")
#eval do
  if ( int32FromInt64  ((Int.neg  (( 0 :  Int))))  ==  (Int.neg  (( 0 :  Int))) : Bool)
  then IO.println "PASS: int32_from_int_64_3"
  else throw (IO.userError "FAIL: int32_from_int_64_3")
#eval do
  if ( int32FromInt64  ((Int.neg  (( 1 :  Int))))  ==  (Int.neg  (( 1 :  Int))) : Bool)
  then IO.println "PASS: int32_from_int_64_4"
  else throw (IO.userError "FAIL: int32_from_int_64_4")
#eval do
  if ( int32FromInt64  ((Int.neg  (( 123 :  Int))))  ==  (Int.neg  (( 123 :  Int))) : Bool)
  then IO.println "PASS: int32_from_int_64_5"
  else throw (IO.userError "FAIL: int32_from_int_64_5")

#eval do
  if ( Int.ofNat (  0)  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int64_from_nat_0"
  else throw (IO.userError "FAIL: int64_from_nat_0")
#eval do
  if ( Int.ofNat (  1)  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int64_from_nat_1"
  else throw (IO.userError "FAIL: int64_from_nat_1")
#eval do
  if ( Int.ofNat (  123)  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int64_from_nat_2"
  else throw (IO.userError "FAIL: int64_from_nat_2")

#eval do
  if ( Int.ofNat (  0)  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int64_from_natural_0"
  else throw (IO.userError "FAIL: int64_from_natural_0")
#eval do
  if ( Int.ofNat (  1)  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int64_from_natural_1"
  else throw (IO.userError "FAIL: int64_from_natural_1")
#eval do
  if ( Int.ofNat (  123)  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int64_from_natural_2"
  else throw (IO.userError "FAIL: int64_from_natural_2")

#eval do
  if ( int64FromInteger (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int64_from_integer_0"
  else throw (IO.userError "FAIL: int64_from_integer_0")
#eval do
  if ( int64FromInteger (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int64_from_integer_1"
  else throw (IO.userError "FAIL: int64_from_integer_1")
#eval do
  if ( int64FromInteger (( 123 :  Int))  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int64_from_integer_2"
  else throw (IO.userError "FAIL: int64_from_integer_2")
#eval do
  if ( int64FromInteger  ((Int.neg  (( 0 :  Int))))  ==  (Int.neg  (( 0 :  Int))) : Bool)
  then IO.println "PASS: int64_from_integer_3"
  else throw (IO.userError "FAIL: int64_from_integer_3")
#eval do
  if ( int64FromInteger  ((Int.neg  (( 1 :  Int))))  ==  (Int.neg  (( 1 :  Int))) : Bool)
  then IO.println "PASS: int64_from_integer_4"
  else throw (IO.userError "FAIL: int64_from_integer_4")
#eval do
  if ( int64FromInteger  ((Int.neg  (( 123 :  Int))))  ==  (Int.neg  (( 123 :  Int))) : Bool)
  then IO.println "PASS: int64_from_integer_5"
  else throw (IO.userError "FAIL: int64_from_integer_5")

#eval do
  if ( int64FromInt (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int64_from_int_0"
  else throw (IO.userError "FAIL: int64_from_int_0")
#eval do
  if ( int64FromInt (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int64_from_int_1"
  else throw (IO.userError "FAIL: int64_from_int_1")
#eval do
  if ( int64FromInt (( 123 :  Int))  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int64_from_int_2"
  else throw (IO.userError "FAIL: int64_from_int_2")
#eval do
  if ( int64FromInt  ((Int.neg  (( 0 :  Int))))  ==  (Int.neg  (( 0 :  Int))) : Bool)
  then IO.println "PASS: int64_from_int_3"
  else throw (IO.userError "FAIL: int64_from_int_3")
#eval do
  if ( int64FromInt  ((Int.neg  (( 1 :  Int))))  ==  (Int.neg  (( 1 :  Int))) : Bool)
  then IO.println "PASS: int64_from_int_4"
  else throw (IO.userError "FAIL: int64_from_int_4")
#eval do
  if ( int64FromInt  ((Int.neg  (( 123 :  Int))))  ==  (Int.neg  (( 123 :  Int))) : Bool)
  then IO.println "PASS: int64_from_int_5"
  else throw (IO.userError "FAIL: int64_from_int_5")

#eval do
  if ( int64FromInt32 (( 0 :  Int))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int64_from_int_33_0"
  else throw (IO.userError "FAIL: int64_from_int_33_0")
#eval do
  if ( int64FromInt32 (( 1 :  Int))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int64_from_int_32_1"
  else throw (IO.userError "FAIL: int64_from_int_32_1")
#eval do
  if ( int64FromInt32 (( 123 :  Int))  == ( 123 :  Int) : Bool)
  then IO.println "PASS: int64_from_int_32_2"
  else throw (IO.userError "FAIL: int64_from_int_32_2")
#eval do
  if ( int64FromInt32  ((Int.neg  (( 0 :  Int))))  ==  (Int.neg  (( 0 :  Int))) : Bool)
  then IO.println "PASS: int64_from_int_32_3"
  else throw (IO.userError "FAIL: int64_from_int_32_3")
#eval do
  if ( int64FromInt32  ((Int.neg  (( 1 :  Int))))  ==  (Int.neg  (( 1 :  Int))) : Bool)
  then IO.println "PASS: int64_from_int_32_4"
  else throw (IO.userError "FAIL: int64_from_int_32_4")
#eval do
  if ( int64FromInt32  ((Int.neg  (( 123 :  Int))))  ==  (Int.neg  (( 123 :  Int))) : Bool)
  then IO.println "PASS: int64_from_int_32_5"
  else throw (IO.userError "FAIL: int64_from_int_32_5")

#eval do
  if (   (Int.natAbs (( 0 :  Int)))  ==   0 : Bool)
  then IO.println "PASS: natural_from_int_0"
  else throw (IO.userError "FAIL: natural_from_int_0")
#eval do
  if (   (Int.natAbs (( 1 :  Int)))  ==   1 : Bool)
  then IO.println "PASS: natural_from_int_1"
  else throw (IO.userError "FAIL: natural_from_int_1")
#eval do
  if (   (Int.natAbs  ((Int.neg  (( 2 :  Int)))))  ==   2 : Bool)
  then IO.println "PASS: natural_from_int_2"
  else throw (IO.userError "FAIL: natural_from_int_2")
#eval do
  if ( Int.natAbs  ( (( 0 :  Int)))  ==   0 : Bool)
  then IO.println "PASS: natural_from_int32_0"
  else throw (IO.userError "FAIL: natural_from_int32_0")
#eval do
  if ( Int.natAbs  ( (( 1 :  Int)))  ==   1 : Bool)
  then IO.println "PASS: natural_from_int32_1"
  else throw (IO.userError "FAIL: natural_from_int32_1")
#eval do
  if ( Int.natAbs  (  ((Int.neg  (( 2 :  Int)))))  ==   2 : Bool)
  then IO.println "PASS: natural_from_int32_2"
  else throw (IO.userError "FAIL: natural_from_int32_2")
#eval do
  if ( Int.natAbs  ( (( 0 :  Int)))  ==   0 : Bool)
  then IO.println "PASS: natural_from_int64_0"
  else throw (IO.userError "FAIL: natural_from_int64_0")
#eval do
  if ( Int.natAbs  ( (( 1 :  Int)))  ==   1 : Bool)
  then IO.println "PASS: natural_from_int64_1"
  else throw (IO.userError "FAIL: natural_from_int64_1")
#eval do
  if ( Int.natAbs  (  ((Int.neg  (( 2 :  Int)))))  ==   2 : Bool)
  then IO.println "PASS: natural_from_int64_2"
  else throw (IO.userError "FAIL: natural_from_int64_2")

#eval do
  if ( Int.ofNat  ( (  0))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int_from_natural_0"
  else throw (IO.userError "FAIL: int_from_natural_0")
#eval do
  if ( Int.ofNat  ( (  1))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int_from_natural_1"
  else throw (IO.userError "FAIL: int_from_natural_1")
#eval do
  if ( Int.ofNat  ( (  122))  == ( 122 :  Int) : Bool)
  then IO.println "PASS: int_from_natural_2"
  else throw (IO.userError "FAIL: int_from_natural_2")
#eval do
  if (   ( (( 0 :  Int)))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int_from_int32_0"
  else throw (IO.userError "FAIL: int_from_int32_0")
#eval do
  if (   ( (( 1 :  Int)))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int_from_int32_1"
  else throw (IO.userError "FAIL: int_from_int32_1")
#eval do
  if (   (  ((Int.neg  (( 2 :  Int)))))  ==  ((Int.neg  (( 2 :  Int)))) : Bool)
  then IO.println "PASS: int_from_int32_2"
  else throw (IO.userError "FAIL: int_from_int32_2")
#eval do
  if (   ( (( 0 :  Int)))  == ( 0 :  Int) : Bool)
  then IO.println "PASS: int_from_int64_0"
  else throw (IO.userError "FAIL: int_from_int64_0")
#eval do
  if (   ( (( 1 :  Int)))  == ( 1 :  Int) : Bool)
  then IO.println "PASS: int_from_int64_1"
  else throw (IO.userError "FAIL: int_from_int64_1")
#eval do
  if (   (  ((Int.neg  (( 2 :  Int)))))  ==  ((Int.neg  (( 2 :  Int)))) : Bool)
  then IO.println "PASS: int_from_int64_2"
  else throw (IO.userError "FAIL: int_from_int64_2")

#eval do
  if ( Int.natAbs  ( (( 0 :  Int)))  ==   0 : Bool)
  then IO.println "PASS: nat_from_integer_0"
  else throw (IO.userError "FAIL: nat_from_integer_0")
#eval do
  if ( Int.natAbs  ( (( 1 :  Int)))  ==   1 : Bool)
  then IO.println "PASS: nat_from_integer_1"
  else throw (IO.userError "FAIL: nat_from_integer_1")
#eval do
  if ( Int.natAbs  ( (( 122 :  Int)))  ==   122 : Bool)
  then IO.println "PASS: nat_from_integer_2"
  else throw (IO.userError "FAIL: nat_from_integer_2")
#eval do
  if ( Int.natAbs  (  ( (( 0 :  Int))))  ==   0 : Bool)
  then IO.println "PASS: nat_from_int32_0"
  else throw (IO.userError "FAIL: nat_from_int32_0")
#eval do
  if ( Int.natAbs  (  ( (( 1 :  Int))))  ==   1 : Bool)
  then IO.println "PASS: nat_from_int32_1"
  else throw (IO.userError "FAIL: nat_from_int32_1")
#eval do
  if ( Int.natAbs  (  (  ((Int.neg  (( 2 :  Int))))))  ==   2 : Bool)
  then IO.println "PASS: nat_from_int32_2"
  else throw (IO.userError "FAIL: nat_from_int32_2")
#eval do
  if ( Int.natAbs  (  ( (( 0 :  Int))))  ==   0 : Bool)
  then IO.println "PASS: nat_from_int64_0"
  else throw (IO.userError "FAIL: nat_from_int64_0")
#eval do
  if ( Int.natAbs  (  ( (( 1 :  Int))))  ==   1 : Bool)
  then IO.println "PASS: nat_from_int64_1"
  else throw (IO.userError "FAIL: nat_from_int64_1")
#eval do
  if ( Int.natAbs  (  (  ((Int.neg  (( 2 :  Int))))))  ==   2 : Bool)
  then IO.println "PASS: nat_from_int64_2"
  else throw (IO.userError "FAIL: nat_from_int64_2")
