/- Generated by Lem from relation.lem. -/

import LemLib
import Relation



/- 
instance forall 'a 'b. SetType 'a, SetType 'b => (Eq (rel 'a 'b))
  let (=) = relEq
end
 -/

theorem  relToSet_inv : ( (∀  r, ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (r)  r) : Prop)) : Prop) := by decide

#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)])  (relFromPred  (setFromList [  2,   3])  (setFromList [  1,   2,   3,   4,   5,   6])  (fun (x : Nat) (y : Nat) =>  y  ==  (x  +   1)))) : Bool)
  then IO.println "PASS: rel_basic_0"
  else throw (IO.userError "FAIL: rel_basic_0")
#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)]))  (setFromList [(  2,  3),  (  3,  4)])) : Bool)
  then IO.println "PASS: rel_basic_1"
  else throw (IO.userError "FAIL: rel_basic_1")
#eval do
  if ( relToPred  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)])) (  2) (  3) : Bool)
  then IO.println "PASS: rel_basic_2"
  else throw (IO.userError "FAIL: rel_basic_2")

theorem  inRel_set  : ( (∀  s  a  b, ( (setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  (s))  ==  ( (setMemberBy  (pairCompare  setElemCompare  setElemCompare) (a, b)  s)) : Prop)) : Prop) := by decide
theorem  inRel_pred  : ( (∀  p  a  b  sa  sb, ( ((setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  (relFromPred  sa  sb  p))  ==  p  a  b)  &&  ((setMemberBy  setElemCompare  a  sa)  &&  (setMemberBy  setElemCompare  b  sb)) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare) (  2,  3)  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  4,  5)])))) : Bool)
  then IO.println "PASS: in_rel_0"
  else throw (IO.userError "FAIL: in_rel_0")
#eval do
  if ( ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare) (  4,  5)  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  4,  5)])))) : Bool)
  then IO.println "PASS: in_rel_1"
  else throw (IO.userError "FAIL: in_rel_1")
#eval do
  if ( not  ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare) (  3,  2)  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  4,  5)])))) : Bool)
  then IO.println "PASS: in_rel_2"
  else throw (IO.userError "FAIL: in_rel_2")
#eval do
  if ( not  ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare) (  7,  4)  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  4,  5)])))) : Bool)
  then IO.println "PASS: in_rel_3"
  else throw (IO.userError "FAIL: in_rel_3")

#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  ( (setEmpty))  ((setEmpty) :  List  ((Nat  × Nat)))) : Bool)
  then IO.println "PASS: relEmpty_0"
  else throw (IO.userError "FAIL: relEmpty_0")
#eval do
  if ( not  ( (setMemberBy  (pairCompare  boolCompare  defaultCompare) (true, (  2 :Nat))  ( (setEmpty)))) : Bool)
  then IO.println "PASS: relEmpty_1"
  else throw (IO.userError "FAIL: relEmpty_1")

#eval do
  if ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare)  ((  2 :  Nat), (  3 :  Nat))  ((setAdd  (  2,  3)  (( (setEmpty)))))) : Bool)
  then IO.println "PASS: relAdd_0"
  else throw (IO.userError "FAIL: relAdd_0")
#eval do
  if ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare)  ((  4 :  Nat), (  5 :  Nat))  ((setAdd  (  2,  3)  (((setAdd  (  4,  5)  (( (setEmpty))))))))) : Bool)
  then IO.println "PASS: relAdd_1"
  else throw (IO.userError "FAIL: relAdd_1")
#eval do
  if ( not  ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare) ((  2 :  Nat), (  5 :  Nat))  ((setAdd  (  2,  3)  (((setAdd  (  4,  5)  (( (setEmpty)))))))))) : Bool)
  then IO.println "PASS: relAdd_2"
  else throw (IO.userError "FAIL: relAdd_2")
#eval do
  if ( not  ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare) ((  4 :  Nat), (  9 :  Nat))  ((setAdd  (  2,  3)  (((setAdd  (  4,  5)  (( (setEmpty)))))))))) : Bool)
  then IO.println "PASS: relAdd_3"
  else throw (IO.userError "FAIL: relAdd_3")

theorem  in_relAdd : ( (∀  a  b  a'  b'  r, ( ((setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  ((setAdd  (a',b')  (r))))  == 
  ((a  ==  a')  &&  (b  ==  b')))  ||  (setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  r) : Prop)) : Prop) := by decide

theorem  relId_spec : ( (∀  x  y  s, ( ( (setMemberBy  (pairCompare  setElemCompare  setElemCompare) (x, y)  (relIdOn  s))  ==  ( (setMemberBy  setElemCompare x  s)  &&  (x  ==  y))) : Prop)) : Prop) := by decide

#eval do
  if ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare)  ((  0 :Nat),  0)  (relIdOn  (setFromList [  0,   1,   2,   3]))) : Bool)
  then IO.println "PASS: rel_id_0"
  else throw (IO.userError "FAIL: rel_id_0")
#eval do
  if ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare)  ((  2 :Nat),  2)  (relIdOn  (setFromList [  0,   1,   2,   3]))) : Bool)
  then IO.println "PASS: rel_id_1"
  else throw (IO.userError "FAIL: rel_id_1")
#eval do
  if ( not  ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare) ((  5 :Nat),  5)  (relIdOn  (setFromList [  0,   1,   2,   3])))) : Bool)
  then IO.println "PASS: rel_id_2"
  else throw (IO.userError "FAIL: rel_id_2")
#eval do
  if ( not  ( (setMemberBy  (pairCompare  defaultCompare  defaultCompare) ((  0 :Nat),  2)  (relIdOn  (setFromList [  0,   1,   2,   3])))) : Bool)
  then IO.println "PASS: rel_id_3"
  else throw (IO.userError "FAIL: rel_id_3")

theorem  in_rel_union : ( (∀  a  b  r1  r2, ( ((setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  (( (setUnionBy  (pairCompare  setElemCompare  setElemCompare) (r1)  (r2)))))  ==  (setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  r1))  ||  (setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  r2) : Prop)) : Prop) := by decide
#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  boolCompare)  ( (setUnionBy  (pairCompare  defaultCompare  boolCompare) (((setAdd  ((  2 :Nat),true)  (( (setEmpty))))))  (((setAdd  (  5,false)  (( (setEmpty)))))))) 
                    (setFromList [(  5,false),  (  2,true)])) : Bool)
  then IO.println "PASS: rel_union_0"
  else throw (IO.userError "FAIL: rel_union_0")

theorem  in_rel_inter : ( (∀  a  b  r1  r2, ( ((setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  (( (setInterBy  (pairCompare  setElemCompare  setElemCompare) (r1)  (r2)))))  ==  (setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  r1))  &&  (setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (a, b)  r2) : Prop)) : Prop) := by decide
#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  boolCompare)  ( (setInterBy  (pairCompare  defaultCompare  boolCompare) (((setAdd  ((  2 :Nat),true)  (((setAdd  (  7,false)  (( (setEmpty)))))))))  (((setAdd  (  7,false)  (((setAdd  (  2,false)  (( (setEmpty))))))))))) 
                    (setFromList [(  7,false)])) : Bool)
  then IO.println "PASS: rel_inter_0"
  else throw (IO.userError "FAIL: rel_inter_0")

theorem  rel_comp_1  : ( (∀  r1  r2  e1  e2  e3, ( ((not  ( (setMemberBy  (pairCompare  setElemCompare  setElemCompare) (e1, e2)  r1)  &&  (setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (e2, e3)  r2)))  ||  (setMemberBy  (pairCompare  setElemCompare  setElemCompare)  (e1, e3)  (relComp  r1  r2))) : Prop)) : Prop) := by decide
theorem  rel_comp_3  : ( (∀  r, ( ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare) (relComp  r  ( (setEmpty)))  ( (setEmpty))))  &&  ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare) (relComp  ( (setEmpty))  r)  ( (setEmpty)))) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare) (relComp  ((setFromList [((  2 :Nat), (  4 :Nat)),  (  2,  8)]))  ((setFromList [(  4, (  3 :Nat)),  (  2,  8)])))  
                    (setFromList [(  2,  3)]))) : Bool)
  then IO.println "PASS: rel_comp_0"
  else throw (IO.userError "FAIL: rel_comp_0")


#eval do
  if ( ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare) (relRestrict  ((setFromList [((  2 :Nat), (  4 :Nat)),  (  2,  2),  (  2,  8)]))  (setFromList [  2,   8]))  
                    (setFromList [(  2,  8),  (  2,  2)]))) : Bool)
  then IO.println "PASS: rel_restrict_0"
  else throw (IO.userError "FAIL: rel_restrict_0")

theorem  rel_restrict_empty : ( (∀  r, ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (relRestrict  r  (setEmpty))  ( (setEmpty))) : Prop)) : Prop) := by decide
theorem  rel_restrict_rel_empty : ( (∀  s, ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (relRestrict  ( (setEmpty))  s)  ( (setEmpty))) : Prop)) : Prop) := by decide
theorem  rel_restrict_rel_add : ( (∀  r  x  y  s, ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (relRestrict  ((setAdd  (x,y)  (r)))  s)  
  (if  (( (setMemberBy  setElemCompare x  s))  &&  ( (setMemberBy  setElemCompare y  s))) then  (setAdd  (x,y)  ((relRestrict  r  s)))  else  relRestrict  r  s)) : Prop)) : Prop) := by decide

#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (relConverse  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)]))) 
                       (setFromList [(  3,  2),  (  4,  3),  (  5,  4)])) : Bool)
  then IO.println "PASS: rel_converse_0"
  else throw (IO.userError "FAIL: rel_converse_0")
theorem  rel_converse_empty  : ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (relConverse  ( (setEmpty)))  ( (setEmpty))) : Prop) := by decide
theorem  rel_converse_add  : (∀  x  y  r, ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (relConverse  ((setAdd  (x,y)  (r))))  (setAdd  (y,x)  ((relConverse  r)))) : Prop) : Prop) := by decide
theorem  rel_converse_converse  : (∀  r, ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (relConverse  (relConverse  r))  r) : Prop) : Prop) := by decide

#eval do
  if ( (setEqualBy  defaultCompare  (relDomain  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: rel_domain_0"
  else throw (IO.userError "FAIL: rel_domain_0")
#eval do
  if ( (setEqualBy  defaultCompare  (relDomain  ((setFromList [((  5 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))  (setFromList [  3,   4,   5])) : Bool)
  then IO.println "PASS: rel_domain_1"
  else throw (IO.userError "FAIL: rel_domain_1")
#eval do
  if ( (setEqualBy  defaultCompare  (relDomain  ((setFromList [((  3 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))  (setFromList [  3,   4])) : Bool)
  then IO.println "PASS: rel_domain_2"
  else throw (IO.userError "FAIL: rel_domain_2")

#eval do
  if ( (setEqualBy  defaultCompare  (relRange  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))  (setFromList [  3,   4,   5])) : Bool)
  then IO.println "PASS: rel_range_0"
  else throw (IO.userError "FAIL: rel_range_0")
#eval do
  if ( (setEqualBy  defaultCompare  (relRange  ((setFromList [((  5 :Nat), (  6 :Nat)),  (  3,  4),  (  4,  5)])))  (setFromList [  4,   5,   6])) : Bool)
  then IO.println "PASS: rel_range_1"
  else throw (IO.userError "FAIL: rel_range_1")
#eval do
  if ( (setEqualBy  defaultCompare  (relRange  ((setFromList [((  3 :Nat), (  5 :Nat)),  (  3,  4),  (  4,  5)])))  (setFromList [  4,   5])) : Bool)
  then IO.println "PASS: rel_range_2"
  else throw (IO.userError "FAIL: rel_range_2")

#eval do
  if ( (setEqualBy  defaultCompare  ( (setUnionBy  defaultCompare (relDomain  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))  (relRange  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))))  (setFromList [  2,   3,   4,   5])) : Bool)
  then IO.println "PASS: rel_field_0"
  else throw (IO.userError "FAIL: rel_field_0")
#eval do
  if ( (setEqualBy  defaultCompare  ( (setUnionBy  defaultCompare (relDomain  ((setFromList [((  5 :Nat), (  6 :Nat)),  (  3,  4),  (  4,  5)])))  (relRange  ((setFromList [((  5 :Nat), (  6 :Nat)),  (  3,  4),  (  4,  5)])))))  (setFromList [  3,   4,   5,   6])) : Bool)
  then IO.println "PASS: rel_field_1"
  else throw (IO.userError "FAIL: rel_field_1")
#eval do
  if ( (setEqualBy  defaultCompare  ( (setUnionBy  defaultCompare (relDomain  ((setFromList [((  3 :Nat), (  5 :Nat)),  (  3,  4),  (  4,  5)])))  (relRange  ((setFromList [((  3 :Nat), (  5 :Nat)),  (  3,  4),  (  4,  5)])))))  (setFromList [  3,   4,   5])) : Bool)
  then IO.println "PASS: rel_field_2"
  else throw (IO.userError "FAIL: rel_field_2")

#eval do
  if ( relOver  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)]))  (setFromList [  2,   3,   4,   5]) : Bool)
  then IO.println "PASS: rel_over_0"
  else throw (IO.userError "FAIL: rel_over_0")
#eval do
  if ( not  (relOver  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)]))  (setFromList [  3,   4,   5])) : Bool)
  then IO.println "PASS: rel_over_1"
  else throw (IO.userError "FAIL: rel_over_1")

theorem  rel_over_empty : (∀  s, ( relOver  ( (setEmpty))  s : Prop) : Prop) := by decide
theorem  rel_over_add : (∀  x  y  s  r, ( relOver  ((setAdd  (x,y)  (r)))  s  ==  ( (setMemberBy  setElemCompare x  s)  &&  ((setMemberBy  setElemCompare  y  s)  &&  relOver  r  s)) : Prop) : Prop) := by decide

#eval do
  if ( (setEqualBy  defaultCompare  (relApply  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)]))  (setFromList [  2,   3]))  (setFromList [  3,   4])) : Bool)
  then IO.println "PASS: rel_apply_0"
  else throw (IO.userError "FAIL: rel_apply_0")
#eval do
  if ( (setEqualBy  defaultCompare  (relApply  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  7),  (  3,  5)]))  (setFromList [  2,   3]))  (setFromList [  3,   5,   7])) : Bool)
  then IO.println "PASS: rel_apply_1"
  else throw (IO.userError "FAIL: rel_apply_1")

theorem  rel_apply_empty_set : (∀  r, ( (setEqualBy  setElemCompare  (relApply  r  (setEmpty))  (setEmpty)) : Prop) : Prop) := by decide
theorem  rel_apply_empty : (∀  s, ( (setEqualBy  setElemCompare  (relApply  ( (setEmpty))  s)  (setEmpty)) : Prop) : Prop) := by decide
theorem  rel_apply_add : (∀  x  y  s  r, ( (setEqualBy  setElemCompare  (relApply  ((setAdd  (x,y)  (r)))  s)  (if  ( (setMemberBy  setElemCompare x  s)) then  (setAdd  y  (relApply  r  s))  else  relApply  r  s)) : Prop) : Prop) := by decide

theorem  is_subrel_empty  : (∀  r, ( (setSubsetBy  (pairCompare  setElemCompare  setElemCompare)  (( (setEmpty)))  (r)) : Prop) : Prop) := by decide
theorem  is_subrel_empty2  : (∀  r, ( (setSubsetBy  (pairCompare  setElemCompare  setElemCompare)  (r)  (( (setEmpty))))  ==  ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare) r  ( (setEmpty)))) : Prop) : Prop) := by decide
theorem  is_subrel_add  : (∀  x  y  r1  r2, ( (setSubsetBy  (pairCompare  setElemCompare  setElemCompare)  (((setAdd  (x,y)  (r1))))  (r2))  ==  ( (setMemberBy  (pairCompare  setElemCompare  setElemCompare) (x, y)  r2)  &&  (setSubsetBy  (pairCompare  setElemCompare  setElemCompare)  (r1)  (r2))) : Prop) : Prop) := by decide

#eval do
  if ( (setSubsetBy  (pairCompare  defaultCompare  defaultCompare)  (( (setEmpty)))  (((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))) : Bool)
  then IO.println "PASS: is_subrel_0"
  else throw (IO.userError "FAIL: is_subrel_0")
#eval do
  if ( (setSubsetBy  (pairCompare  defaultCompare  defaultCompare)  (((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))  (((setFromList [(  2,  3),  (  3,  4),  (  4,  5)])))) : Bool)
  then IO.println "PASS: is_subrel_1"
  else throw (IO.userError "FAIL: is_subrel_1")
#eval do
  if ( (setSubsetBy  (pairCompare  defaultCompare  defaultCompare)  (((setFromList [((  2 :Nat), (  3 :Nat)),  (  4,  5)])))  (((setFromList [(  2,  3),  (  3,  4),  (  4,  5)])))) : Bool)
  then IO.println "PASS: is_subrel_2"
  else throw (IO.userError "FAIL: is_subrel_2")
#eval do
  if ( not  ((setSubsetBy  (pairCompare  defaultCompare  defaultCompare)  (((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])))  (((setFromList [(  2,  3),  (  4,  5)]))))) : Bool)
  then IO.println "PASS: is_subrel_3"
  else throw (IO.userError "FAIL: is_subrel_3")

#eval do
  if ( isReflexiveOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))  (setFromList [  2,   3]) : Bool)
  then IO.println "PASS: is_reflexive_on_0"
  else throw (IO.userError "FAIL: is_reflexive_on_0")
#eval do
  if ( not  (isReflexiveOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))  (setFromList [  2,   4,   3])) : Bool)
  then IO.println "PASS: is_reflexive_on_1"
  else throw (IO.userError "FAIL: is_reflexive_on_1")
#eval do
  if ( not  (isReflexiveOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))  (setFromList [  5,   2])) : Bool)
  then IO.println "PASS: is_reflexive_on_2"
  else throw (IO.userError "FAIL: is_reflexive_on_2")

#eval do
  if ( isIrreflexiveOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))  (setFromList [  4]) : Bool)
  then IO.println "PASS: is_irreflexive_on_0"
  else throw (IO.userError "FAIL: is_irreflexive_on_0")
#eval do
  if ( not  (isIrreflexiveOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))  (setFromList [  2,   4])) : Bool)
  then IO.println "PASS: is_irreflexive_on_1"
  else throw (IO.userError "FAIL: is_irreflexive_on_1")
#eval do
  if ( not  (isIrreflexiveOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))  (setFromList [  5,   2])) : Bool)
  then IO.println "PASS: is_irreflexive_on_2"
  else throw (IO.userError "FAIL: is_irreflexive_on_2")
#eval do
  if ( isIrreflexiveOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))  (setFromList [  5,   4]) : Bool)
  then IO.println "PASS: is_irreflexive_on_3"
  else throw (IO.userError "FAIL: is_irreflexive_on_3")

#eval do
  if ( not  (isIrreflexive  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))) : Bool)
  then IO.println "PASS: is_irreflexive_0"
  else throw (IO.userError "FAIL: is_irreflexive_0")
#eval do
  if ( isIrreflexive  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5)])) : Bool)
  then IO.println "PASS: is_irreflexive_1"
  else throw (IO.userError "FAIL: is_irreflexive_1")

#eval do
  if ( isSymmetricOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5),  (  5,  4)]))  (setFromList [  4]) : Bool)
  then IO.println "PASS: is_symmetric_on_0"
  else throw (IO.userError "FAIL: is_symmetric_on_0")
#eval do
  if ( isSymmetricOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5),  (  5,  4)]))  (setFromList [  3]) : Bool)
  then IO.println "PASS: is_symmetric_on_1"
  else throw (IO.userError "FAIL: is_symmetric_on_1")
#eval do
  if ( not  (isSymmetricOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5),  (  5,  4)]))  (setFromList [  3,   4])) : Bool)
  then IO.println "PASS: is_symmetric_on_2"
  else throw (IO.userError "FAIL: is_symmetric_on_2")

#eval do
  if ( not  (isSymmetric  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))) : Bool)
  then IO.println "PASS: is_symmetric_0"
  else throw (IO.userError "FAIL: is_symmetric_0")
#eval do
  if ( isSymmetric  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2),  (  4,  5),  (  5,  4)])) : Bool)
  then IO.println "PASS: is_symmetric_1"
  else throw (IO.userError "FAIL: is_symmetric_1")

theorem  is_symmetric_empty  : (∀  r, ( isSymmetricOn  r  (setEmpty) : Prop) : Prop) := by decide
theorem  is_symmetric_sing  : (∀  r  x, ( isSymmetricOn  r  (setFromList [x]) : Prop) : Prop) := by decide

#eval do
  if ( isAntisymmetricOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5),  (  5,  4)]))  (setFromList [  3,   4]) : Bool)
  then IO.println "PASS: is_antisymmetric_on_0"
  else throw (IO.userError "FAIL: is_antisymmetric_on_0")
#eval do
  if ( not  (isAntisymmetricOn  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5),  (  5,  4)]))  (setFromList [  4,   5])) : Bool)
  then IO.println "PASS: is_antisymmetric_on_1"
  else throw (IO.userError "FAIL: is_antisymmetric_on_1")

#eval do
  if ( isAntisymmetric  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)])) : Bool)
  then IO.println "PASS: is_antisymmetric_0"
  else throw (IO.userError "FAIL: is_antisymmetric_0")
#eval do
  if ( not  (isAntisymmetric  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2),  (  4,  5),  (  2,  4)]))) : Bool)
  then IO.println "PASS: is_antisymmetric_1"
  else throw (IO.userError "FAIL: is_antisymmetric_1")

theorem  is_antisymmetric_empty  : (∀  r, ( isAntisymmetricOn  r  (setEmpty) : Prop) : Prop) := by decide
theorem  is_antisymmetric_sing  : (∀  r  x, ( isAntisymmetricOn  r  (setFromList [x]) : Prop) : Prop) := by decide

#eval do
  if ( isTransitiveOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  2,  4),  (  4,  5),  (  5,  4)]))  (setFromList [  2,   3,   4]) : Bool)
  then IO.println "PASS: is_transitive_on_0"
  else throw (IO.userError "FAIL: is_transitive_on_0")
#eval do
  if ( not  (isTransitiveOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  2,  4),  (  4,  5),  (  5,  4)]))  (setFromList [  2,   3,   4,   5])) : Bool)
  then IO.println "PASS: is_transitive_on_1"
  else throw (IO.userError "FAIL: is_transitive_on_1")

#eval do
  if ( not  (isTransitive  ((setFromList [((  2 :Nat), (  2 :Nat)),  (  3,  3),  (  3,  4),  (  4,  5)]))) : Bool)
  then IO.println "PASS: is_transitive_0"
  else throw (IO.userError "FAIL: is_transitive_0")
#eval do
  if ( isTransitive  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  2,  4)]) ) : Bool)
  then IO.println "PASS: is_transitive_1"
  else throw (IO.userError "FAIL: is_transitive_1")


#eval do
  if ( isTotalOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  3,  3),  (  4,  4)]))  (setFromList [  3,   4]) : Bool)
  then IO.println "PASS: is_total_on_0"
  else throw (IO.userError "FAIL: is_total_on_0")
#eval do
  if ( not  (isTotalOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  3,  3),  (  4,  4)]))  (setFromList [  2,   4])) : Bool)
  then IO.println "PASS: is_total_on_1"
  else throw (IO.userError "FAIL: is_total_on_1")

#eval do
  if ( isTrichotomousOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)]))  (setFromList [  3,   4]) : Bool)
  then IO.println "PASS: is_trichotomous_on_0"
  else throw (IO.userError "FAIL: is_trichotomous_on_0")
#eval do
  if ( not  (isTrichotomousOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_trichotomous_on_1"
  else throw (IO.userError "FAIL: is_trichotomous_on_1")

#eval do
  if ( isSingleValued  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)])) : Bool)
  then IO.println "PASS: is_single_valued_0"
  else throw (IO.userError "FAIL: is_single_valued_0") 
#eval do
  if ( not  (isSingleValued  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  2,  4) ,  (  3,  4)]))) : Bool)
  then IO.println "PASS: is_single_valued_1"
  else throw (IO.userError "FAIL: is_single_valued_1")


#eval do
  if ( isEquivalenceOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2),  (  2,  2),  (  3,  3),  (  4,  4)]))  (setFromList [  2,   3,   4]) : Bool)
  then IO.println "PASS: is_equivalence_0"
  else throw (IO.userError "FAIL: is_equivalence_0")
#eval do
  if ( not  (isEquivalenceOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2),  (  2,  4),  (  2,  2),  (  3,  3),  (  4,  4)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_equivalence_1"
  else throw (IO.userError "FAIL: is_equivalence_1")
#eval do
  if ( not  (isEquivalenceOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2),  (  2,  2),  (  3,  3)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_equivalence_2"
  else throw (IO.userError "FAIL: is_equivalence_2")

#eval do
  if ( isPreorderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2),  (  2,  2),  (  3,  3),  (  4,  4)]))  (setFromList [  2,   3,   4]) : Bool)
  then IO.println "PASS: is_preorder_0"
  else throw (IO.userError "FAIL: is_preorder_0")
#eval do
  if ( not  (isPreorderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  2,  2),  (  3,  3)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_preorder_1"
  else throw (IO.userError "FAIL: is_preorder_1")
#eval do
  if ( not  (isPreorderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  2,  2),  (  3,  3),  (  4,  4)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_preorder_2"
  else throw (IO.userError "FAIL: is_preorder_2")

#eval do
  if ( isPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  2,  2),  (  3,  3),  (  4,  4)]))  (setFromList [  2,   3,   4]) : Bool)
  then IO.println "PASS: is_partialorder_0"
  else throw (IO.userError "FAIL: is_partialorder_0")
#eval do
  if ( not  (isPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2),  (  2,  2),  (  3,  3),  (  4,  4)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_partialorder_1"
  else throw (IO.userError "FAIL: is_partialorder_1")
#eval do
  if ( not  (isPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  2,  2),  (  3,  3)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_partialorder_2"
  else throw (IO.userError "FAIL: is_partialorder_2")
#eval do
  if ( not  (isPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  2,  2),  (  3,  3),  (  4,  4)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_partialorder_3"
  else throw (IO.userError "FAIL: is_partialorder_3")

theorem  isStrictPartialOrderOn_antisym  : ( (∀  r  s, ( ((not  (isStrictPartialOrderOn  r  s))  ||  isAntisymmetricOn  r  s) : Prop)) : Prop) := by decide

#eval do
  if ( isStrictPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat))]))  (setFromList [  2,   3,   4]) : Bool)
  then IO.println "PASS: is_strict_partialorder_on_0"
  else throw (IO.userError "FAIL: is_strict_partialorder_on_0")
#eval do
  if ( isStrictPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  2,  4)]))  (setFromList [  2,   3,   4]) : Bool)
  then IO.println "PASS: is_strict_partialorder_on_1"
  else throw (IO.userError "FAIL: is_strict_partialorder_on_1")
#eval do
  if ( not  (isStrictPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_strict_partialorder_on_2"
  else throw (IO.userError "FAIL: is_strict_partialorder_on_2")
#eval do
  if ( not  (isStrictPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_strict_partialorder_on_3"
  else throw (IO.userError "FAIL: is_strict_partialorder_on_3")
#eval do
  if ( not  (isStrictPartialOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  2,  2)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_strict_partialorder_on_4"
  else throw (IO.userError "FAIL: is_strict_partialorder_on_4")

#eval do
  if ( isStrictPartialOrder  ((setFromList [((  2 :Nat), (  3 :Nat))])) : Bool)
  then IO.println "PASS: is_strict_partialorder_0"
  else throw (IO.userError "FAIL: is_strict_partialorder_0")
#eval do
  if ( isStrictPartialOrder  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  2,  4)])) : Bool)
  then IO.println "PASS: is_strict_partialorder_1"
  else throw (IO.userError "FAIL: is_strict_partialorder_1") 
#eval do
  if ( not  (isStrictPartialOrder  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)]))) : Bool)
  then IO.println "PASS: is_strict_partialorder_2"
  else throw (IO.userError "FAIL: is_strict_partialorder_2")
#eval do
  if ( not  (isStrictPartialOrder  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  2)]))) : Bool)
  then IO.println "PASS: is_strict_partialorder_3"
  else throw (IO.userError "FAIL: is_strict_partialorder_3")
#eval do
  if ( not  (isStrictPartialOrder  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  2,  2)]))) : Bool)
  then IO.println "PASS: is_strict_partialorder_4"
  else throw (IO.userError "FAIL: is_strict_partialorder_4")


#eval do
  if ( isTotalOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)), (  2,  2), (  3,  3), (  4,  4)]))  (setFromList [  2,   3]) : Bool)
  then IO.println "PASS: is_totalorder_on_0"
  else throw (IO.userError "FAIL: is_totalorder_on_0")
#eval do
  if ( not  (isTotalOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat)), (  2,  2), (  3,  3), (  4,  4)]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_totalorder_on_1"
  else throw (IO.userError "FAIL: is_totalorder_on_1")
#eval do
  if ( not  (isTotalOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat))]))  (setFromList [  2,   3])) : Bool)
  then IO.println "PASS: is_totalorder_on_2"
  else throw (IO.userError "FAIL: is_totalorder_on_2")

#eval do
  if ( isStrictTotalOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat))]))  (setFromList [  2,   3]) : Bool)
  then IO.println "PASS: is_strict_totalorder_on_0"
  else throw (IO.userError "FAIL: is_strict_totalorder_on_0")
#eval do
  if ( not  (isStrictTotalOrderOn  ((setFromList [((  2 :Nat), (  3 :Nat))]))  (setFromList [  2,   3,   4])) : Bool)
  then IO.println "PASS: is_strict_totalorder_on_1"
  else throw (IO.userError "FAIL: is_strict_totalorder_on_1")


theorem  transitiveClosure_spec1 : ( (∀  r, ( (setSubsetBy  (pairCompare  setElemCompare  setElemCompare)  (r)  (((set_tc  (fun x y => x == y)  r)))) : Prop)) : Prop) := by decide
theorem  transitiveClosure_spec2 : ( (∀  r, ( isTransitive  ((set_tc  (fun x y => x == y)  r)) : Prop)) : Prop) := by decide
theorem  transitiveClosure_spec3 : ( (∀  r1  r2, ( ((not  ((isTransitive  r2)  &&  ((setSubsetBy  (pairCompare  setElemCompare  setElemCompare)  (r1)  (r2)))))  ||  (setSubsetBy  (pairCompare  setElemCompare  setElemCompare)  (((set_tc  (fun x y => x == y)  r1)))  (r2))) : Prop)) : Prop) := by decide
theorem  transitiveClosure_spec4 : ( (∀  r, ( ((not  (isTransitive  r))  ||  ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare) (set_tc  (fun x y => x == y)  r)  r))) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare) (set_tc  (fun x y => x == y)  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)]))) 
                              (setFromList [(  2,  3),  (  2,  4),  (  3,  4)]))) : Bool)
  then IO.println "PASS: transitive_closure_0"
  else throw (IO.userError "FAIL: transitive_closure_0")
#eval do
  if ( ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare) (set_tc  (fun x y => x == y)  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4),  (  4,  5),  (  7,  9)]))) 
                              (setFromList [(  2,  3),  (  2,  4),  (  2,  5),  (  3,  4),  (  3,  5),  (  4,  5),  (  7,  9)]))) : Bool)
  then IO.println "PASS: transitive_closure_1"
  else throw (IO.userError "FAIL: transitive_closure_1")

theorem  transitive_closure_add_thm : (∀  x  y  r, ( ((not  (isTransitive  r))  ||  ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare) (transitiveClosureAdd  x  y  r)  (set_tc  (fun x y => x == y)  ((setAdd  (x,y)  (r))))))) : Prop) : Prop) := by decide

#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (transitiveClosureAdd  (  2 :Nat)  (  3 :Nat)  (setEmpty))  (setFromList [(  2,  3)])) : Bool)
  then IO.println "PASS: transitive_closure_add_0"
  else throw (IO.userError "FAIL: transitive_closure_add_0")
#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (transitiveClosureAdd  (  3 :Nat)  (  4 :Nat)  (setFromList [(  2,  3)]))  (setFromList [(  2,  3),  (  3,  4),  (  2,  4)])) : Bool)
  then IO.println "PASS: transitive_closure_add_1"
  else throw (IO.userError "FAIL: transitive_closure_add_1")
#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (transitiveClosureAdd  (  4 :Nat)  (  5 :Nat)  (setFromList [(  2,  3),  (  3,  4),  (  2,  4)]))  
                                 (setFromList [(  2,  3),  (  3,  4),  (  2,  4),  (  4,  5),  (  2,  5),  (  3,  5)])) : Bool)
  then IO.println "PASS: transitive_closure_add_2"
  else throw (IO.userError "FAIL: transitive_closure_add_2")

#eval do
  if ( ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare) (reflexiveTransitiveClosureOn  ((setFromList [((  2 :Nat), (  3 :Nat)),  (  3,  4)]))  (setFromList [  2,   3,   4])) 
                              (setFromList [(  2,  3),  (  2,  4),  (  3,  4),  (  2,  2),  (  3,  3),  (  4,  4)]))) : Bool)
  then IO.println "PASS: reflexive_transitive_closure_0"
  else throw (IO.userError "FAIL: reflexive_transitive_closure_0")

theorem  trancl_withoutTransitiveEdges_thm : (∀  r, ( ((not  true)  ||  (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (set_tc  (fun x y => x == y)  (withoutTransitiveEdges  r))  (set_tc  (fun x y => x == y)  r))) : Prop) : Prop) := by decide

#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (withoutTransitiveEdges  (setFromList [((  0 :Nat),  1)]))  (setFromList [((  0 :Nat),  1)])) : Bool)
  then IO.println "PASS: withoutTransitiveEdges_0"
  else throw (IO.userError "FAIL: withoutTransitiveEdges_0")
#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (withoutTransitiveEdges  (setFromList [((  0 :Nat),  1),  (  1,  2),  (  0,  2)]))  
                                 (setFromList [((  0 :Nat),  1),  (  1,  2)])) : Bool)
  then IO.println "PASS: withoutTransitiveEdges_1"
  else throw (IO.userError "FAIL: withoutTransitiveEdges_1")
#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (withoutTransitiveEdges  (setFromList [((  0 :Nat),  1),  (  1,  2),  (  2,  3),  (  0,  3)]))  
                                 (setFromList [((  0 :Nat),  1),  (  1,  2),  (  2,  3)])) : Bool)
  then IO.println "PASS: withoutTransitiveEdges_2"
  else throw (IO.userError "FAIL: withoutTransitiveEdges_2")
#eval do
  if ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare)  (withoutTransitiveEdges  (setFromList [((  0 :Nat),  0),  (  0,  1)]))  
                                 (setFromList [((  0 :Nat),  0),  (  0,  1)])) : Bool)
  then IO.println "PASS: withoutTransitiveEdges_3"
  else throw (IO.userError "FAIL: withoutTransitiveEdges_3")
