/- Generated by Lem from set.lem. -/

import LemLib
import Set



#eval do
  if ( (setEqualBy  boolCompare  (setEmpty :  List  Bool)  (setEmpty)) : Bool)
  then IO.println "PASS: empty_0"
  else throw (IO.userError "FAIL: empty_0")
#eval do
  if ( (setEqualBy  defaultCompare  (setEmpty :  List  Nat)  (setEmpty)) : Bool)
  then IO.println "PASS: empty_1"
  else throw (IO.userError "FAIL: empty_1")
#eval do
  if ( (setEqualBy  (lexicographicCompareBy  defaultCompare)  (setEmpty :  List  (List  Nat))  (setEmpty)) : Bool)
  then IO.println "PASS: empty_2"
  else throw (IO.userError "FAIL: empty_2")
#eval do
  if ( (setEqualBy  (setCompareBy  defaultCompare)  (setEmpty :  List  (List  Nat))  (setEmpty)) : Bool)
  then IO.println "PASS: empty_3"
  else throw (IO.userError "FAIL: empty_3")

#eval do
  if ( setAny  (fun  (x :Nat) =>  natGtb  x (  5))  (setFromList [  3,   4,   6]) : Bool)
  then IO.println "PASS: any_0"
  else throw (IO.userError "FAIL: any_0")
#eval do
  if ( not  (setAny  (fun  (x :Nat) =>  natGtb  x (  10))  (setFromList [  3,   4,   6])) : Bool)
  then IO.println "PASS: any_1"
  else throw (IO.userError "FAIL: any_1")

#eval do
  if ( setForAll  (fun  (x :Nat) =>  natGtb  x (  2))  (setFromList [  3,   4,   6]) : Bool)
  then IO.println "PASS: all_0"
  else throw (IO.userError "FAIL: all_0")
#eval do
  if ( not  (setForAll  (fun  (x :Nat) =>  natGtb  x (  2))  (setFromList [  3,   4,   6,   1])) : Bool)
  then IO.println "PASS: all_1"
  else throw (IO.userError "FAIL: all_1")

#eval do
  if ( ( (setMemberBy  defaultCompare (  1 :Nat)  (setFromList [(  2 :Nat),   3,   1]))) : Bool)
  then IO.println "PASS: in_1"
  else throw (IO.userError "FAIL: in_1")
#eval do
  if ( (not  ( (setMemberBy  defaultCompare (  1 :Nat)  (setFromList [  2,   3,   4])))) : Bool)
  then IO.println "PASS: in_2"
  else throw (IO.userError "FAIL: in_2")
#eval do
  if ( (not  ( (setMemberBy  defaultCompare (  1 :Nat)  (setEmpty)))) : Bool)
  then IO.println "PASS: in_3"
  else throw (IO.userError "FAIL: in_3")
#eval do
  if ( ( (setMemberBy  defaultCompare (  1 :Nat)  (setFromList [  1,   2,   1,   3,   1,   4]))) : Bool)
  then IO.println "PASS: in_4"
  else throw (IO.userError "FAIL: in_4")

#eval do
  if ( not  ( not  ( (setMemberBy  defaultCompare (  1 :Nat)  (setFromList [  2,   3,   1])))) : Bool)
  then IO.println "PASS: nin_1"
  else throw (IO.userError "FAIL: nin_1")
#eval do
  if ( ( not  ( (setMemberBy  defaultCompare (  1 :Nat)  (setFromList [  2,   3,   4])))) : Bool)
  then IO.println "PASS: nin_2"
  else throw (IO.userError "FAIL: nin_2")
#eval do
  if ( ( not  ( (setMemberBy  defaultCompare (  1 :Nat)  (setEmpty)))) : Bool)
  then IO.println "PASS: nin_3"
  else throw (IO.userError "FAIL: nin_3")
#eval do
  if ( not  ( not  ( (setMemberBy  defaultCompare (  1 :Nat)  (setFromList [  1,   2,   1,   3,   1,   4])))) : Bool)
  then IO.println "PASS: nin_4"
  else throw (IO.userError "FAIL: nin_4")

#eval do
  if ( (setIsEmpty  ((setEmpty) : List  Nat)) : Bool)
  then IO.println "PASS: null_1"
  else throw (IO.userError "FAIL: null_1")
#eval do
  if ( (not  (setIsEmpty  (setFromList [(  1 :Nat)]))) : Bool)
  then IO.println "PASS: null_2"
  else throw (IO.userError "FAIL: null_2")

#eval do
  if ( (setEqualBy  defaultCompare  (setSingleton  (  2 :Nat))  (setFromList [  2])) : Bool)
  then IO.println "PASS: singleton_1"
  else throw (IO.userError "FAIL: singleton_1")
#eval do
  if ( not  (setIsEmpty  (setSingleton  (  2 :Nat))) : Bool)
  then IO.println "PASS: singleton_2"
  else throw (IO.userError "FAIL: singleton_2")
#eval do
  if ( (setMemberBy  defaultCompare (  2)  (setSingleton  (  2 :Nat))) : Bool)
  then IO.println "PASS: singleton_3"
  else throw (IO.userError "FAIL: singleton_3")
#eval do
  if ( not  ( (setMemberBy  defaultCompare (  3)  (setSingleton  (  2 :Nat)))) : Bool)
  then IO.println "PASS: singleton_4"
  else throw (IO.userError "FAIL: singleton_4")

#eval do
  if ( (setCardinal  ((setEmpty) :List  Nat)  ==   0) : Bool)
  then IO.println "PASS: size_1"
  else throw (IO.userError "FAIL: size_1")
#eval do
  if ( (setCardinal  (setFromList [(  2 :Nat)])  ==   1) : Bool)
  then IO.println "PASS: size_2"
  else throw (IO.userError "FAIL: size_2")
#eval do
  if ( (setCardinal  (setFromList [(  1 :Nat),   1])  ==   1) : Bool)
  then IO.println "PASS: size_3"
  else throw (IO.userError "FAIL: size_3")
#eval do
  if ( (setCardinal  (setFromList [(  2 :Nat),   1,   3])  ==   3) : Bool)
  then IO.println "PASS: size_4"
  else throw (IO.userError "FAIL: size_4")
#eval do
  if ( (setCardinal  (setFromList [(  2 :Nat),   1,   3,   9])  ==   4) : Bool)
  then IO.println "PASS: size_5"
  else throw (IO.userError "FAIL: size_5")

theorem  null_size : ( (∀  s, ( ((not  (setIsEmpty  s))  ||  (setCardinal  s  ==   0)) : Prop)) : Prop) := by decide
theorem  null_singleton : ( (∀  x, ( (setCardinal  (setSingleton  x)  ==   1) : Prop)) : Prop) := by decide

#eval do
  if ( (
  match  ((setEmpty) :  List  Nat) with  |  setEmpty =>  true |  _ =>  false
  
) : Bool)
  then IO.println "PASS: set_patterns_0"
  else throw (IO.userError "FAIL: set_patterns_0")

#eval do
  if ( not  (
  match  (setFromList [(  2 :Nat)]) with  |  setEmpty =>  true |  _ =>  false
  
) : Bool)
  then IO.println "PASS: set_patterns_1"
  else throw (IO.userError "FAIL: set_patterns_1")

#eval do
  if ( not  (
  match  (setFromList [(  3 :  Nat),   4]) with  |  setEmpty =>  true |  _ =>  false
  
) : Bool)
  then IO.println "PASS: set_patterns_2"
  else throw (IO.userError "FAIL: set_patterns_2")

#eval do
  if ( (
  match  ((setFromList [  2]) :  List  Nat) with  |  setEmpty =>   0 |  setSingleton x =>  x |  _ =>   1
  
)  ==   2 : Bool)
  then IO.println "PASS: set_patterns_3"
  else throw (IO.userError "FAIL: set_patterns_3")

#eval do
  if ( (
  match  ((setEmpty) :  List  Nat) with  |  setEmpty =>   0 |  setSingleton x =>  x |  _ =>   1
  
)  ==   0 : Bool)
  then IO.println "PASS: set_patterns_4"
  else throw (IO.userError "FAIL: set_patterns_4")

#eval do
  if ( (
  match  ((setFromList [  3,   4,   5]) :  List  Nat) with  |  setEmpty =>   0 |  setSingleton x =>  x |  _ =>   1
  
)  ==   1 : Bool)
  then IO.println "PASS: set_patterns_5"
  else throw (IO.userError "FAIL: set_patterns_5")

#eval do
  if ( (
  match  ((setFromList [  3,   3,   3]) :  List  Nat) with  |  setEmpty =>   0 |  setSingleton x =>  x |  _ =>   1
  
)  ==   3 : Bool)
  then IO.println "PASS: set_patterns_6"
  else throw (IO.userError "FAIL: set_patterns_6")

#eval do
  if ( (
  match  ((setFromList [  3,   4,   5]) :  List  Nat) with  |  setEmpty =>   0 |  setSingleton _ =>   1 |  s =>  setCardinal  s
  
)  ==   3 : Bool)
  then IO.println "PASS: set_patterns_7"
  else throw (IO.userError "FAIL: set_patterns_7")

#eval do
  if ( (
  match  (((setFromList [  3,   4,   5]) :  List  Nat), false) with  |  (setEmpty,  true) =>   0 |  (setSingleton _,  _) =>   1 |  (s,  true) =>  setCardinal  s |  _ =>   5
  
)  ==   5 : Bool)
  then IO.println "PASS: set_patterns_8"
  else throw (IO.userError "FAIL: set_patterns_8")

#eval do
  if ( ( setCase  ((setFromList [  5]) :  List  Nat) (  0) (fun (n : Nat)=> match n with |  0 =>   1 |  1 =>   1 |  2 =>   0 |  n0 =>  (let x0  := n0 -   3 
x0) ) (  1)
)  ==   2 : Bool)
  then IO.println "PASS: set_patterns_9"
  else throw (IO.userError "FAIL: set_patterns_9")

#eval do
  if ( ( setCase  ((setFromList [  2]) :  List  Nat) (  0) (fun (n : Nat)=> match n with |  0 =>   1 |  1 =>   1 |  2 =>   0 |  n0 =>  (let x0  := n0 -   3 
x0) ) (  1)
)  ==   0 : Bool)
  then IO.println "PASS: set_patterns_10"
  else throw (IO.userError "FAIL: set_patterns_10")


#eval do
  if ( ( (setEqualBy  defaultCompare  (setUnionBy  defaultCompare (setFromList [(  1 :Nat),   2,   3])  (setFromList [  3,   2,   4]))  (setFromList [  1,   2,   3,   4]))) : Bool)
  then IO.println "PASS: union_1"
  else throw (IO.userError "FAIL: union_1")
theorem  union_in : ( (∀  e  s1  s2, ( (setMemberBy  setElemCompare  e  ( (setUnionBy  setElemCompare s1  s2)))  ==  ( (setMemberBy  setElemCompare e  s1)  ||  (setMemberBy  setElemCompare  e  s2)) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setEqualBy  defaultCompare (setAdd  (  2 :Nat)  (setFromList [  3,   4]))  (setFromList [  2,   3,   4]))) : Bool)
  then IO.println "PASS: insert_1"
  else throw (IO.userError "FAIL: insert_1")
#eval do
  if ( ( (setEqualBy  defaultCompare (setAdd  (  3 :Nat)  (setFromList [  3,   4]))  (setFromList [  3,   4]))) : Bool)
  then IO.println "PASS: insert_2"
  else throw (IO.userError "FAIL: insert_2")
#eval do
  if ( ( (setEqualBy  defaultCompare (setAdd  (  3 :Nat)  (setEmpty))  (setFromList [  3]))) : Bool)
  then IO.println "PASS: insert_3"
  else throw (IO.userError "FAIL: insert_3")

#eval do
  if ( ( (setEqualBy  defaultCompare (filter  (fun (n : Nat) =>  ( natGtb n (  2)))  (setFromList [(  1 :Nat),   2,   3,   4]))  (setFromList [  3,   4]))) : Bool)
  then IO.println "PASS: filter_1"
  else throw (IO.userError "FAIL: filter_1")
#eval do
  if ( ( (setEqualBy  defaultCompare (filter  (fun (n : Nat) =>  natGtb  n  (  2 :Nat))  (setEmpty))  (setEmpty))) : Bool)
  then IO.println "PASS: filter_2"
  else throw (IO.userError "FAIL: filter_2")
theorem  filter_emp : ( (∀  P, ( (setEqualBy  setElemCompare  (filter  P  (setEmpty))  (setEmpty)) : Prop)) : Prop) := by decide
theorem  filter_insert : ( (∀  e  s  P, ( (setEqualBy  setElemCompare  (filter  P  (setAdd  e  s)) 
  (if  (P  e) then  setAdd  e  (filter  P  s)  else  (filter  P  s))) : Prop)) : Prop) := by decide

#eval do
  if (
        pairEqual  (split  
        (  3,  0)  
        ((setFromList [ (  1,  0),  (  2,  0),  (  3,  0),  (  4,  0),  (  5,  0),  (  6,  0)])  :  List  ((Nat  × Nat))))  ((setFromList [ (  1,  0),  (  2,  0)]) , (setFromList [ (  4,  0),  (  5,  0),  (  6,  0)]) ) : Bool)
  then IO.println "PASS: split_simple"
  else throw (IO.userError "FAIL: split_simple")

#eval do
  if ( ((setSubsetBy  defaultCompare  ((setEmpty) :List  Nat)  (setEmpty))) : Bool)
  then IO.println "PASS: isSubsetOf_1"
  else throw (IO.userError "FAIL: isSubsetOf_1")
#eval do
  if ( ((setSubsetBy  defaultCompare  (setFromList [(  1 :Nat),   2,   3])  (setFromList [  1,   2,   3]))) : Bool)
  then IO.println "PASS: isSubsetOf_2"
  else throw (IO.userError "FAIL: isSubsetOf_2")
#eval do
  if ( ((setSubsetBy  defaultCompare  (setFromList [(  1 :Nat),   2])  (setFromList [  3,   2,   1]))) : Bool)
  then IO.println "PASS: isSubsetOf_3"
  else throw (IO.userError "FAIL: isSubsetOf_3")
theorem  isSubsetOf_refl : ( (∀  s, ( (setSubsetBy  setElemCompare  s  s) : Prop)) : Prop) := by decide
theorem  isSubsetOf_def : ( (∀  s1  s2, ( (setSubsetBy  setElemCompare  s1  s2)  ==  (∀  e, ( ((not  (setMemberBy  setElemCompare  e  s1))  ||  (setMemberBy  setElemCompare  e  s2)) : Prop)) : Prop)) : Prop) := by decide
theorem  isSubsetOf_eq : ( (∀  s1  s2, ( ( (setEqualBy  setElemCompare s1  s2))  ==  (((setSubsetBy  setElemCompare  s1  s2))  &&  ((setSubsetBy  setElemCompare  s2  s1))) : Prop)) : Prop) := by decide

#eval do
  if ( (not  ((setProperSubsetBy  defaultCompare  ((setEmpty) :List  Nat)  (setEmpty)))) : Bool)
  then IO.println "PASS: isProperSubsetOf_1"
  else throw (IO.userError "FAIL: isProperSubsetOf_1")
#eval do
  if ( (not  ((setProperSubsetBy  defaultCompare  (setFromList [(  1 :Nat),   2,   3])  (setFromList [  1,   2,   3])))) : Bool)
  then IO.println "PASS: isProperSubsetOf_2"
  else throw (IO.userError "FAIL: isProperSubsetOf_2")
#eval do
  if ( ((setProperSubsetBy  defaultCompare  (setFromList [(  1 :Nat),   2])  (setFromList [  3,   2,   1]))) : Bool)
  then IO.println "PASS: isProperSubsetOf_3"
  else throw (IO.userError "FAIL: isProperSubsetOf_3")
theorem  isProperSubsetOf_irrefl : ( (∀  s, ( not  ((setProperSubsetBy  setElemCompare  s  s)) : Prop)) : Prop) := by decide
theorem  isProperSubsetOf_def : ( (∀  s1  s2, ( (setProperSubsetBy  setElemCompare  s1  s2)  ==  (((setSubsetBy  setElemCompare  s1  s2))  &&  not  ((setSubsetBy  setElemCompare  s2  s1))) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setEqualBy  defaultCompare (bigunion  (setFromList [(setFromList [(  1 :Nat)])]))  (setFromList [  1]))) : Bool)
  then IO.println "PASS: bigunion_0"
  else throw (IO.userError "FAIL: bigunion_0")
#eval do
  if ( ( (setEqualBy  defaultCompare (bigunion  (setFromList [(setFromList [(  1 :Nat),   2,   3]) ,  (setFromList [  3,   2,   4])]))  (setFromList [  1,   2,   3,   4]))) : Bool)
  then IO.println "PASS: bigunion_1"
  else throw (IO.userError "FAIL: bigunion_1")
#eval do
  if ( ( (setEqualBy  defaultCompare (bigunion  (setFromList [(setFromList [(  1 :Nat),   2,   3]) ,  (setFromList [  3,   2,   4]),  (setEmpty)]))  (setFromList [  1,   2,   3,   4]))) : Bool)
  then IO.println "PASS: bigunion_2"
  else throw (IO.userError "FAIL: bigunion_2")
#eval do
  if ( ( (setEqualBy  defaultCompare (bigunion  (setFromList [(setFromList [(  1 :Nat),   2,   3]) ,  (setFromList [  3,   2,   4]),  (setFromList [  5])]))  (setFromList [  1,   2,   3,   4,   5]))) : Bool)
  then IO.println "PASS: bigunion_3"
  else throw (IO.userError "FAIL: bigunion_3")
theorem  bigunion_in : ( (∀  e  bs, ( (setMemberBy  setElemCompare  e  (bigunion  bs))  ==  (∃  s, ( (setMemberBy  (setCompareBy  setElemCompare)  s  bs)  &&  (setMemberBy  setElemCompare  e  s) : Prop)) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setEqualBy  defaultCompare (setDiffBy  defaultCompare  (setFromList [(  1 :Nat),   2,   3])  (setFromList [  3,   2,   4]))  (setFromList [  1]))) : Bool)
  then IO.println "PASS: difference_1"
  else throw (IO.userError "FAIL: difference_1")
theorem  difference_in : ( (∀  e  s1  s2, ( (setMemberBy  setElemCompare  e  ((setDiffBy  setElemCompare  s1  s2)))  ==  ( (setMemberBy  setElemCompare e  s1)  &&  not  ( (setMemberBy  setElemCompare e  s2))) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setEqualBy  defaultCompare (setInterBy  defaultCompare  (setFromList [  1,   2,   3])  (setFromList [(  3 :Nat),   2,   4]))  (setFromList [  2,   3]))) : Bool)
  then IO.println "PASS: intersection_1"
  else throw (IO.userError "FAIL: intersection_1")
theorem  intersection_in : ( (∀  e  s1  s2, ( (setMemberBy  setElemCompare  e  ((setInterBy  setElemCompare  s1  s2)))  ==  ( (setMemberBy  setElemCompare e  s1)  &&  (setMemberBy  setElemCompare  e  s2)) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setEqualBy  defaultCompare (map  Nat.succ  (setFromList [(  2 :Nat),   3,   4]))  (setFromList [  5,   4,   3]))) : Bool)
  then IO.println "PASS: map_1"
  else throw (IO.userError "FAIL: map_1") 
#eval do
  if ( ( (setEqualBy  defaultCompare (map  (fun (n : Nat) =>  n  *   3)  (setFromList [(  2 :Nat),   3,   4]))  (setFromList [  6,   9,   12]))) : Bool)
  then IO.println "PASS: map_2"
  else throw (IO.userError "FAIL: map_2")

#eval do
  if ( ( (setEqualBy  defaultCompare (bigunion  (map  (fun (n : Nat) =>  (setFromList [n,   2  *  n,   3  *  n]))  (setFromList [(  1 :Nat)])))  (setFromList [  1,   2,   3]))) : Bool)
  then IO.println "PASS: bigunionmap_0"
  else throw (IO.userError "FAIL: bigunionmap_0")
#eval do
  if ( ( (setEqualBy  defaultCompare (bigunion  (map  (fun (n : Nat) =>  (setFromList [n,   2  *  n,   3  *  n]))  (setFromList [(  2 :Nat),   8])))  (setFromList [  2,   4,   6,   8,   16,   24]))) : Bool)
  then IO.println "PASS: bigunionmap_1"
  else throw (IO.userError "FAIL: bigunionmap_1")


#eval do
  if ( ( (setEqualBy  defaultCompare (setFromListBy  defaultCompare  [(  2 :Nat),  4,  3])  (setFromList [  2,   3,   4]))) : Bool)
  then IO.println "PASS: fromList_1"
  else throw (IO.userError "FAIL: fromList_1") 
#eval do
  if ( ( (setEqualBy  defaultCompare (setFromListBy  defaultCompare  [(  2 :Nat),  2,  3,  2,  4])  (setFromList [  2,   3,   4]))) : Bool)
  then IO.println "PASS: fromList_2"
  else throw (IO.userError "FAIL: fromList_2") 
#eval do
  if ( ( (setEqualBy  defaultCompare (setFromListBy  defaultCompare  ([] :  List  Nat))  (setEmpty))) : Bool)
  then IO.println "PASS: fromList_3"
  else throw (IO.userError "FAIL: fromList_3")

theorem sigma_def_lemma : ((∀ sa sb a, ((setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (let  x2   := (setEmpty) 
 setFold  (fun (a1 : a) (x2 : List ((a ×b))) =>  setFold  (fun (b1 : b) (x2 : List ((a ×b))) =>  if  true then setAdd  (a1, b1)  x2  else  x2)  (sb  a1)  x2)  sa  x2)  (setSigmaBy  (pairCompare  setElemCompare  setElemCompare)  sa  sb)) : Prop)) : Prop) := by decide

#eval do
  if ( ( (setEqualBy  (pairCompare  defaultCompare  defaultCompare) (setSigmaBy  (pairCompare  defaultCompare  defaultCompare)  (setFromList [(  2 :Nat),   3])  (fun (n : Nat) =>  (setFromList [n *   2,  n  *   3])))  (setFromList [(  2,  4),  (  2,  6),  (  3,  6),  (  3,  9)]))) : Bool)
  then IO.println "PASS: Sigma_1"
  else throw (IO.userError "FAIL: Sigma_1")
theorem  Sigma_2 : ( (∀  sa  sb  a  b, ( ( (setMemberBy  (pairCompare  setElemCompare  setElemCompare) (a, b)  (setSigmaBy  (pairCompare  setElemCompare  setElemCompare)  sa  sb)))  ==  (( (setMemberBy  setElemCompare a  sa))  &&  ( (setMemberBy  setElemCompare b  (sb  a)))) : Prop)) : Prop) := by decide

theorem  cross_by_sigma  : (∀  s1  s2, ( (setEqualBy  (pairCompare  setElemCompare  setElemCompare)  (cross  s1  s2)  (setSigmaBy  (pairCompare  setElemCompare  setElemCompare)  s1  (Function.const  s2))) : Prop) : Prop) := by decide
#eval do
  if ( ( (setEqualBy  (pairCompare  defaultCompare  boolCompare) (cross  (setFromList [(  2 :Nat),   3])  (setFromList [true,  false]))  (setFromList [(  2,true), (  3,true),  (  2,false),  (  3,false)]))) : Bool)
  then IO.println "PASS: cross_1"
  else throw (IO.userError "FAIL: cross_1")

#eval do
  if ( (setEqualBy  defaultCompare  (leastFixedPoint (  0)  (map  (fun (x : Nat) =>  x))  ((setEmpty) :  List  Nat))  (setEmpty)) : Bool)
  then IO.println "PASS: lfp_empty_0"
  else throw (IO.userError "FAIL: lfp_empty_0")
#eval do
  if ( (setEqualBy  defaultCompare  (leastFixedPoint (  1)  (map  (fun (x : Nat) =>  x))  ((setEmpty) :  List  Nat))  (setEmpty)) : Bool)
  then IO.println "PASS: lfp_empty_1"
  else throw (IO.userError "FAIL: lfp_empty_1")
#eval do
  if ( (setEqualBy  defaultCompare  (leastFixedPoint (  1)  (map  (fun (x : Int) =>  (Int.neg  x)))  ((setFromList [( 1 :  Int), ( 2 :  Int), ( 3 :  Int)]) :  List  Int))  (setFromList [(Int.neg  (( 3 :  Int))),  (Int.neg  (( 2 :  Int))),  (Int.neg  (( 1 :  Int))), ( 1 :  Int), ( 2 :  Int), ( 3 :  Int)])) : Bool)
  then IO.println "PASS: lfp_saturate_neg_1"
  else throw (IO.userError "FAIL: lfp_saturate_neg_1")
#eval do
  if ( (setEqualBy  defaultCompare  (leastFixedPoint (  2)  (map  (fun (x : Int) =>  (Int.neg  x)))  ((setFromList [( 1 :  Int), ( 2 :  Int), ( 3 :  Int)]) :  List  Int))  (setFromList [(Int.neg  (( 3 :  Int))),  (Int.neg  (( 2 :  Int))),  (Int.neg  (( 1 :  Int))), ( 1 :  Int), ( 2 :  Int), ( 3 :  Int)])) : Bool)
  then IO.println "PASS: lfp_saturate_neg_2"
  else throw (IO.userError "FAIL: lfp_saturate_neg_2")
#eval do
  if ( (setEqualBy  defaultCompare  (leastFixedPoint (  3)  (map  (fun (x : Nat) =>  (  2 * x)  %   5))  ((setFromList [  1]) :  List  Nat))  (setFromList [  1,   2,   3,   4])) : Bool)
  then IO.println "PASS: lfp_saturate_mod_3"
  else throw (IO.userError "FAIL: lfp_saturate_mod_3")
#eval do
  if ( (setEqualBy  defaultCompare  (leastFixedPoint (  4)  (map  (fun (x : Nat) =>  (  2 * x)  %   5))  ((setFromList [  1]) :  List  Nat))  (setFromList [  1,   2,   3,   4])) : Bool)
  then IO.println "PASS: lfp_saturate_mod_4"
  else throw (IO.userError "FAIL: lfp_saturate_mod_4")
#eval do
  if ( (setEqualBy  defaultCompare  (leastFixedPoint (  5)  (map  (fun (x : Nat) =>  (  2 * x)  %   5))  ((setFromList [  1]) :  List  Nat))  (setFromList [  1,   2,   3,   4])) : Bool)
  then IO.println "PASS: lfp_saturate_mod_5"
  else throw (IO.userError "FAIL: lfp_saturate_mod_5")
#eval do
  if ( (setSubsetBy  defaultCompare  (setFromList [  1,   3,   5,   7,   9])  (leastFixedPoint (  5)  (map  (fun (x : Nat) =>   2 + x))  (setFromList [(  1 :  Nat)]))) : Bool)
  then IO.println "PASS: lfp_termination"
  else throw (IO.userError "FAIL: lfp_termination") 
