/- Generated by Lem from sorting.lem. -/

import LemLib
import Sorting



#eval do
  if ( ((isPermutationBy  (fun x y => x == y)  ([] :List  Nat)  [])) : Bool)
  then IO.println "PASS: perm_1"
  else throw (IO.userError "FAIL: perm_1")
#eval do
  if ( (not  ((isPermutationBy  (fun x y => x == y)  [(  2 :Nat)]  []))) : Bool)
  then IO.println "PASS: perm_2"
  else throw (IO.userError "FAIL: perm_2")
#eval do
  if ( ((isPermutationBy  (fun x y => x == y)  [(  2 :Nat),  1,  3,  5,  4]  [  1,  2,  3,  4,  5])) : Bool)
  then IO.println "PASS: perm_3"
  else throw (IO.userError "FAIL: perm_3")
#eval do
  if ( (not  ((isPermutationBy  (fun x y => x == y)  [(  2 :Nat),  3,  3,  5,  4]  [  1,  2,  3,  4,  5]))) : Bool)
  then IO.println "PASS: perm_4"
  else throw (IO.userError "FAIL: perm_4")
#eval do
  if ( (not  ((isPermutationBy  (fun x y => x == y)  [(  2 :Nat),  1,  3,  5,  4,  3]  [  1,  2,  3,  4,  5]))) : Bool)
  then IO.println "PASS: perm_5"
  else throw (IO.userError "FAIL: perm_5")
#eval do
  if ( ((isPermutationBy  (fun x y => x == y)  [(  2 :Nat),  1,  3,  5,  4,  3]  [  1,  2,  3,  3,  4,  5])) : Bool)
  then IO.println "PASS: perm_6"
  else throw (IO.userError "FAIL: perm_6")

theorem  isPermutation_1  : ( (∀  l, ( (isPermutationBy  (fun x y => x == y)  l  l) : Prop)) : Prop) := by decide
theorem  isPermutation_2  : ( (∀  l1  l2, ( (isPermutationBy  (fun x y => x == y)  l1  l2)  ==  (isPermutationBy  (fun x y => x == y)  l2  l1) : Prop)) : Prop) := by decide
theorem  isPermutation_3  : ( (∀  l1  l2  l3, ( ((not  (isPermutationBy  (fun x y => x == y)  l1  l2))  ||  ((not  (isPermutationBy  (fun x y => x == y)  l2  l3))  ||  (isPermutationBy  (fun x y => x == y)  l1  l3))) : Prop)) : Prop) := by decide
theorem  isPermutation_4  : ( (∀  l1  l2, ( ((not  (isPermutationBy  (fun x y => x == y)  l1  l2))  ||  (List.length  l1  ==  List.length  l2)) : Prop)) : Prop) := by decide
theorem  isPermutation_5  : ( (∀  l1  l2, ( ((not  (isPermutationBy  (fun x y => x == y)  l1  l2))  ||  (∀  x, ( elem  x  l1  ==  elem  x  l2 : Prop))) : Prop)) : Prop) := by decide

#eval do
  if ( ((isSortedBy  natLteb  ([] :List  Nat))) : Bool)
  then IO.println "PASS: isSorted_1"
  else throw (IO.userError "FAIL: isSorted_1")
#eval do
  if ( ((isSortedBy  natLteb  [(  2 :Nat)])) : Bool)
  then IO.println "PASS: isSorted_2"
  else throw (IO.userError "FAIL: isSorted_2")
#eval do
  if ( ((isSortedBy  natLteb  [(  2 :Nat),  4,  5])) : Bool)
  then IO.println "PASS: isSorted_3"
  else throw (IO.userError "FAIL: isSorted_3")
#eval do
  if ( ((isSortedBy  natLteb  [(  1 :Nat),  2,  2,  4,  4,  8])) : Bool)
  then IO.println "PASS: isSorted_4"
  else throw (IO.userError "FAIL: isSorted_4")
#eval do
  if ( (not  ((isSortedBy  natLteb  [(  3 :Nat),  2]))) : Bool)
  then IO.println "PASS: isSorted_5"
  else throw (IO.userError "FAIL: isSorted_5")
#eval do
  if ( (not  ((isSortedBy  natLteb  [(  1 :Nat),  2,  3,  2,  3,  4,  5]))) : Bool)
  then IO.println "PASS: isSorted_6"
  else throw (IO.userError "FAIL: isSorted_6")

theorem  insertBy_1 : ( (∀  l  e  cmp, ( ((not  ((∀  x  y  z, ( ((not  (cmp  x  y  &&  cmp  y  z))  ||  cmp  x  z) : Prop))  &&  isSortedBy  cmp  l))  ||  isSortedBy  cmp  (insertBy  cmp  e  l)) : Prop)) : Prop) := by decide
theorem  insertBy_2 : ( (∀  l  e  cmp, ( List.length  (insertBy  cmp  e  l)  ==  (List.length  l  +   1) : Prop)) : Prop) := by decide
theorem  insertBy_3 : ( (∀  l  e1  e2  cmp, ( elem  e1  (insertBy  cmp  e2  l)  ==  ((e1  ==  e2)  ||  elem  e1  l) : Prop)) : Prop) := by decide

theorem  insertSort_1 : ( (∀  l  cmp, ( (isPermutationBy  (fun x y => x == y)  ((insertSortBy  isLessEqual  l))  l) : Prop)) : Prop) := by decide
theorem  insertSort_2 : ( (∀  l  cmp, ( (isSortedBy  isLessEqual  ((insertSortBy  isLessEqual  l))) : Prop)) : Prop) := by decide


#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (insertSortBy  natLteb  ([] :  List  Nat))  [])) : Bool)
  then IO.println "PASS: sort_1"
  else throw (IO.userError "FAIL: sort_1")
#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (insertSortBy  natLteb  ([  6,  4,  3,  8,  1,  2] :  List  Nat))  [  1,  2,  3,  4,  6,  8])) : Bool)
  then IO.println "PASS: sort_2"
  else throw (IO.userError "FAIL: sort_2")
#eval do
  if ( ( (listEqualBy  (fun x y => x == y) (insertSortBy  natLteb  ([  5,  4,  5,  2,  4] :  List  Nat))  [  2,  4,  4,  5,  5])) : Bool)
  then IO.println "PASS: sort_3"
  else throw (IO.userError "FAIL: sort_3")

theorem  sort_4 : ( (∀  l  cmp, ( (isPermutationBy  (fun x y => x == y)  ((insertSortBy  isLessEqual  l))  l) : Prop)) : Prop) := by decide
theorem  sort_5 : ( (∀  l  cmp, ( (isSortedBy  isLessEqual  ((insertSortBy  isLessEqual  l))) : Prop)) : Prop) := by decide


