/- Generated by Lem from string_extra.lem. -/

import LemLib
import String_extra



#eval do
  if ( stringFromNat (  0)  ==  "0" : Bool)
  then IO.println "PASS: stringFromNat_0"
  else throw (IO.userError "FAIL: stringFromNat_0")
#eval do
  if ( stringFromNat (  1)  ==  "1" : Bool)
  then IO.println "PASS: stringFromNat_1"
  else throw (IO.userError "FAIL: stringFromNat_1")
#eval do
  if ( stringFromNat (  42)  ==  "42" : Bool)
  then IO.println "PASS: stringFromNat_2"
  else throw (IO.userError "FAIL: stringFromNat_2")

#eval do
  if ( stringFromNatural (  0)  ==  "0" : Bool)
  then IO.println "PASS: stringFromNatural_0"
  else throw (IO.userError "FAIL: stringFromNatural_0")
#eval do
  if ( stringFromNatural (  1)  ==  "1" : Bool)
  then IO.println "PASS: stringFromNatural_1"
  else throw (IO.userError "FAIL: stringFromNatural_1")
#eval do
  if ( stringFromNatural (  42)  ==  "42" : Bool)
  then IO.println "PASS: stringFromNatural_2"
  else throw (IO.userError "FAIL: stringFromNatural_2")

#eval do
  if ( stringFromInt (( 0 :  Int))  ==  "0" : Bool)
  then IO.println "PASS: stringFromInt_0"
  else throw (IO.userError "FAIL: stringFromInt_0")
#eval do
  if ( stringFromInt (( 1 :  Int))  ==  "1" : Bool)
  then IO.println "PASS: stringFromInt_1"
  else throw (IO.userError "FAIL: stringFromInt_1")
#eval do
  if ( stringFromInt (( 42 :  Int))  ==  "42" : Bool)
  then IO.println "PASS: stringFromInt_2"
  else throw (IO.userError "FAIL: stringFromInt_2")
#eval do
  if ( stringFromInt  ((Int.neg  (( 1 :  Int))))  ==  "-1" : Bool)
  then IO.println "PASS: stringFromInt_3"
  else throw (IO.userError "FAIL: stringFromInt_3")

#eval do
  if ( stringFromInteger (( 0 :  Int))  ==  "0" : Bool)
  then IO.println "PASS: stringFromInteger_0"
  else throw (IO.userError "FAIL: stringFromInteger_0")
#eval do
  if ( stringFromInteger (( 1 :  Int))  ==  "1" : Bool)
  then IO.println "PASS: stringFromInteger_1"
  else throw (IO.userError "FAIL: stringFromInteger_1")
#eval do
  if ( stringFromInteger (( 42 :  Int))  ==  "42" : Bool)
  then IO.println "PASS: stringFromInteger_2"
  else throw (IO.userError "FAIL: stringFromInteger_2")
#eval do
  if ( stringFromInteger  ((Int.neg  (( 1 :  Int))))  ==  "-1" : Bool)
  then IO.println "PASS: stringFromInteger_3"
  else throw (IO.userError "FAIL: stringFromInteger_3")
 
