#!/bin/sh

file=`basename $1 .lem`
dir=.builddir---$file---`date +%Y-%m-%d---%H-%M-%S`---ocaml
mkdir $dir
cd $dir
cp ../$file.lem .
lem -ocaml $file.lem
ln -s ../../ocaml-lib .
ocamlbuild -libs nums -I ocaml-lib ${file}Extra.native
./${file}Extra.native
cd ..

