(*Generated by Lem from ../library-new/pervasives.lem.*)
open HolKernel Parse boolLib bossLib;
open basic_classesTheory lem_boolTheory optionTheory sumTheory lem_eitherTheory lem_functionTheory integerTheory intReduce lem_numTheory listTheory rich_listTheory lem_listTheory sortingTheory lem_mapTheory lem_setTheory lem_sortingTheory;

val _ = numLib.prefer_num();



val _ = new_theory "lem_pervasives"

 

(*include import Basic_classes Bool Tuple Maybe Either Function Num List Map Set*) 

(*import Sorting Relation*)

val _ = export_theory()

