(*Generated by Lem from ../library-new/maybe_extra.lem.*)
open HolKernel Parse boolLib bossLib;
open basic_classesTheory optionTheory;

val _ = numLib.prefer_num();



val _ = new_theory "lem_maybe_extra"



(*open import Basic_classes Maybe*)

(* ----------------------- *)
(* fromJust                *)
(* ----------------------- *)

(*val fromJust : forall 'a. maybe 'a -> 'a*)
(*let fromJust (Just v) = v*)

val _ = export_theory()

