/- Stub Pervasives_extra for the Lean backend test suite.
   In production, this file is generated by `lem -lean` from pervasives.lem.
   This stub provides the minimal type class definitions needed by test files. -/
import LemLib

namespace Pervasives_extra

/- Numeric addition class, extending Lean's built-in Add. -/
class NumAdd (a : Type) extends Add a where

instance : NumAdd Nat where
  add := Nat.add

/- Ordered set element class. Provides the comparison function used by
   LemLib's set operations (setMemberBy, setUnionBy, etc.). -/
class SetType (a : Type) where
  setElemCompare : a → a → LemOrdering
export SetType (setElemCompare)

/- Derive BEq from SetType's comparison function. -/
instance {a : Type} [SetType a] : BEq a where
  beq x y := match SetType.setElemCompare x y with | .EQ => true | _ => false

end Pervasives_extra
