/- Generated by Lem from bool.lem. -/

import LemLib


namespace Lem_Bool

/- removed value specification -/

/- 
def  not  (b : Bool)  : Bool :=  match  b with  |  true =>  false |  false =>  true
 -/
/- removed value specification -/

/- 
def  and  (b1 : Bool) (b2 : Bool)  : Bool :=  match b1,  b2 with  | true,  true =>  true | _, _ =>  false
 -/
/- removed value specification -/

/- 
def  or  (b1 : Bool) (b2 : Bool)  : Bool :=  match b1,  b2 with  | false,  false =>  false | _, _ =>  true
 -/
/- removed value specification -/

/- 
def  imp  (b1 : Bool) (b2 : Bool)  : Bool :=  match b1,  b2 with  | true,  false =>  false | _, _ =>  true
 -/
/- removed top-level value definition -/
/- removed value specification -/

/- 
def  equiv  (b1 : Bool) (b2 : Bool)  : Bool :=  match b1,  b2 with  | true,  true =>  true | false,  false =>  true | _, _ =>  false
 -/
/- removed value specification -/

/- removed top-level value definition -/
end Lem_Bool


