/- Generated by Lem from either.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.List
import LemLib.Tuple

namespace Lem_Either
 

open Lem_Bool
open Lem_Basic_classes
open Lem_List
open Lem_Tuple



/- 

abbrev  either  (a : Type) (b : Type) := Sum
 -/
/- removed value specification -/

/- removed value specification -/


def  eitherEqualBy  {a : Type} {b : Type}  (eql : a → a → Bool) (eqr : b → b → Bool)  (left : Sum  a  b)  (right : Sum  a  b)  : Bool := 
  match left,  right with  | Sum.inl  l,  Sum.inl  l' =>  eql  l  l' | Sum.inr  r,  Sum.inr  r' =>  eqr  r  r' | _, _ =>  false
  
def  eitherEqual  {a : Type} {b : Type} [Eq0 a] [Eq0 b]   : Sum a b → Sum a b → Bool :=  eitherEqualBy  (fun x y => x == y)  (fun x y => x == y)

instance (a b : Type) [Eq0 a] [Eq0 b] : Eq0 (Sum  a  b) where

    isEqual   :=  (@eitherEqual (a) (b) _ _)

    isInequal   x  y  :=  not  (eitherEqual  x  y)
 

def  either_setElemCompare  {a : Type} {b : Type} {c : Type} {d : Type}  (cmpa : d → b → LemOrdering) (cmpb : c → a → LemOrdering) (x : Sum d c) (y : Sum b a)  : LemOrdering := 
  match x,  y with  | Sum.inl  x',  Sum.inl  y' =>  cmpa  x'  y' | Sum.inr  x',  Sum.inr  y' =>  cmpb  x'  y' | Sum.inl  _,  Sum.inr  _ =>  LemOrdering.LT | Sum.inr  _,  Sum.inl  _ =>  LemOrdering.GT
  

instance (a b : Type) [SetType a] [SetType b] : SetType (Sum  a  b) where

    setElemCompare   x  y  :=  either_setElemCompare  (@setElemCompare (a) _)  (@setElemCompare (b) _)  x  y

/- removed value specification -/


/- removed value specification -/


/- removed value specification -/

def  either0  {a : Type} {b : Type} {c : Type}  (fa : a → c) (fb : b → c) (x : Sum a b)  : c :=  match  x with  |  Sum.inl  a1 =>  fa  a1 |  Sum.inr  b1 =>  fb  b1

/- removed value specification -/

 def  partitionEither  {a : Type} {b : Type}  (l : List (Sum a b))  : (List a ×List b) :=  match  l with  |  [] =>  ([], []) |  x  ::  xs =>  (       match  partitionEither  xs with |   (ll,  rl) => (       match  x with  |  Sum.inl  l =>  ((l :: ll), rl) |  Sum.inr  r =>  (ll, (r :: rl))       )      )

/- removed value specification -/


/- removed value specification -/


end Lem_Either



