/- Generated by Lem from function_extra.lem. -/

import LemLib

import LemLib.Maybe
import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Num
import LemLib.Function

namespace Lem_Function_extra


open Lem_Maybe
open Lem_Bool
open Lem_Basic_classes
open Lem_Num
open Lem_Function




/- removed value specification -/

end Lem_Function_extra


