/- Generated by Lem from map.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Function
import LemLib.Maybe
import LemLib.List
import LemLib.Tuple
import LemLib.Set
import LemLib.Num

namespace Lem_Map


open Lem_Bool
open Lem_Basic_classes
open Lem_Function
open Lem_Maybe
open Lem_List
open Lem_Tuple
open Lem_Set
open Lem_Num


/- 

inductive  map (k : Type) (v : Type) : Type where
open map
 -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance (k v : Type) [Eq0 k] [Eq0 v] : Eq0 (Fmap  k  v) where

    isEqual   :=  (fmapEqualBy  (fun x y => x == y)  (fun x y => x == y))

    isInequal   m1  m2  :=  not  ((fmapEqualBy  (fun x y => x == y)  (fun x y => x == y)  m1  m2))



/-  --------------------------------------------------------------------------  -/
/-  Map type class                                                              -/
/-  --------------------------------------------------------------------------  -/

class MapKeyType (a : Type) where 

  mapKeyCompare :  a →  a →  LemOrdering


export MapKeyType (mapKeyCompare)

instance {a : Type} [MapKeyType a] : BEq a where
  beq x y := match mapKeyCompare x y with | .EQ => true | _ => false


instance (priority := low) (a : Type) [SetType a] : MapKeyType a where

    mapKeyCompare   :=  (@setElemCompare (a) _)
 
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

def  fromList  {k : Type} {v : Type} [MapKeyType k]  (l : List ((k ×v)))  : Fmap k v :=  List.foldl  (fun (m : Fmap k v) (p : (k ×v)) =>  match m, p with |  m,  (k1, v1) =>  fmapAdd  k1  v1  m )  fmapEmpty  l
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/-  

def  all  {k : Type} {v : Type} [MapKeyType k] [Eq0 v]  (P : k → v → Bool) (m : Fmap k v)  : Bool :=  (∀  k  v, ( (P  k  v  &&  (Instance_Basic_classes_Eq_Maybe_maybe.=  lookup  k  m  some  v)) : Prop)) -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/

/-  instance of SetType  -/
def  map_setElemCompare  {a : Type} {b : Type} {c : Type} {d : Type} {e : Type} [SetType a] [SetType b] [SetType c] [SetType d] [MapKeyType b] [MapKeyType d]  (cmp : List ((d ×c)) → List ((b ×a)) → e) (x : Fmap d c) (y : Fmap b a)  : e := 
  cmp  (id  x)  (id  y)

instance (a b : Type) [SetType a] [SetType b] [MapKeyType a] : SetType (Fmap  a  b) where

    setElemCompare   x  y  :=  map_setElemCompare  (setCompareBy  (pairCompare  (@setElemCompare (a) _)  (@setElemCompare (b) _)))  x  y

end Lem_Map

