/- Generated by Lem from maybe.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Function

namespace Lem_Maybe
 

open Lem_Bool
open Lem_Basic_classes
open Lem_Function

/- 

/-  ==========================================================================  -/
/-  Basic stuff                                                                 -/
/-  ==========================================================================  -/

inductive  maybe (a : Type) : Type where 
 
  
  |  Nothing : maybe a
  
  |  Just :  a →  maybe a
  deriving BEq, Ord
export maybe (Nothing Just)
instance {a : Type} : Inhabited (maybe a) where
  default := sorry
instance {a : Type} : Lem_Basic_classes.SetType (maybe a) where
  setElemCompare := sorry
instance {a : Type} : Lem_Basic_classes.Eq0 (maybe a) where
  isEqual _ _ := sorry
  isInequal _ _ := sorry
instance {a : Type} : Lem_Basic_classes.Ord0 (maybe a) where
  compare := sorry
  isLess := sorry
  isLessEqual := sorry
  isGreater := sorry
  isGreaterEqual := sorry -/
/- removed value specification -/

/- removed value specification -/


def  maybeEqualBy  {a : Type}  (eq : a → a → Bool) (x : Option a) (y : Option a)  : Bool :=  match x, y with  | none,  none =>  true | none,  some  _ =>  false | some  _,  none =>  false | some  x',  some  y' =>  (eq  x'  y')

/- removed top-level value definition -/
/- removed top-level value definition -/

instance (a : Type) [Eq0 a] : Eq0 (Option  a) where

    isEqual   :=  (maybeEqualBy  (fun x y => x == y))

    isInequal   x  y  :=  not  ((maybeEqualBy  (fun x y => x == y)  x  y))
  


def  maybeCompare  {a : Type} {b : Type}  (cmp : b → a → LemOrdering) (x : Option b) (y : Option a)  : LemOrdering :=  match x, y with  | none,  none =>  LemOrdering.EQ | none,  some  _ =>  LemOrdering.LT | some  _,  none =>  LemOrdering.GT | some  x',  some  y' =>  cmp  x'  y'


instance (a : Type) [SetType a] : SetType (Option  a) where

    setElemCompare   :=  maybeCompare  (@setElemCompare (a) _)


instance (a : Type) [Ord0 a] : Ord0 (Option  a) where

      compare   :=  maybeCompare  Ord0.compare

      isLess   :=  fun  m1 =>  (fun  m2 =>  maybeCompare  Ord0.compare  m1  m2  ==  LemOrdering.LT)

      isLessEqual   :=  fun  m1 =>  (fun  m2 =>  (let  r  := maybeCompare  Ord0.compare  m1  m2;  (r  ==  LemOrdering.LT)  ||  (r  ==  LemOrdering.EQ)))

      isGreater   :=  fun  m1 =>  (fun  m2 =>  maybeCompare  Ord0.compare  m1  m2  ==  LemOrdering.GT)

      isGreaterEqual   :=  fun  m1 =>  (fun  m2 =>  (let  r  := maybeCompare  Ord0.compare  m1  m2;  (r  ==  LemOrdering.GT)  ||  (r  ==  LemOrdering.EQ)))

/- removed value specification -/

def  maybe0  {a : Type} {b : Type}  (d : b) (f : a → b) (mb : Option a)  : b :=  match  mb with  |  some  a1 =>  f  a1 |  none =>  d

/- removed value specification -/

def  isJust  {a : Type}  (mb : Option a)  : Bool :=  match  mb with  |  some  _ =>  true |  none =>  false

/- removed value specification -/

def  isNothing  {a : Type}  (mb : Option a)  : Bool :=  match  mb with  |  some  _ =>  false |  none =>  true

/- removed value specification -/

def  fromMaybe  {a : Type}  (d : a) (mb : Option a)  : a :=  match  mb with  |  some  v =>  v |  none =>  d

/- removed value specification -/

/-  
def  map  {a : Type} {b : Type}  (f : a → b)  : Option a → Option b :=  maybe0  none  (fun (v : a) =>  some  (f  v)) -/
/- removed value specification -/
 
def  bind0  {a : Type} {b : Type}  (mb : Option a) (f : a → Option b)  : Option b :=  maybe0  none  f  mb
abbrev  maybe (a : Type) := Option  a

end Lem_Maybe

