/- Generated by Lem from num.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes

namespace Lem_Num


open Lem_Bool
open Lem_Basic_classes




/- 

 -/

/-  ==========================================================================  -/
/-  Syntactic type-classes for common operations                                -/
/-  ==========================================================================  -/

/-  Typeclasses can be used as a mean to overload constants like "+", "-", etc  -/

class NumNegate (a : Type) where 
 
  numNegate :  a →  a 


export NumNegate (numNegate)


class NumAbs (a : Type) where 
 
  abs :  a →  a 


export NumAbs (abs)


class NumAdd (a : Type) where 
 
  numAdd :  a →  a →  a


export NumAdd (numAdd)


class NumMinus (a : Type) where 
 
  numMinus :  a →  a →  a


export NumMinus (numMinus)


class NumMult (a : Type) where 
 
  numMult :  a →  a →  a


export NumMult (numMult)


class NumPow (a : Type) where 
 
  numPow :  a →  Nat →  a


export NumPow (numPow)


class NumDivision (a : Type) where 
 
  numDivision :  a →  a →  a


export NumDivision (numDivision)


class NumIntegerDivision (a : Type) where 
 
  numIntegerDivision :  a →  a →  a


export NumIntegerDivision (numIntegerDivision)



class NumRemainder (a : Type) where 
 
  numRemainder :  a →  a →  a


export NumRemainder (numRemainder)


class NumSucc (a : Type) where 
 
  succ :  a →  a


export NumSucc (succ)


class NumPred (a : Type) where 
 
  pred :  a →  a


export NumPred (pred)

/- 


/-  -----------------------  -/
/-  natural                  -/
/-  -----------------------  -/

/-  unbounded size natural numbers  -/
inductive  natural : Type where
open natural
 -/
/- 


/-  -----------------------  -/
/-  int                      -/
/-  -----------------------  -/

/-  bounded size integers with uncertain length  -/

inductive  int : Type where
open int
 -/
/- 


/-  -----------------------  -/
/-  integer                  -/
/-  -----------------------  -/

/-  unbounded size integers  -/

inductive  integer : Type where
open integer
 -/
/- 

/-  -----------------------  -/
/-  bint                     -/
/-  -----------------------  -/

/-  TODO the bounded ints are only partially implemented, use with care.  -/

/-  32 bit integers  -/
inductive  int32 : Type where
open int32
 -/
/-  /-  newtype wrapper â distinct from Int  -/

/-  64 bit integers  -/
inductive  int64 : Type where
open int64
 -/
/-  /-  newtype wrapper â distinct from Int  -/


/-  -----------------------  -/
/-  rational                 -/
/-  -----------------------  -/

/-  unbounded size and precision rational numbers  -/

inductive  rational : Type where
open rational
 -/
/-  /-  ???: better type for this in HOL?  -/


/-  -----------------------  -/
/-  real                     -/
/-  -----------------------  -/

/-  real numbers  -/
/-  Note that for OCaml, this is mapped to floats with 64 bits.  -/

inductive  real : Type where
open real
 -/
/-  /-  ???: better type for this in HOL?  -/


/-  -----------------------  -/
/-  double                   -/
/-  -----------------------  -/

/-  double precision floating point (64 bits)  -/

inductive  float64 : Type where
open float64
 -/
/-  /-  ???: better type for this in HOL?  -/

inductive  float32 : Type where
open float32
 -/
/- removed value specification -/

/- 

instance   : Numeral Nat where

    fromNumeral   n  :=    n
 -/
/- removed value specification -/

/- removed top-level value definition -/
instance   : Eq0 Nat where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance   : Ord0 Nat where

    compare   :=  defaultCompare

    isLess   :=  natLtb

    isLessEqual   :=  natLteb

    isGreater   :=  natGtb

    isGreaterEqual   :=  natGteb


instance   : SetType Nat where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumAdd Nat where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Nat where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- 
def  natSucc  (n : Nat)  : Nat :=  n  +  1 -/
instance   : NumSucc Nat where

    succ   :=  Nat.succ

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumPred Nat where

    pred   :=  Nat.pred

/- removed value specification -/


instance   : NumMult Nat where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumIntegerDivision Nat where
 
    numIntegerDivision   :=  (fun x y => x / y)


instance   : NumDivision Nat where
 
    numDivision   :=  (fun x y => x / y)

/- removed value specification -/


instance   : NumRemainder Nat where
 
    numRemainder   :=  (fun x y => x % y)

/- removed value specification -/

/- 
 def  gen_pow_aux  {a : Type}   (mul  : a →  a →  a)  (a  : a)  (b  : a)  (e  : Nat)  : a := 
   match  e with  |  0 =>  a |  1 =>  mul  a  b | (  (e' + 2)) => ( let  e''  := e  /  2;                     let  a'   := (if  (e  mod  2)  =  0 then  a  else  mul  a  b);                     gen_pow_aux  mul  a'  (mul  b  b)  e'')
    -/
       
def  gen_pow  {a : Type}   (one  : a)  (mul  : a →  a →  a)  (b  : a)  (e  : Nat)   :  a :=  
  if  natLtb  e (  0) then  one  else  
  if  (e  ==   0) then  one  else  gen_pow_aux  mul  one  b  e
/- removed value specification -/


instance   : NumPow Nat where
 
    numPow   :=  natPower

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : OrdMaxMin Nat where
 
    max   :=  natMax

    min   :=  natMin

/- removed value specification -/

/- 

instance   : Numeral Nat where

    fromNumeral   n  :=    n
 -/
/- removed value specification -/

/- removed top-level value definition -/
instance   : Eq0 Nat where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance   : Ord0 Nat where

    compare   :=  defaultCompare

    isLess   :=  natLtb

    isLessEqual   :=  natLteb

    isGreater   :=  natGtb

    isGreaterEqual   :=  natGteb


instance   : SetType Nat where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumAdd Nat where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Nat where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- 
def  naturalSucc  (n : Nat)  : Nat :=  n  +  1 -/
instance   : NumSucc Nat where

    succ   :=  Nat.succ

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumPred Nat where

    pred   :=  Nat.pred

/- removed value specification -/


instance   : NumMult Nat where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow Nat where
 
    numPow   :=  natPower

/- removed value specification -/


instance   : NumIntegerDivision Nat where
 
    numIntegerDivision   :=  (fun x y => x / y)


instance   : NumDivision Nat where
 
    numDivision   :=  (fun x y => x / y)

/- removed value specification -/


instance   : NumRemainder Nat where
 
    numRemainder   :=  (fun x y => x % y)

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : OrdMaxMin Nat where
 
    max   :=  natMax

    min   :=  natMin

/- removed value specification -/

/- 

instance   : Numeral Int where

    fromNumeral   n  :=  ( n :  Int)
 -/
/- removed value specification -/

/- removed top-level value definition -/
instance   : Eq0 Int where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance   : Ord0 Int where

    compare   :=  defaultCompare

    isLess   :=  intLtb

    isLessEqual   :=  intLteb

    isGreater   :=  intGtb

    isGreaterEqual   :=  intGteb


instance   : SetType Int where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumNegate Int where

    numNegate   :=  (fun  i=> (Int.neg  i))

/- removed value specification -/


instance   : NumAbs Int where

    abs   :=  intAbs

/- removed value specification -/


instance   : NumAdd Int where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Int where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumSucc Int where

    succ   :=  (fun  n=> n  + ( 1 :  Int))

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumPred Int where

    pred   :=  (fun  n=> n  - ( 1 :  Int))

/- removed value specification -/


instance   : NumMult Int where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow Int where
 
    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


instance   : NumIntegerDivision Int where
 
    numIntegerDivision   :=  (fun x y => x / y)


instance   : NumDivision Int where
 
    numDivision   :=  (fun x y => x / y)

/- removed value specification -/


instance   : NumRemainder Int where
 
    numRemainder   :=  (fun x y => x % y)

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : OrdMaxMin Int where
 
    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral LemInt32 where

    fromNumeral   n  :=  ( n :  LemInt32)
 -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : Eq0 LemInt32 where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance   : Ord0 LemInt32 where

    compare   :=  defaultCompare

    isLess   :=  lemInt32Ltb

    isLessEqual   :=  lemInt32Lteb

    isGreater   :=  lemInt32Gtb

    isGreaterEqual   :=  lemInt32Gteb


instance   : SetType LemInt32 where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumNegate LemInt32 where

    numNegate   :=  Neg.neg

/- removed value specification -/

/- 
def  int32Abs  (i : LemInt32)  : LemInt32 :=  (if  <=  0  i then  i  else  ~ i) -/

instance   : NumAbs LemInt32 where

    abs   :=  lemInt32Abs

/- removed value specification -/


instance   : NumAdd LemInt32 where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus LemInt32 where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- removed top-level value definition -/

instance   : NumSucc LemInt32 where

    succ   :=  (fun  n=> n  + ( 1 :  LemInt32))

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumPred LemInt32 where

    pred   :=  (fun  n=> n  - ( 1 :  LemInt32))

/- removed value specification -/


instance   : NumMult LemInt32 where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow LemInt32 where
 
    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


instance   : NumIntegerDivision LemInt32 where
 
    numIntegerDivision   :=  (fun x y => x / y)


instance   : NumDivision LemInt32 where
 
    numDivision   :=  (fun x y => x / y)

/- removed value specification -/


instance   : NumRemainder LemInt32 where
 
    numRemainder   :=  (fun x y => x % y)

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : OrdMaxMin LemInt32 where
 
    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral LemInt64 where

    fromNumeral   n  :=  ( n :  LemInt64)
 -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : Eq0 LemInt64 where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance   : Ord0 LemInt64 where

    compare   :=  defaultCompare

    isLess   :=  lemInt64Ltb

    isLessEqual   :=  lemInt64Lteb

    isGreater   :=  lemInt64Gtb

    isGreaterEqual   :=  lemInt64Gteb


instance   : SetType LemInt64 where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumNegate LemInt64 where

    numNegate   :=  Neg.neg

/- removed value specification -/

/- 
def  int64Abs  (i : LemInt64)  : LemInt64 :=  (if  <=  0  i then  i  else  ~ i) -/

instance   : NumAbs LemInt64 where

    abs   :=  lemInt64Abs

/- removed value specification -/


instance   : NumAdd LemInt64 where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus LemInt64 where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- removed top-level value definition -/

instance   : NumSucc LemInt64 where

    succ   :=  (fun  n=> n  + ( 1 :  LemInt64))

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumPred LemInt64 where

    pred   :=  (fun  n=> n  - ( 1 :  LemInt64))

/- removed value specification -/


instance   : NumMult LemInt64 where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow LemInt64 where
 
    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


instance   : NumIntegerDivision LemInt64 where
 
    numIntegerDivision   :=  (fun x y => x / y)


instance   : NumDivision LemInt64 where
 
    numDivision   :=  (fun x y => x / y)

/- removed value specification -/


instance   : NumRemainder LemInt64 where
 
    numRemainder   :=  (fun x y => x % y)

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : OrdMaxMin LemInt64 where
 
    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral Int where

    fromNumeral   n  :=  ( n :  Int)
 -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
instance   : Eq0 Int where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance   : Ord0 Int where

    compare   :=  defaultCompare

    isLess   :=  intLtb

    isLessEqual   :=  intLteb

    isGreater   :=  intGtb

    isGreaterEqual   :=  intGteb


instance   : SetType Int where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumNegate Int where

    numNegate   :=  (fun  i=> (Int.neg  i))

/- removed value specification -/


instance   : NumAbs Int where

    abs   :=  intAbs

/- removed value specification -/


instance   : NumAdd Int where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus Int where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumSucc Int where

    succ   :=  (fun  n=> n  + ( 1 :  Int))

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumPred Int where

    pred   :=  (fun  n=> n  - ( 1 :  Int))

/- removed value specification -/


instance   : NumMult Int where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumPow Int where
 
    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/


instance   : NumIntegerDivision Int where
 
    numIntegerDivision   :=  (fun x y => x / y)


instance   : NumDivision Int where
 
    numDivision   :=  (fun x y => x / y)

/- removed value specification -/


instance   : NumRemainder Int where
 
    numRemainder   :=  (fun x y => x % y)

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : OrdMaxMin Int where
 
    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral LemRational where

    fromNumeral   n  :=  unsupportedRationalFromNumeral  n
 -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
instance   : Eq0 LemRational where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance   : Ord0 LemRational where

    compare   :=  defaultCompare

    isLess   :=  unsupportedRationalLess

    isLessEqual   :=  unsupportedRationalLessEq

    isGreater   :=  unsupportedRationalGreater

    isGreaterEqual   :=  unsupportedRationalGreaterEq


instance   : SetType LemRational where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumAdd LemRational where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus LemRational where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- removed top-level value definition -/

instance   : NumNegate LemRational where

    numNegate   :=  (fun  n=> unsupportedRationalFromNumeral  0  -  n)

/- removed value specification -/

/- removed top-level value definition -/

instance   : NumAbs LemRational where

    abs   :=  (fun  n=> (if  unsupportedRationalGreater  n (unsupportedRationalFromNumeral  0) then  n  else unsupportedRationalFromNumeral  0  -  n))

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumSucc LemRational where

    succ   :=  (fun  n=> n  + unsupportedRationalFromNumeral  1)

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumPred LemRational where

    pred   :=  (fun  n=> n  - unsupportedRationalFromNumeral  1)

/- removed value specification -/


instance   : NumMult LemRational where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumDivision LemRational where

    numDivision   :=  (fun x y => x / y)

/- removed value specification -/

/- 
def  rationalFromFrac  (n : Int) (d : Int)  : LemRational :=  (unsupportedRationalFromInt  n)  /  (unsupportedRationalFromInt  d) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
 partial def  rationalPowInteger  (b : LemRational) (e : Int)  : LemRational := 
  if  e  =  0 then  1  else 
  if  >  e  0 then  b  ^  (e  -  1)  *  b  else 
  b  ^  (e  +  1)  /  b -/
/- removed value specification -/

/- 
def  rationalPowNat  (r : LemRational) (e : Nat)  : LemRational :=  r  ^  (Int.ofNat  e) -/

instance   : NumPow LemRational where

    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : OrdMaxMin LemRational where

    max   :=  max

    min   :=  min

/- removed value specification -/

/- 

instance   : Numeral LemReal where

    fromNumeral   n  :=  unsupportedRealFromNumeral  n
 -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
instance   : Eq0 LemReal where

    isEqual   :=  (fun x y => x == y)

    isInequal   n1  n2  :=  not  (n1  ==  n2)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/

instance   : Ord0 LemReal where

    compare   :=  defaultCompare

    isLess   :=  unsupportedRealLess

    isLessEqual   :=  unsupportedRealLessEq

    isGreater   :=  unsupportedRealGreater

    isGreaterEqual   :=  unsupportedRealGreaterEq


instance   : SetType LemReal where

    setElemCompare   :=  defaultCompare

/- removed value specification -/


instance   : NumAdd LemReal where

    numAdd   :=  (fun x y => x + y)

/- removed value specification -/


instance   : NumMinus LemReal where

    numMinus   :=  (fun x y => x - y)

/- removed value specification -/

/- removed top-level value definition -/

instance   : NumNegate LemReal where

    numNegate   :=  Neg.neg

/- removed value specification -/

/- removed top-level value definition -/

instance   : NumAbs LemReal where

    abs   :=  unsupportedRealAbs

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumSucc LemReal where

    succ   :=  (fun  n=> n  + unsupportedRealFromNumeral  1)

/- removed value specification -/

/- removed top-level value definition -/
instance   : NumPred LemReal where

    pred   :=  (fun  n=> n  - unsupportedRealFromNumeral  1)

/- removed value specification -/


instance   : NumMult LemReal where

    numMult   :=  (fun x y => x * y)

/- removed value specification -/


instance   : NumDivision LemReal where

    numDivision   :=  (fun x y => x / y)

/- removed value specification -/

/- 
def  realFromFrac  (n : Int) (d : Int)  : LemReal :=  (unsupportedRealFromInt  n)  /  (unsupportedRealFromInt  d) -/
/- removed value specification -/

/- 
 partial def  realPowInteger  (b : LemReal) (e : Int)  : LemReal := 
  if  e  =  0 then  1  else 
  if  >  e  0 then  b  ^  (e  -  1)  *  b  else 
  b  ^  (e  +  1)  /  b -/
/- removed value specification -/

/- 
def  realPowNat  (r : LemReal) (e : Nat)  : LemReal :=  r  ^  (Int.ofNat  e) -/

instance   : NumPow LemReal where

    numPow   :=  (fun x y => x ^ y)

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/

instance   : OrdMaxMin LemReal where

    max   :=  max

    min   :=  min

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
def  integerSqrt  (i : Int)  : Int :=  realFloor  (realSqrt  (unsupportedRealFromInt  i)) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
def  int32FromInteger  (i : Int)  : LemInt32 :=  (
  let  abs_int32  := lemInt32OfNat  (Int.natAbs  i); 
  if  (<  i  0) then  (~  abs_int32)  else  abs_int32 
) -/
/- removed value specification -/

/- 
def  int32FromInt  (i : Int)  : LemInt32 :=  lemInt32OfInt  (  i) -/
/- removed value specification -/

/- 
def  int32FromInt64  (i : LemInt64)  : LemInt32 :=  lemInt32OfInt  (lemInt64ToInt  i) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
def  int64FromInteger  (i : Int)  : LemInt64 :=  (
  let  abs_int64  := lemInt64OfNat  (Int.natAbs  i); 
  if  (<  i  0) then  (~  abs_int64)  else  abs_int64 
) -/
/- removed value specification -/

/- 
def  int64FromInt  (i : Int)  : LemInt64 :=  lemInt64OfInt  (  i) -/
/- removed value specification -/

/- 
def  int64FromInt32  (i : LemInt32)  : LemInt64 :=  lemInt64OfInt  (lemInt32ToInt  i) -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed top-level value definition -/
end Lem_Num

