/- Generated by Lem from num_extra.lem. -/

import LemLib

import LemLib.Assert_extra
import LemLib.String
import LemLib.Num
import LemLib.Basic_classes

namespace Lem_Num_extra
/-  ****************************************************  -/
/-                                                        -/
/-  A library of additional functions on numbers          -/
/-                                                        -/
/-  ****************************************************  -/

open Lem_Basic_classes

open Lem_Num

open Lem_String

open Lem_Assert_extra



/- removed value specification -/

/- removed value specification -/

/- removed value specification -/


def  integerOfChar   : Char → Int :=  fun (x : Char) =>  match x with  |  '0' => ( 0 :  Int) |  '1' => ( 1 :  Int) |  '2' => ( 2 :  Int) |  '3' => ( 3 :  Int) |  '4' => ( 4 :  Int) |  '5' => ( 5 :  Int) |  '6' => ( 6 :  Int) |  '7' => ( 7 :  Int) |  '8' => ( 8 :  Int) |  '9' => ( 9 :  Int) |  _ =>  failwith  "integerOfChar: unexpected character"

/- removed value specification -/


 def  integerOfStringHelper  (s : List (Char))  : Int :=  match  s with  |  d  ::  ds =>  integerOfChar  d  +  (( 10 :  Int)  *  integerOfStringHelper  ds) |  [] => ( 0 :  Int)


def  integerOfString  (s : String)  : Int :=  match  String.toList  s with  |  '-'  ::  ds =>  (Int.neg  (integerOfStringHelper  (List.reverse  ds))) |  ds =>  integerOfStringHelper  (List.reverse  ds)

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

end Lem_Num_extra

