/- Generated by Lem from set_extra.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Maybe
import LemLib.Function
import LemLib.Num
import LemLib.List
import LemLib.Sorting
import LemLib.Set

namespace Lem_Set_extra
/- **************************************************************************** -/
/-  A library for sets                                                          -/
/-                                                                              -/
/-  It mainly follows the Haskell Set-library                                   -/
/- **************************************************************************** -/

/-  ==========================================================================  -/
/-  Header                                                                      -/
/-  ==========================================================================  -/

open Lem_Bool
open Lem_Basic_classes
open Lem_Maybe
open Lem_Function
open Lem_Num
open Lem_List
open Lem_Sorting
open Lem_Set

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed top-level value definition -/
/- removed value specification -/

/- removed value specification -/

def  setCompare  {a : Type} [SetType a] [Ord0 a]   : List a → List a → LemOrdering :=  setCompareBy  Ord0.compare

instance (a : Type) [SetType a] : SetType (List  a) where

    setElemCompare   :=  setCompareBy  (@setElemCompare (a) _)

/- removed value specification -/

 partial def  leastFixedPointUnbounded  {a : Type} [SetType a]  (f : List a → List a) (x : List a)  : List a := 
   let  fx   := f  x; 
   if  (setSubsetBy  (@setElemCompare (a) _)  fx  x) then  x
    else  leastFixedPointUnbounded  f  ( (setUnionBy  (@setElemCompare (a) _) fx  x))
end Lem_Set_extra

