/- Generated by Lem from show.lem. -/

import LemLib

import LemLib.String
import LemLib.Maybe
import LemLib.Num
import LemLib.Basic_classes

namespace Lem_Show


open Lem_String
open Lem_Maybe
open Lem_Num
open Lem_Basic_classes




class Show (a : Type) where

  show0 : a →  String


export Show (show0)


instance   : Show String where

    show0   s  :=   String.append "\""   (String.append s  "\"")

/- removed value specification -/

def  stringFromMaybe  {a : Type}  (showX : a → String) (x : Option a)  : String := 
  match  x with  |  some  x =>   String.append "Just ("   (String.append (showX  x)  ")") |  none =>  "Nothing"
  

instance (a : Type) [Show a] : Show (Option  a) where

    show0   x_opt  :=  stringFromMaybe  (@show0 (a) _)  x_opt

/- removed value specification -/

 def  stringFromListAux  {a : Type}  (showX : a → String) (x : List a)  : String := 
  match  x with  |  [] =>  "" |  x :: xs' => (       match  xs' with  |  [] =>  showX  x |  _ =>   String.append (showX  x)   (String.append "; "  (stringFromListAux  showX  xs'))       )
  
/- removed value specification -/

def  stringFromList  {a : Type}  (showX : a → String) (xs : List a)  : String :=  
  String.append "["   (String.append (stringFromListAux  showX  xs)  "]")

instance (a : Type) [Show a] : Show (List  a) where

    show0   xs  :=  stringFromList  (@show0 (a) _)  xs

/- removed value specification -/

def  stringFromPair  {a : Type} {b : Type}  (showX : a → String) (showY : b → String) (p : (a ×b))  : String := match showX, showY, p with |  showX,  showY,  (x, y) =>   String.append "("   (String.append (showX  x)   (String.append ", "   (String.append (showY  y)  ")"))) 

instance (a b : Type) [Show a] [Show b] : Show ((a  × b)) where

    show0   :=  stringFromPair  (@show0 (a) _)  (@show0 (b) _)


instance   : Show Bool where

    show0   b  :=  if  b then  "true"  else  "false"

end Lem_Show

