/- Generated by Lem from sorting.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.Maybe
import LemLib.List
import LemLib.Num

namespace Lem_Sorting


open Lem_Bool
open Lem_Basic_classes
open Lem_Maybe
open Lem_List
open Lem_Num






/- removed value specification -/

/- removed value specification -/


 def  isPermutationBy  {a : Type}  (eq : a → a → Bool) (l1 : List a) (l2 : List a)  : Bool :=  match  l1 with  |  [] =>  List.isEmpty  l2 | ( x  ::  xs) =>  (       match  deleteFirst  (eq  x)  l2 with  |  none =>  false |  some  ys =>  isPermutationBy  eq  xs  ys            )



/- removed value specification -/

/- removed value specification -/


/-  DPM: rejigged the definition with a nested match to get past Coq's termination checker.  -/
 def  isSortedBy  {a : Type}  (cmp : a → a → Bool) (l : List a)  : Bool :=  match  l with  |  [] =>  true |  x1  ::  xs => (     match  xs with  |  [] =>  true |  x2  ::  _ =>  (cmp  x1  x2  &&  isSortedBy  cmp  xs)     )



/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/


 def  insertBy  {a : Type}  (cmp : a → a → Bool) (e : a) (l : List a)  : List a :=  match  l with  |  [] =>  [e] |  x  ::  xs => ( if  cmp  x  e then  x  ::  (insertBy  cmp  e  xs)  else  (e  ::  (x  ::  xs)))




def  insertSortBy  {a : Type}  (cmp : a → a → Bool) (l : List a)  : List a :=  List.foldl  (fun (l : List a) (e : a) =>  insertBy  cmp  e  l)  []  l

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

def  predicate_of_ord  {a : Type}  (f : a → a → LemOrdering) (x : a) (y : a)  : Bool := 
  match  f  x  y with  |  LemOrdering.LT =>  true |  LemOrdering.EQ =>  true |  LemOrdering.GT =>  false
  







end Lem_Sorting



