/- Generated by Lem from string.lem. -/

import LemLib

import LemLib.Bool
import LemLib.Basic_classes
import LemLib.List

namespace Lem_String


open Lem_Bool
open Lem_Basic_classes
open Lem_List




/- removed value specification -/

/- removed value specification -/

/- removed value specification -/

/- 
def  makeString  (len : Nat) (c : Char)  : String :=  String.ofList  (List.replicate  len  c) -/
/- removed value specification -/

/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/


def  string_case  {a : Type}  (s : String) (c_empty : a) (c_cons : Char → String → a)  : a := 
  match  (String.toList  s) with  |  [] =>  c_empty |  c  ::  cs =>  c_cons  c  (String.ofList  cs)
  
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

/- removed top-level value definition -/
/- removed value specification -/

 def  concat  (sep : String) (ss : List (String))  : String := 
  match  ss with  |  [] =>  "" |  s  ::  ss' => (       match  ss' with  |  [] =>  s |  _ =>   String.append s   (String.append sep  (concat  sep  ss'))       )
  
end Lem_String

